CREATE TYPE "public"."ihm_evidence_type" AS ENUM('NONE', 'DOC', 'CERT', 'MSDS', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."ihm_presence" AS ENUM('YES', 'NO', 'UNKNOWN');--> statement-breakpoint
CREATE TYPE "public"."inventory_event_type" AS ENUM('RECEIVE', 'CONSUME', 'ADJUST_OPENING_BALANCE', 'ADJUST_CORRECTION');--> statement-breakpoint
CREATE TYPE "public"."inventory_reference_type" AS ENUM('WORK_ORDER', 'MANUAL', 'EXCEL_IMPORT');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('Ship', 'Office', 'PMS Admin');--> statement-breakpoint
CREATE TABLE "alert_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"quiet_hours_enabled" boolean DEFAULT false NOT NULL,
	"quiet_hours_start" text,
	"quiet_hours_end" text,
	"escalation_enabled" boolean DEFAULT false NOT NULL,
	"escalation_hours" integer DEFAULT 4 NOT NULL,
	"escalation_recipients" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_deliveries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"channel" text NOT NULL,
	"recipient" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"sent_at" timestamp,
	"acknowledged_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"policy_id" integer NOT NULL,
	"alert_type" text NOT NULL,
	"priority" text NOT NULL,
	"object_type" text,
	"object_id" text,
	"vessel_id" text,
	"dedupe_key" text NOT NULL,
	"state" text,
	"payload" text NOT NULL,
	"ack_by" text,
	"ack_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_policies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_policies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alert_type" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"email_enabled" boolean DEFAULT false NOT NULL,
	"in_app_enabled" boolean DEFAULT true NOT NULL,
	"thresholds" text DEFAULT '{}' NOT NULL,
	"scope_filters" text DEFAULT '{}' NOT NULL,
	"recipients" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" text NOT NULL,
	"updated_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"user_id" text NOT NULL,
	"vessel_code" text,
	"component_code" text,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"action_type" text NOT NULL,
	"field_name" text,
	"old_value" text,
	"new_value" text,
	"source" text NOT NULL,
	"payload" json
);
--> statement-breakpoint
CREATE TABLE "bulk_import_errors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bulk_import_errors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"import_id" integer NOT NULL,
	"row_number" integer NOT NULL,
	"field_name" text,
	"field_value" text,
	"error_type" text NOT NULL,
	"error_description" text NOT NULL,
	"recommended_fix" text,
	"severity" text DEFAULT 'Error' NOT NULL,
	"raw_row_data" json,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bulk_import_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bulk_import_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_code" text,
	"vessel_name" text,
	"module_type" text NOT NULL,
	"sheet_name" text,
	"file_name" text NOT NULL,
	"file_size" integer,
	"uploaded_by" text NOT NULL,
	"uploaded_by_name" text,
	"uploaded_at" timestamp DEFAULT now() NOT NULL,
	"total_rows" integer DEFAULT 0 NOT NULL,
	"success_count" integer DEFAULT 0 NOT NULL,
	"failed_count" integer DEFAULT 0 NOT NULL,
	"skipped_count" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'Processing' NOT NULL,
	"error_summary" text,
	"is_fleet_import" boolean DEFAULT false NOT NULL,
	"template_version" text,
	"processing_time_ms" integer
);
--> statement-breakpoint
CREATE TABLE "certificates" (
	"id" text PRIMARY KEY NOT NULL,
	"certificate_name" text NOT NULL,
	"type" text NOT NULL,
	"vessel" text NOT NULL,
	"vessel_id" text,
	"issue_date" text,
	"expiry_date" text,
	"last_annual" text,
	"last_interm" text,
	"endorsement_date" text,
	"last_edit_upload" text,
	"applicable" boolean DEFAULT true NOT NULL,
	"attachments" json DEFAULT '[]'::json,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "change_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"reason" text NOT NULL,
	"target_type" text,
	"target_id" text,
	"snapshot_before_json" json,
	"proposed_changes_json" json,
	"move_preview_json" json,
	"status" text DEFAULT 'draft' NOT NULL,
	"requested_by_user_id" text NOT NULL,
	"submitted_at" timestamp,
	"reviewed_by_user_id" text,
	"reviewed_at" timestamp,
	"revision_number" integer DEFAULT 0 NOT NULL,
	"revision_history" json DEFAULT '[]'::json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_request_attachment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "change_request_attachment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"change_request_id" integer NOT NULL,
	"filename" text NOT NULL,
	"url" text NOT NULL,
	"uploaded_by_user_id" text NOT NULL,
	"uploaded_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_request_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "change_request_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"change_request_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "component_class_regulatory" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_class_regulatory_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_id" text NOT NULL,
	"component_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"classification_society" text NOT NULL,
	"survey_type" text NOT NULL,
	"certificate_number" text,
	"issue_date" text,
	"expiry_date" text,
	"last_class_survey" text,
	"next_survey_due" text,
	"class_requirements" text,
	"survey_status" text DEFAULT 'Active' NOT NULL,
	"remarks" text,
	"created_by" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "component_documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_id" text NOT NULL,
	"component_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"fleet_equipment_code" text,
	"file_name" text NOT NULL,
	"file_key" text NOT NULL,
	"file_type" text NOT NULL,
	"file_size" integer,
	"version" text DEFAULT '1.0' NOT NULL,
	"uploaded_by" text NOT NULL,
	"uploaded_at" timestamp DEFAULT now() NOT NULL,
	"can_ship_view" boolean DEFAULT true NOT NULL,
	"can_ship_download" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"notes" text,
	"storage_backend" text DEFAULT 'object'
);
--> statement-breakpoint
CREATE TABLE "component_maintenance_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_maintenance_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_id" text NOT NULL,
	"component_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"job_id" text,
	"job_code" text,
	"work_order_id" text NOT NULL,
	"work_order_no" text NOT NULL,
	"job_title" text NOT NULL,
	"maintenance_type" text NOT NULL,
	"date_completed" text NOT NULL,
	"running_hours_at_completion" numeric(10, 2),
	"performed_by" text NOT NULL,
	"approved_by" text,
	"approval_date" text,
	"status" text DEFAULT 'Approved' NOT NULL,
	"work_description" text,
	"spares_used" json,
	"remarks" text,
	"is_component_replaced" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "component_requisitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_requisitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requisition_no" text NOT NULL,
	"component_id" text NOT NULL,
	"component_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"raised_on" text NOT NULL,
	"item_or_service" text NOT NULL,
	"related_part_code" text,
	"related_part_name" text,
	"quantity" integer DEFAULT 1 NOT NULL,
	"uom" text DEFAULT 'EA',
	"status" text DEFAULT 'Draft' NOT NULL,
	"priority" text DEFAULT 'Normal' NOT NULL,
	"requested_by" text NOT NULL,
	"approved_by" text,
	"approval_date" text,
	"purchase_order_no" text,
	"expected_delivery" text,
	"actual_delivery" text,
	"supplier" text,
	"estimated_cost" numeric(10, 2),
	"actual_cost" numeric(10, 2),
	"remarks" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "component_requisitions_requisition_no_unique" UNIQUE("requisition_no")
);
--> statement-breakpoint
CREATE TABLE "component_running_hours_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_running_hours_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_code" text NOT NULL,
	"component_code" text NOT NULL,
	"component_id" text NOT NULL,
	"previous_rh" numeric(10, 2) NOT NULL,
	"new_rh" numeric(10, 2) NOT NULL,
	"delta_rh" numeric(10, 2) NOT NULL,
	"updated_by" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"update_source" text NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "components" (
	"id" text PRIMARY KEY NOT NULL,
	"fleet_equipment_code" text,
	"fleet_equipment_name" text,
	"parent_id" text,
	"component_code" text,
	"name" text,
	"component_category" text,
	"maker" text,
	"maker_code" text,
	"model" text,
	"model_code" text,
	"serial_no" text,
	"drawing_no" text,
	"location" text,
	"critical" boolean DEFAULT false,
	"condition_based" boolean DEFAULT false,
	"installation_date" text,
	"commissioned_date" text,
	"rating" text,
	"eqpt_system_dept" text,
	"is_active" boolean DEFAULT true,
	"vessel_code" text,
	"is_parent" boolean DEFAULT false,
	"notes" text,
	"vessel_id" text,
	"data_scope" text DEFAULT 'vessel' NOT NULL,
	"parent_fleet_equipment_code" text,
	"model_number" text,
	"department" text,
	"dept_category" text,
	"category" text,
	"class_item" boolean DEFAULT false,
	"no_of_units" text,
	"parent_component" text,
	"dimensions_size" text,
	"running_hours" numeric(10, 2),
	"current_cumulative_rh" numeric(10, 2) DEFAULT '0' NOT NULL,
	"last_updated" text,
	"applicable_vessel_ids" text[],
	"scope_notes" text,
	"rh_counter_type" text DEFAULT 'NOT_RH_DRIVEN' NOT NULL,
	"rh_counter_source" text,
	"rh_master_component_id" text,
	"rh_current_master" numeric(10, 2),
	"rh_master_updated_at" timestamp,
	"rh_master_updated_by" text,
	"rh_master_update_source" text,
	"rh_current_inherited_cached" numeric(10, 2),
	"rh_inherited_updated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "defect_actions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"defect_id" text NOT NULL,
	"action_type" text NOT NULL,
	"action_description" text NOT NULL,
	"proposed_by" text NOT NULL,
	"responsibility" text NOT NULL,
	"due_date" text NOT NULL,
	"date_completed" text,
	"status" text DEFAULT 'Open' NOT NULL,
	"justification" text,
	"attachment_urls" text[],
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "defect_attachments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_attachments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"defect_id" text NOT NULL,
	"filename" text NOT NULL,
	"url" text NOT NULL,
	"attachment_type" text NOT NULL,
	"uploaded_by" text NOT NULL,
	"uploaded_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "defect_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "defect_categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "defect_sequences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_sequences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"year" integer NOT NULL,
	"last_sequence" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "defect_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "defect_types_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "defects" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"vessel_name" text NOT NULL,
	"issue_date" text NOT NULL,
	"category" text NOT NULL,
	"defect_type" text,
	"description" text NOT NULL,
	"description_html" text,
	"description_text" text,
	"action_taken_requested" text,
	"target_close_date" text,
	"date_completed" text,
	"status" text DEFAULT 'Open' NOT NULL,
	"priority" text DEFAULT 'Medium',
	"critical" boolean DEFAULT false NOT NULL,
	"is_coc" boolean DEFAULT false NOT NULL,
	"severity" integer DEFAULT 1,
	"source" text,
	"equipment_category" text,
	"equipment_type" text,
	"equipment_make" text,
	"equipment_model" text,
	"equipment_serial_no" text,
	"equipment_location" text,
	"equipment_system" text,
	"component_id" text,
	"purchase_order_ref" text,
	"responsible_dept" text,
	"verified_date" text,
	"defect_category" text,
	"viq_version" text,
	"viq_ref" text,
	"viq_chapter" text,
	"viq_section" text,
	"sfi_code_ref" text,
	"sire_hardware_id" text,
	"sire_hardware_level1" text,
	"sire_hardware_level2" text,
	"sire_hardware_level3" text,
	"component_hardware_id" text,
	"component_hardware_level1" text,
	"component_hardware_level2" text,
	"component_hardware_level3" text,
	"immediate_cause" json,
	"immediate_cause_explanation" text,
	"root_cause" json,
	"root_cause_explanation" text,
	"risk_level" text,
	"hold_reason" text,
	"next_review_date" text,
	"seed_id" text,
	"equipment_key" text,
	"raised_by_id" text,
	"raised_by_name" text,
	"raised_by_rank" text,
	"operating_condition" text,
	"location_text" text,
	"occurrence_type" text,
	"responsible_role" text,
	"responsible_role_id" text,
	"is_deferred" boolean DEFAULT false NOT NULL,
	"defer_reason" text,
	"defer_new_target_date" text,
	"defer_approval_required" boolean DEFAULT true,
	"report_to_third_party" boolean DEFAULT false NOT NULL,
	"class_report" boolean DEFAULT false NOT NULL,
	"flag_report" boolean DEFAULT false NOT NULL,
	"port_report" boolean DEFAULT false NOT NULL,
	"report_reference_no" text,
	"report_date" text,
	"date_reported_to_office" text,
	"date_registered_in_system" text,
	"vessel_location_type" text,
	"port_name" text,
	"latitude" text,
	"longitude" text,
	"vessel_location_detail" text,
	"reported_by" text NOT NULL,
	"assigned_to" text,
	"reviewed_by" text,
	"closed_by" text,
	"closed_on" text,
	"closure_comment" text,
	"closure_files" text[],
	"linked_defects" text[],
	"notes" json DEFAULT '[]'::json,
	"actions" json,
	"attachments" json,
	"audit_trail" json DEFAULT '[]'::json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "equipment_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "equipment_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "equipment_categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "fleet_component_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_component_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_equipment_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"component_code" text NOT NULL,
	"component_id" text,
	"component_name" text,
	"mapped_by" text NOT NULL,
	"mapped_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unique_fleet_component_mapping" UNIQUE("fleet_equipment_code","vessel_code","component_code")
);
--> statement-breakpoint
CREATE TABLE "fleet_equipment_master" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_equipment_master_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_equipment_code" text NOT NULL,
	"fleet_equipment_name" text NOT NULL,
	"maker" text,
	"maker_code" text,
	"model" text,
	"model_code" text,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "fleet_equipment_master_fleet_equipment_code_unique" UNIQUE("fleet_equipment_code")
);
--> statement-breakpoint
CREATE TABLE "fleet_job_vessel_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_job_vessel_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_equipment_code" text NOT NULL,
	"job_code" text NOT NULL,
	"job_id" text,
	"vessel_code" text NOT NULL,
	"vessel_name" text,
	"mapped_by" text NOT NULL,
	"mapped_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unique_fleet_job_vessel_mapping" UNIQUE("job_code","vessel_code")
);
--> statement-breakpoint
CREATE TABLE "fleet_spare_vessel_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_spare_vessel_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_equipment_code" text NOT NULL,
	"part_code" text NOT NULL,
	"spare_id" text,
	"vessel_code" text NOT NULL,
	"vessel_name" text,
	"mapped_by" text NOT NULL,
	"mapped_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unique_fleet_spare_vessel_mapping" UNIQUE("part_code","vessel_code")
);
--> statement-breakpoint
CREATE TABLE "fleet_vessel_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_vessel_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_equipment_code" text NOT NULL,
	"vessel_code" text NOT NULL,
	"vessel_name" text,
	"mapped_by" text NOT NULL,
	"mapped_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unique_fleet_vessel_mapping" UNIQUE("fleet_equipment_code","vessel_code")
);
--> statement-breakpoint
CREATE TABLE "fleets" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "fleets_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "form_definitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "form_definitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"subgroup" text,
	CONSTRAINT "form_definitions_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "form_version_usage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "form_version_usage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_version_id" integer NOT NULL,
	"used_in_module" text NOT NULL,
	"used_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "form_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "form_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_id" integer NOT NULL,
	"version_no" integer NOT NULL,
	"version_date" timestamp NOT NULL,
	"status" text NOT NULL,
	"author_user_id" text NOT NULL,
	"changelog" text,
	"schema_json" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ihm_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ihm_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_id" text NOT NULL,
	"spare_id" text,
	"presence" text NOT NULL,
	"materials" text[],
	"evidence_type" text,
	"evidence_file_name" text,
	"verified_date" text,
	"supplier" text,
	"remarks" text,
	"vessel_id" text DEFAULT 'V001' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ihm_maintenance_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ihm_maintenance_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"work_order_id" text NOT NULL,
	"action" text NOT NULL,
	"target_component" text,
	"target_spare" text,
	"quantity" numeric(10, 2),
	"location" text,
	"materials" text[],
	"remarks" text,
	"vessel_id" text DEFAULT 'V001' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_change_log" (
	"id" text PRIMARY KEY NOT NULL,
	"import_history_id" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"operation" text NOT NULL,
	"previous_data" json,
	"new_data" json,
	"checksum" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_history" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"mode" text NOT NULL,
	"archive_missing" boolean DEFAULT false NOT NULL,
	"user_id" text NOT NULL,
	"vessel_id" text,
	"created" integer DEFAULT 0 NOT NULL,
	"updated" integer DEFAULT 0 NOT NULL,
	"skipped" integer DEFAULT 0 NOT NULL,
	"archived" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"finished_at" timestamp,
	"status" text NOT NULL,
	"original_name" text,
	"file_size" integer,
	"stored_file_path" text,
	"undone_at" timestamp,
	"error_message" text
);
--> statement-breakpoint
CREATE TABLE "inventory_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inventory_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"txn_datetime" timestamp DEFAULT now() NOT NULL,
	"spare_id" integer NOT NULL,
	"location_id" integer,
	"event_type" text NOT NULL,
	"qty_change" integer NOT NULL,
	"rob_total_before" integer NOT NULL,
	"rob_total_after" integer NOT NULL,
	"rob_location_before" integer,
	"rob_location_after" integer,
	"reference_type" text NOT NULL,
	"reference_id" text,
	"reference_note" text,
	"user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_component_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_component_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"job_id" text NOT NULL,
	"component_id" text NOT NULL,
	"component_code" text,
	"linked_by" text NOT NULL,
	"linked_at" timestamp DEFAULT now() NOT NULL,
	"last_done_date" text,
	"next_due_date" text,
	"last_done_rh" text,
	"next_due_rh" text,
	"updated_at" timestamp,
	CONSTRAINT "unique_job_component_link" UNIQUE("job_id","component_id")
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" text,
	"component_id" text,
	"component_code" text,
	"component_name" text,
	"job_no" text NOT NULL,
	"job_title" text NOT NULL,
	"assigned_to" text,
	"maintenance_type" text,
	"maintenance_basis" text,
	"frequency_type" text,
	"frequency_value" text,
	"frequency_unit" text,
	"interval_running_hour" integer,
	"lead_time_value" integer,
	"lead_time_unit" text,
	"initial_next_due" text,
	"last_done_date" text,
	"next_due_date" text,
	"last_done_rh" text,
	"next_due_rh" text,
	"job_priority" text,
	"class_related" text,
	"brief_work_description" text,
	"job_description" text,
	"approver" text,
	"department" text,
	"required_spare_parts" json DEFAULT '[]'::json NOT NULL,
	"required_tools" json DEFAULT '[]'::json NOT NULL,
	"safety_requirements" json DEFAULT '{"ppeRequirements":[],"permitRequirements":[],"otherRequirements":[]}'::json NOT NULL,
	"data_scope" text DEFAULT 'vessel' NOT NULL,
	"fleet_equipment_code" text,
	"fleet_job_code" text,
	"sfi_code" text,
	"criticality" text,
	"is_active" boolean DEFAULT true,
	"estimated_man_hours" numeric(6, 2),
	"created_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"location_name" text NOT NULL,
	"location_type" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"created_by" text NOT NULL,
	CONSTRAINT "unique_vessel_location" UNIQUE("vessel_id","location_name")
);
--> statement-breakpoint
CREATE TABLE "maker_list" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maker_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"maker_code" text NOT NULL,
	"maker_name" text NOT NULL,
	"address" text,
	"address_id" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "maker_list_maker_code_unique" UNIQUE("maker_code")
);
--> statement-breakpoint
CREATE TABLE "makers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "makers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"maker_code" text NOT NULL,
	"maker_name" text NOT NULL,
	"address" text,
	"address_id" text,
	"contact_person" text,
	"email" text,
	"phone" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "makers_maker_code_unique" UNIQUE("maker_code")
);
--> statement-breakpoint
CREATE TABLE "master_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "master_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sl_no" integer,
	"maker_name" text NOT NULL,
	"maker_code" text NOT NULL,
	"count_maker" integer,
	"model" text NOT NULL,
	"model_code" text NOT NULL,
	"count_sfi_code" integer,
	"fleet_equipment_code" text NOT NULL,
	"sfi_code" text NOT NULL,
	"assigned_sub_code" text,
	"vessel_name" text,
	"vessel_code" text,
	"equipment_name" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "master_data_fleet_equipment_code_unique" UNIQUE("fleet_equipment_code")
);
--> statement-breakpoint
CREATE TABLE "master_lists" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "master_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"list_type" text NOT NULL,
	"list_key" text NOT NULL,
	"list_value" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_list_type_key" UNIQUE("list_type","list_key")
);
--> statement-breakpoint
CREATE TABLE "pms_vessel_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pms_vessel_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"calendar_lead_days_critical" integer DEFAULT 7 NOT NULL,
	"calendar_lead_days_non_critical" integer DEFAULT 14 NOT NULL,
	"calendar_grace_mode" text DEFAULT 'COMPANY_STANDARD' NOT NULL,
	"calendar_grace_days" integer DEFAULT 7 NOT NULL,
	"rh_lead_hours_critical" integer DEFAULT 50 NOT NULL,
	"rh_lead_hours_non_critical" integer DEFAULT 100 NOT NULL,
	"rh_grace_hours" integer DEFAULT 168 NOT NULL,
	"location_a_name" text DEFAULT 'Location A' NOT NULL,
	"location_b_name" text DEFAULT 'Location B' NOT NULL,
	"updated_by" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pms_vessel_settings_vessel_id_unique" UNIQUE("vessel_id")
);
--> statement-breakpoint
CREATE TABLE "recurring_defect_links" (
	"recurring_id" integer NOT NULL,
	"defect_id" text NOT NULL,
	CONSTRAINT "recurring_defect_links_recurring_id_defect_id_pk" PRIMARY KEY("recurring_id","defect_id")
);
--> statement-breakpoint
CREATE TABLE "recurring_defects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recurring_defects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"equipment_key" text NOT NULL,
	"window_months" integer DEFAULT 12 NOT NULL,
	"occurrence_count" integer NOT NULL,
	"open_count" integer NOT NULL,
	"vessels_affected" integer NOT NULL,
	"last_occurrence_date" text NOT NULL,
	"has_coc" boolean DEFAULT false NOT NULL,
	"mtbf_days" numeric,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "running_hours_audit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "running_hours_audit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"component_id" text NOT NULL,
	"previous_rh" numeric(10, 2) NOT NULL,
	"new_rh" numeric(10, 2) NOT NULL,
	"cumulative_rh" numeric(10, 2) NOT NULL,
	"date_updated_local" text NOT NULL,
	"date_updated_tz" text NOT NULL,
	"entered_at_utc" timestamp NOT NULL,
	"user_id" text NOT NULL,
	"source" text NOT NULL,
	"notes" text,
	"meter_replaced" boolean DEFAULT false NOT NULL,
	"old_meter_final" numeric(10, 2),
	"new_meter_start" numeric(10, 2),
	"version" integer DEFAULT 1 NOT NULL,
	"is_renewal_reset" boolean DEFAULT false NOT NULL,
	"renewal_action_type" text,
	"renewal_reason" text,
	"renewal_reference" text,
	"renewal_evidence_urls" json,
	"component_code" text,
	"component_name" text
);
--> statement-breakpoint
CREATE TABLE "sfi_details" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sfi_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_code" text NOT NULL,
	"component_name" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "sfi_details_component_code_unique" UNIQUE("component_code")
);
--> statement-breakpoint
CREATE TABLE "spare_component_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spare_component_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"spare_id" integer NOT NULL,
	"component_id" text NOT NULL,
	"linked_by" text NOT NULL,
	"linked_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_spare_component_link" UNIQUE("spare_id","component_id")
);
--> statement-breakpoint
CREATE TABLE "spare_location_stock" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spare_location_stock_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"spare_id" integer NOT NULL,
	"location_id" integer NOT NULL,
	"qty" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "unique_spare_location_stock" UNIQUE("spare_id","location_id")
);
--> statement-breakpoint
CREATE TABLE "spares" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spares_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"part_code" text NOT NULL,
	"part_name" text NOT NULL,
	"component_id" text,
	"component_code" text,
	"component_name" text NOT NULL,
	"component_spare_code" text,
	"critical" text NOT NULL,
	"rob" integer DEFAULT 0 NOT NULL,
	"rob_location_a" integer DEFAULT 0 NOT NULL,
	"rob_location_b" integer DEFAULT 0 NOT NULL,
	"min" integer DEFAULT 0 NOT NULL,
	"max" integer,
	"unit_cost" numeric(10, 2),
	"stocking_number" text,
	"lead_time" text,
	"supplier" text,
	"last_order_date" text,
	"location" text,
	"vessel_id" text,
	"deleted" boolean DEFAULT false NOT NULL,
	"data_scope" text DEFAULT 'vessel' NOT NULL,
	"fleet_equipment_code" text,
	"fleet_part_code" text,
	"part_number" text,
	"uom" text,
	"drawing_number" text,
	"drawing_no" text,
	"location_2" text,
	"remarks" text,
	"unit" text,
	"position_number" text,
	"note" text,
	"specification" text,
	"maker" text,
	"maker_code" text,
	"model" text,
	"manual_name" text,
	"page_number" text,
	"criticality" text,
	"is_active" boolean DEFAULT true,
	"ihm" text,
	"ihm_presence" text DEFAULT 'UNKNOWN',
	"evidence_type" text,
	"part_category" text,
	"applicable_vessel_ids" text[],
	"scope_notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"created_by" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "unique_fleet_part_code_vessel" UNIQUE("fleet_part_code","data_scope","vessel_id")
);
--> statement-breakpoint
CREATE TABLE "spares_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spares_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timestamp_utc" timestamp NOT NULL,
	"vessel_id" text NOT NULL,
	"spare_id" integer NOT NULL,
	"part_code" text NOT NULL,
	"part_name" text NOT NULL,
	"component_id" text NOT NULL,
	"component_code" text,
	"component_name" text NOT NULL,
	"component_spare_code" text,
	"event_type" text NOT NULL,
	"qty_change" integer NOT NULL,
	"rob_after" integer NOT NULL,
	"user_id" text NOT NULL,
	"remarks" text,
	"reference" text,
	"date_local" text,
	"tz" text,
	"place" text
);
--> statement-breakpoint
CREATE TABLE "stores_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stores_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"item_type" text NOT NULL,
	"item_code" text NOT NULL,
	"impa_code" text,
	"item_name" text NOT NULL,
	"category" text,
	"specification" text,
	"uom" text,
	"rob" numeric(10, 2) DEFAULT '0' NOT NULL,
	"rob_location_a" numeric(10, 2) DEFAULT '0' NOT NULL,
	"rob_location_b" numeric(10, 2) DEFAULT '0' NOT NULL,
	"location_a" text,
	"location_b" text,
	"min" numeric(10, 2) DEFAULT '0' NOT NULL,
	"max" numeric(10, 2),
	"unit_cost" numeric(10, 2),
	"supplier" text,
	"last_order_date" text,
	"lead_time" text,
	"ihm" boolean DEFAULT false NOT NULL,
	"ihm_details" text,
	"remarks" text,
	"deleted" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stores_ledger" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stores_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"section" text NOT NULL,
	"item_id" integer NOT NULL,
	"part_code" text NOT NULL,
	"item_name" text NOT NULL,
	"uom" text,
	"event_type" text NOT NULL,
	"qty_change_base" numeric(10, 2) NOT NULL,
	"qty_display" numeric(10, 2) NOT NULL,
	"uom_display" text,
	"rob_after_base" numeric(10, 2) NOT NULL,
	"date_local" text NOT NULL,
	"tz" text NOT NULL,
	"timestamp_utc" timestamp NOT NULL,
	"place" text,
	"ref" text,
	"user_id" text NOT NULL,
	"remarks" text
);
--> statement-breakpoint
CREATE TABLE "surveys" (
	"id" text PRIMARY KEY NOT NULL,
	"survey_name" text NOT NULL,
	"type" text NOT NULL,
	"vessel" text NOT NULL,
	"vessel_id" text,
	"survey_date" text,
	"due_date" text,
	"first_range_date" text,
	"second_range_date" text,
	"postponed" text,
	"last_edit" text,
	"applicable" boolean DEFAULT true NOT NULL,
	"attachments" json DEFAULT '[]'::json,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password" text NOT NULL,
	"full_name" text NOT NULL,
	"email" text,
	"role" "user_role" DEFAULT 'Ship' NOT NULL,
	"vessel_id" text,
	"department" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "vessels" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"code" text NOT NULL,
	"fleet_id" text,
	"imo_number" text,
	"vessel_type" text,
	"flag" text,
	"vessel_sequence" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "work_order_execution_details" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "work_order_execution_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"work_order_id" text NOT NULL,
	"vessel_id" text NOT NULL,
	"executed_by" text,
	"executed_date" text,
	"completion_notes" text,
	"parts_used" json DEFAULT '[]'::json,
	"tools_used" json DEFAULT '[]'::json,
	"labor_hours" numeric(6, 2),
	"findings" text,
	"recommendations" text,
	"next_action_required" text,
	"quality_check_by" text,
	"quality_check_date" text,
	"quality_check_notes" text,
	"attachments" json DEFAULT '[]'::json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "work_order_executions" (
	"id" text PRIMARY KEY NOT NULL,
	"template_id" text NOT NULL,
	"component_id" text NOT NULL,
	"vessel_id" text NOT NULL,
	"execution_id" text NOT NULL,
	"date_completed" text,
	"running_hours_at_completion" numeric(10, 2),
	"performed_by" text,
	"approved_by" text,
	"status" text DEFAULT 'In Progress' NOT NULL,
	"uploaded_documents" json DEFAULT '[]'::json NOT NULL,
	"consumed_spare_parts" json DEFAULT '[]'::json NOT NULL,
	"work_description" text,
	"remarks" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "work_order_executions_execution_id_unique" UNIQUE("execution_id")
);
--> statement-breakpoint
CREATE TABLE "work_orders" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" text,
	"component" text NOT NULL,
	"component_code" text,
	"job_id" text,
	"work_order_no" text NOT NULL,
	"work_order_type" text DEFAULT 'Planned' NOT NULL,
	"template_code" text,
	"execution_id" text,
	"job_title" text NOT NULL,
	"assigned_to" text NOT NULL,
	"due_date" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"date_completed" text,
	"submitted_date" text,
	"form_data" json,
	"task_type" text,
	"maintenance_type" text,
	"maintenance_basis" text,
	"frequency_value" text,
	"frequency_unit" text,
	"approver_remarks" text,
	"is_execution" boolean DEFAULT false NOT NULL,
	"template_id" text,
	"approver" text,
	"approval_date" text,
	"rejection_date" text,
	"next_due_date" text,
	"next_due_reading" text,
	"current_reading" text,
	"class_related" text,
	"job_priority" text,
	"brief_work_description" text,
	"data_scope" text DEFAULT 'vessel' NOT NULL,
	"fleet_equipment_code" text,
	"fleet_job_code" text,
	"job_group" text,
	"job_category" text,
	"sfi_code" text,
	"maintenance_interval_value" integer,
	"maintenance_interval_unit" text,
	"interval_running_hour" integer,
	"department" text,
	"criticality" text,
	"is_active" boolean DEFAULT true,
	"applicable_vessel_ids" text[],
	"scope_notes" text,
	"postponement_end_date" text,
	"postponement_reason" text,
	"postponement_authorized_by" text,
	"on_demand_reason" text,
	"required_spare_parts" json DEFAULT '[]'::json NOT NULL,
	"required_tools" json DEFAULT '[]'::json NOT NULL,
	"safety_requirements" json DEFAULT '{"ppeRequirements":[],"permitRequirements":[],"otherRequirements":[]}'::json NOT NULL,
	"uploaded_documents" json DEFAULT '[]'::json NOT NULL,
	"consumed_spare_parts" json DEFAULT '[]'::json NOT NULL,
	"risk_assessment_status" text,
	"safety_checklists_status" text,
	"operational_forms_status" text,
	"start_date_time" text,
	"completion_date_time" text,
	"execution_assigned_to" text,
	"performed_by" text,
	"no_of_persons" text,
	"total_time_hours" text,
	"manhours" text,
	"work_carried_out" text,
	"job_experience_notes" text,
	"previous_reading" text,
	"running_hours" text,
	"running_hours_difference" text,
	"reading_date" text,
	"wo_execution_id" text,
	"remarks" text,
	"completion_remarks" text,
	"rejection_comments" text,
	"approval_action" text,
	"driver_type" text,
	"cycle_due_rh_snapshot" numeric(10, 2),
	"generate_rh_snapshot" numeric(10, 2),
	"due_rh_snapshot" numeric(10, 2),
	"effective_rh_at_generation" numeric(10, 2),
	"rh_last_done_snapshot" numeric(10, 2),
	"cycle_due_date_snapshot" text,
	"generate_date_snapshot" text,
	"due_date_snapshot" text,
	"last_done_date_snapshot" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_fleet_job_code_vessel" UNIQUE("fleet_job_code","data_scope","vessel_id")
);
--> statement-breakpoint
ALTER TABLE "import_change_log" ADD CONSTRAINT "import_change_log_import_history_id_import_history_id_fk" FOREIGN KEY ("import_history_id") REFERENCES "public"."import_history"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_defect_links" ADD CONSTRAINT "recurring_defect_links_recurring_id_recurring_defects_id_fk" FOREIGN KEY ("recurring_id") REFERENCES "public"."recurring_defects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_defect_links" ADD CONSTRAINT "recurring_defect_links_defect_id_defects_id_fk" FOREIGN KEY ("defect_id") REFERENCES "public"."defects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_event_deliveries" ON "alert_deliveries" USING btree ("event_id","channel");--> statement-breakpoint
CREATE INDEX "idx_recipient_deliveries" ON "alert_deliveries" USING btree ("recipient","status");--> statement-breakpoint
CREATE INDEX "idx_dedupe_key" ON "alert_events" USING btree ("dedupe_key","created_at");--> statement-breakpoint
CREATE INDEX "idx_policy_events" ON "alert_events" USING btree ("policy_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_timestamp" ON "audit_log" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_audit_user_id" ON "audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_audit_vessel_code" ON "audit_log" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_audit_entity_type" ON "audit_log" USING btree ("entity_type");--> statement-breakpoint
CREATE INDEX "idx_audit_entity_id" ON "audit_log" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "idx_audit_action_type" ON "audit_log" USING btree ("action_type");--> statement-breakpoint
CREATE INDEX "idx_bulk_error_import" ON "bulk_import_errors" USING btree ("import_id");--> statement-breakpoint
CREATE INDEX "idx_bulk_error_row" ON "bulk_import_errors" USING btree ("import_id","row_number");--> statement-breakpoint
CREATE INDEX "idx_bulk_error_type" ON "bulk_import_errors" USING btree ("error_type");--> statement-breakpoint
CREATE INDEX "idx_bulk_import_vessel" ON "bulk_import_history" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_bulk_import_module" ON "bulk_import_history" USING btree ("module_type");--> statement-breakpoint
CREATE INDEX "idx_bulk_import_date" ON "bulk_import_history" USING btree ("uploaded_at");--> statement-breakpoint
CREATE INDEX "idx_bulk_import_status" ON "bulk_import_history" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_certificates_vessel" ON "certificates" USING btree ("vessel");--> statement-breakpoint
CREATE INDEX "idx_certificates_type" ON "certificates" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_certificates_expiry" ON "certificates" USING btree ("expiry_date");--> statement-breakpoint
CREATE INDEX "idx_vessel_category" ON "change_request" USING btree ("vessel_id","category");--> statement-breakpoint
CREATE INDEX "idx_change_request_status" ON "change_request" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_change_request" ON "change_request_attachment" USING btree ("change_request_id");--> statement-breakpoint
CREATE INDEX "idx_change_request_comment" ON "change_request_comment" USING btree ("change_request_id");--> statement-breakpoint
CREATE INDEX "idx_class_component_id" ON "component_class_regulatory" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_class_component_code" ON "component_class_regulatory" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_class_vessel_code" ON "component_class_regulatory" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_class_survey_type" ON "component_class_regulatory" USING btree ("survey_type");--> statement-breakpoint
CREATE INDEX "idx_class_expiry_date" ON "component_class_regulatory" USING btree ("expiry_date");--> statement-breakpoint
CREATE INDEX "idx_doc_component_id" ON "component_documents" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_doc_component_code" ON "component_documents" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_doc_vessel_code" ON "component_documents" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_doc_fleet_equipment_code" ON "component_documents" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_doc_file_type" ON "component_documents" USING btree ("file_type");--> statement-breakpoint
CREATE INDEX "idx_history_component_id" ON "component_maintenance_history" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_history_component_code" ON "component_maintenance_history" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_history_vessel_code" ON "component_maintenance_history" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_history_job_id" ON "component_maintenance_history" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "idx_history_job_code" ON "component_maintenance_history" USING btree ("job_code");--> statement-breakpoint
CREATE INDEX "idx_history_work_order_id" ON "component_maintenance_history" USING btree ("work_order_id");--> statement-breakpoint
CREATE INDEX "idx_history_date_completed" ON "component_maintenance_history" USING btree ("date_completed");--> statement-breakpoint
CREATE INDEX "idx_req_component_id" ON "component_requisitions" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_req_component_code" ON "component_requisitions" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_req_vessel_code" ON "component_requisitions" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_req_status" ON "component_requisitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_req_no" ON "component_requisitions" USING btree ("requisition_no");--> statement-breakpoint
CREATE INDEX "idx_rh_log_component_code" ON "component_running_hours_log" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_rh_log_vessel_code" ON "component_running_hours_log" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_rh_log_updated_at" ON "component_running_hours_log" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_rh_log_update_source" ON "component_running_hours_log" USING btree ("update_source");--> statement-breakpoint
CREATE INDEX "idx_comp_data_scope" ON "components" USING btree ("data_scope");--> statement-breakpoint
CREATE INDEX "idx_comp_fleet_tree" ON "components" USING btree ("data_scope","parent_fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_comp_vessel_tree" ON "components" USING btree ("data_scope","vessel_id","parent_id");--> statement-breakpoint
CREATE INDEX "idx_comp_fleet_equipment_code" ON "components" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_comp_rh_master" ON "components" USING btree ("rh_counter_type","vessel_id");--> statement-breakpoint
CREATE INDEX "idx_comp_rh_inherited" ON "components" USING btree ("rh_master_component_id");--> statement-breakpoint
CREATE INDEX "idx_action_defect" ON "defect_actions" USING btree ("defect_id");--> statement-breakpoint
CREATE INDEX "idx_action_status" ON "defect_actions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_action_due_date" ON "defect_actions" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "idx_action_responsibility" ON "defect_actions" USING btree ("responsibility");--> statement-breakpoint
CREATE INDEX "idx_attachment_defect" ON "defect_attachments" USING btree ("defect_id");--> statement-breakpoint
CREATE INDEX "idx_attachment_type" ON "defect_attachments" USING btree ("attachment_type");--> statement-breakpoint
CREATE INDEX "idx_defect_seq_vessel_year" ON "defect_sequences" USING btree ("vessel_id","year");--> statement-breakpoint
CREATE INDEX "idx_defect_vessel" ON "defects" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_defect_status" ON "defects" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_defect_issue_date" ON "defects" USING btree ("issue_date");--> statement-breakpoint
CREATE INDEX "idx_defect_category" ON "defects" USING btree ("category");--> statement-breakpoint
CREATE INDEX "idx_defect_critical" ON "defects" USING btree ("critical");--> statement-breakpoint
CREATE INDEX "idx_defect_component" ON "defects" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_fleet_comp_mapping_fleet" ON "fleet_component_mapping" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_comp_mapping_vessel" ON "fleet_component_mapping" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_comp_mapping_component" ON "fleet_component_mapping" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_equipment_code" ON "fleet_equipment_master" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_maker_code" ON "fleet_equipment_master" USING btree ("maker_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_model_code" ON "fleet_equipment_master" USING btree ("model_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_job_mapping_fleet" ON "fleet_job_vessel_mapping" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_job_mapping_job" ON "fleet_job_vessel_mapping" USING btree ("job_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_job_mapping_vessel" ON "fleet_job_vessel_mapping" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_spare_mapping_fleet" ON "fleet_spare_vessel_mapping" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_spare_mapping_part" ON "fleet_spare_vessel_mapping" USING btree ("part_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_spare_mapping_vessel" ON "fleet_spare_vessel_mapping" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_vessel_mapping_fleet" ON "fleet_vessel_mapping" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_vessel_mapping_vessel" ON "fleet_vessel_mapping" USING btree ("vessel_code");--> statement-breakpoint
CREATE INDEX "idx_form_id" ON "form_versions" USING btree ("form_id");--> statement-breakpoint
CREATE INDEX "idx_form_version_status" ON "form_versions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_ihm_component_id" ON "ihm_items" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_ihm_spare_id" ON "ihm_items" USING btree ("spare_id");--> statement-breakpoint
CREATE INDEX "idx_ihm_log_wo_id" ON "ihm_maintenance_log" USING btree ("work_order_id");--> statement-breakpoint
CREATE INDEX "idx_ihm_log_created" ON "ihm_maintenance_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_change_log_import" ON "import_change_log" USING btree ("import_history_id");--> statement-breakpoint
CREATE INDEX "idx_change_log_entity" ON "import_change_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "idx_import_history_type" ON "import_history" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_import_history_started" ON "import_history" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "idx_import_history_vessel" ON "import_history" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_vessel" ON "inventory_transactions" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_spare" ON "inventory_transactions" USING btree ("spare_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_location" ON "inventory_transactions" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_datetime" ON "inventory_transactions" USING btree ("txn_datetime");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_event" ON "inventory_transactions" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "idx_inventory_txn_ref_type" ON "inventory_transactions" USING btree ("reference_type");--> statement-breakpoint
CREATE INDEX "idx_job_component_link_job" ON "job_component_links" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "idx_job_component_link_component" ON "job_component_links" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_job_component_link_vessel" ON "job_component_links" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_job_vessel" ON "jobs" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_job_component" ON "jobs" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_job_component_code" ON "jobs" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_job_data_scope" ON "jobs" USING btree ("data_scope");--> statement-breakpoint
CREATE INDEX "idx_job_next_due" ON "jobs" USING btree ("next_due_date");--> statement-breakpoint
CREATE INDEX "idx_location_vessel" ON "locations" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_maker_list_code" ON "maker_list" USING btree ("maker_code");--> statement-breakpoint
CREATE INDEX "idx_maker_list_name" ON "maker_list" USING btree ("maker_name");--> statement-breakpoint
CREATE INDEX "idx_maker_code" ON "makers" USING btree ("maker_code");--> statement-breakpoint
CREATE INDEX "idx_maker_name" ON "makers" USING btree ("maker_name");--> statement-breakpoint
CREATE INDEX "idx_master_data_fleet_code" ON "master_data" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_master_data_sfi" ON "master_data" USING btree ("sfi_code");--> statement-breakpoint
CREATE INDEX "idx_master_data_maker" ON "master_data" USING btree ("maker_code");--> statement-breakpoint
CREATE INDEX "idx_master_data_model" ON "master_data" USING btree ("model_code");--> statement-breakpoint
CREATE INDEX "idx_master_list_type" ON "master_lists" USING btree ("list_type");--> statement-breakpoint
CREATE INDEX "idx_pms_settings_vessel_id" ON "pms_vessel_settings" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_link_recurring" ON "recurring_defect_links" USING btree ("recurring_id");--> statement-breakpoint
CREATE INDEX "idx_link_defect" ON "recurring_defect_links" USING btree ("defect_id");--> statement-breakpoint
CREATE INDEX "idx_recurring_key_window" ON "recurring_defects" USING btree ("equipment_key","window_months");--> statement-breakpoint
CREATE INDEX "idx_recurring_updated" ON "recurring_defects" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_component_entered" ON "running_hours_audit" USING btree ("component_id","entered_at_utc");--> statement-breakpoint
CREATE INDEX "idx_component_date" ON "running_hours_audit" USING btree ("component_id","date_updated_local");--> statement-breakpoint
CREATE INDEX "idx_renewal_reset" ON "running_hours_audit" USING btree ("is_renewal_reset","vessel_id");--> statement-breakpoint
CREATE INDEX "idx_sfi_component_code" ON "sfi_details" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_spare_component_link_spare" ON "spare_component_links" USING btree ("spare_id");--> statement-breakpoint
CREATE INDEX "idx_spare_component_link_component" ON "spare_component_links" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_spare_component_link_vessel" ON "spare_component_links" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_spare_location_stock_spare" ON "spare_location_stock" USING btree ("spare_id");--> statement-breakpoint
CREATE INDEX "idx_spare_location_stock_location" ON "spare_location_stock" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "idx_spare_location_stock_vessel" ON "spare_location_stock" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_spare_component" ON "spares" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_spare_vessel" ON "spares" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_spare_code" ON "spares" USING btree ("vessel_id","component_spare_code");--> statement-breakpoint
CREATE INDEX "idx_spare_data_scope" ON "spares" USING btree ("data_scope");--> statement-breakpoint
CREATE INDEX "idx_spare_fleet_equipment" ON "spares" USING btree ("data_scope","fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_history_timestamp" ON "spares_history" USING btree ("timestamp_utc");--> statement-breakpoint
CREATE INDEX "idx_history_spare" ON "spares_history" USING btree ("spare_id");--> statement-breakpoint
CREATE INDEX "idx_history_event" ON "spares_history" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "idx_stores_vessel" ON "stores_items" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_stores_item_type" ON "stores_items" USING btree ("item_type");--> statement-breakpoint
CREATE INDEX "idx_stores_item_code" ON "stores_items" USING btree ("vessel_id","item_code");--> statement-breakpoint
CREATE INDEX "idx_stores_impa_code" ON "stores_items" USING btree ("impa_code");--> statement-breakpoint
CREATE INDEX "idx_stores_deleted" ON "stores_items" USING btree ("deleted");--> statement-breakpoint
CREATE INDEX "idx_vessel_section_date" ON "stores_ledger" USING btree ("vessel_id","section","date_local");--> statement-breakpoint
CREATE INDEX "idx_item_date" ON "stores_ledger" USING btree ("item_id","date_local");--> statement-breakpoint
CREATE INDEX "idx_surveys_vessel" ON "surveys" USING btree ("vessel");--> statement-breakpoint
CREATE INDEX "idx_surveys_type" ON "surveys" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_surveys_due" ON "surveys" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "idx_exec_details_wo" ON "work_order_execution_details" USING btree ("work_order_id");--> statement-breakpoint
CREATE INDEX "idx_exec_details_vessel" ON "work_order_execution_details" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_exec_details_date" ON "work_order_execution_details" USING btree ("executed_date");--> statement-breakpoint
CREATE INDEX "idx_exec_template" ON "work_order_executions" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "idx_exec_component" ON "work_order_executions" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_exec_vessel" ON "work_order_executions" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_exec_status" ON "work_order_executions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_exec_date_completed" ON "work_order_executions" USING btree ("date_completed");--> statement-breakpoint
CREATE INDEX "idx_wo_vessel" ON "work_orders" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_wo_status" ON "work_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_wo_due_date" ON "work_orders" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "idx_wo_component" ON "work_orders" USING btree ("component_code");--> statement-breakpoint
CREATE INDEX "idx_wo_template" ON "work_orders" USING btree ("template_code");--> statement-breakpoint
CREATE INDEX "idx_wo_data_scope" ON "work_orders" USING btree ("data_scope");--> statement-breakpoint
CREATE INDEX "idx_wo_fleet_equipment" ON "work_orders" USING btree ("data_scope","fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_wo_job_cycle_rh" ON "work_orders" USING btree ("job_id","cycle_due_rh_snapshot");--> statement-breakpoint
CREATE INDEX "idx_wo_job_cycle_date" ON "work_orders" USING btree ("job_id","cycle_due_date_snapshot");