CREATE TABLE "ship_certificates_labels_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ship_certificates_labels_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_type" text NOT NULL,
	"key" text NOT NULL,
	"label" text DEFAULT '' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ship_certificates_master" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ship_certificates_master_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sequence" integer NOT NULL,
	"master_id" text NOT NULL,
	"certificate_name" text NOT NULL,
	"category" text NOT NULL,
	"group" text NOT NULL,
	"requirement_ref" text,
	"applicable_to_company" boolean DEFAULT false NOT NULL,
	"certificate_label" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"company_id" text,
	"company_group" text,
	"company_sequence" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ship_certificates_master_master_id_unique" UNIQUE("master_id")
);
--> statement-breakpoint
CREATE TABLE "vessel_certificate_applicability" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_certificate_applicability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"vessel_name" text NOT NULL,
	"master_id" text NOT NULL,
	"is_applicable" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "closed_out_by_name" text;--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "closed_out_by_rank" text;--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "verified" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "date_verified" text;--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "verified_by_name" text;--> statement-breakpoint
ALTER TABLE "defects" ADD COLUMN "verified_by_office_position" text;--> statement-breakpoint
CREATE INDEX "idx_ship_cert_master_sequence" ON "ship_certificates_master" USING btree ("sequence");--> statement-breakpoint
CREATE INDEX "idx_ship_cert_master_category" ON "ship_certificates_master" USING btree ("category");--> statement-breakpoint
CREATE INDEX "idx_ship_cert_master_group" ON "ship_certificates_master" USING btree ("group");--> statement-breakpoint
CREATE INDEX "idx_vessel_cert_vessel_master" ON "vessel_certificate_applicability" USING btree ("vessel_id","master_id");--> statement-breakpoint
CREATE INDEX "idx_vessel_cert_vessel" ON "vessel_certificate_applicability" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_vessel_cert_master" ON "vessel_certificate_applicability" USING btree ("master_id");