CREATE TABLE "fleet_components" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_components_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_components_uuid" text DEFAULT gen_random_uuid(),
	"parent_fleet_equipment_code" text,
	"fleet_equipment_code" text NOT NULL,
	"fleet_equipment_name" text NOT NULL,
	"component_category" text,
	"maker_name" text,
	"maker_code" text,
	"model" text,
	"model_code" text,
	"location" text,
	"rating" text,
	"eqpt_system_dept" text,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "fleet_components_fleet_equipment_code_unique" UNIQUE("fleet_equipment_code")
);
--> statement-breakpoint
CREATE INDEX "idx_fleet_components_code" ON "fleet_components" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_components_parent" ON "fleet_components" USING btree ("parent_fleet_equipment_code");--> statement-breakpoint
CREATE INDEX "idx_fleet_components_uuid" ON "fleet_components" USING btree ("fleet_components_uuid");--> statement-breakpoint
CREATE INDEX "idx_fleet_components_maker" ON "fleet_components" USING btree ("maker_code");