CREATE TABLE IF NOT EXISTS "fleet_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_jobs_uuid" text DEFAULT gen_random_uuid(),
	"job_code" text NOT NULL,
	"fleet_equipment_code" text NOT NULL,
	"fleet_equipment_name" text NOT NULL,
	"wo_title" text NOT NULL,
	"maintenance_basis" text,
	"interval_value" text,
	"unit" text,
	"task_type" text NOT NULL,
	"assigned_to" text NOT NULL,
	"approver" text NOT NULL,
	"job_priority" text NOT NULL,
	"class_related" text NOT NULL,
	"brief_work_description" text NOT NULL,
	"department" text NOT NULL,
	"criticality" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"required_spare_parts" json DEFAULT '[]'::json,
	"required_tools" json DEFAULT '[]'::json,
	"ppe_requirements" text,
	"permit_requirements" text,
	"other_safety_requirements" text,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "fleet_jobs_job_code_unique" UNIQUE("job_code")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_fleet_jobs_code" ON "fleet_jobs" USING btree ("job_code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_fleet_jobs_equipment" ON "fleet_jobs" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_fleet_jobs_uuid" ON "fleet_jobs" USING btree ("fleet_jobs_uuid");