CREATE TABLE "report_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"report_type" text NOT NULL,
	"export_format" text NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	"generated_by" text,
	"item_count" integer DEFAULT 0 NOT NULL,
	"filters_applied" jsonb,
	"summary_data" jsonb NOT NULL,
	"items_data" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_report_snapshots_vessel" ON "report_snapshots" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_report_snapshots_type" ON "report_snapshots" USING btree ("report_type");--> statement-breakpoint
CREATE INDEX "idx_report_snapshots_date" ON "report_snapshots" USING btree ("generated_at");