ALTER TYPE "public"."user_role" ADD VALUE 'Sail Admin';--> statement-breakpoint
CREATE TABLE "adm_menumaster_ac" (
	"id" integer PRIMARY KEY NOT NULL,
	"muid" text NOT NULL,
	"name" text NOT NULL,
	"display_name" text NOT NULL,
	"route" text,
	"parent_menu" text,
	"is_active" boolean DEFAULT true,
	"sort_order" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "adm_menumaster_ac_muid_unique" UNIQUE("muid")
);
--> statement-breakpoint
CREATE TABLE "adm_role_menu_access" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "adm_role_menu_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role_ruid" text NOT NULL,
	"menu_muid" text NOT NULL,
	"can_view" boolean DEFAULT false,
	"can_create" boolean DEFAULT false,
	"can_edit" boolean DEFAULT false,
	"can_delete" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by_uuid" text,
	"updated_by_uuid" text,
	CONSTRAINT "adm_role_menu_access_role_ruid_menu_muid_unique" UNIQUE("role_ruid","menu_muid")
);
--> statement-breakpoint
CREATE TABLE "admn_role_master" (
	"id" integer PRIMARY KEY NOT NULL,
	"ruid" text NOT NULL,
	"assigned_role" text NOT NULL,
	"roletype" text NOT NULL,
	"orderby" integer,
	"is_active" boolean DEFAULT true,
	"sort_order" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "admn_role_master_ruid_unique" UNIQUE("ruid")
);
--> statement-breakpoint
CREATE TABLE "company_standard_grace_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_standard_grace_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"singleton_key" text DEFAULT 'ACTIVE' NOT NULL,
	"grace_method" text DEFAULT 'MONTH_END' NOT NULL,
	"grace_value" integer,
	"scope" text DEFAULT 'LAST_WEEK_OF_MONTH' NOT NULL,
	"fallback_grace_days" integer,
	"updated_by" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "company_standard_grace_settings_singleton_key_unique" UNIQUE("singleton_key")
);
--> statement-breakpoint
CREATE TABLE "fleet_classes" (
	"id" serial PRIMARY KEY NOT NULL,
	"fcuuid" text NOT NULL,
	"fleet_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "fleet_classes_fcuuid_unique" UNIQUE("fcuuid")
);
--> statement-breakpoint
CREATE TABLE "planner_dates" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"job_id" text NOT NULL,
	"component_id" text NOT NULL,
	"planned_date" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_planner_date_entry" UNIQUE("vessel_id","job_id","component_id")
);
--> statement-breakpoint
CREATE TABLE "superintendent_notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"work_order_id" text NOT NULL,
	"work_order_code" text,
	"job_title" text,
	"component_name" text,
	"vessel_name" text,
	"days_late" integer DEFAULT 0,
	"missed_cycles" integer DEFAULT 0,
	"backdating_days" integer DEFAULT 0,
	"approval_tier" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"acknowledged_at" timestamp,
	"is_acknowledged" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "work_order_anomalies" (
	"id" serial PRIMARY KEY NOT NULL,
	"work_order_id" text NOT NULL,
	"work_order_code" text,
	"component_code" text,
	"component_name" text,
	"job_title" text,
	"vessel_id" text,
	"anomaly_type" text NOT NULL,
	"severity" text NOT NULL,
	"detected_at" timestamp DEFAULT now() NOT NULL,
	"completion_date" text,
	"due_date" text,
	"days_late" integer DEFAULT 0,
	"missed_cycles" integer DEFAULT 0,
	"anomaly_details" json,
	"status" text DEFAULT 'PENDING_REVIEW' NOT NULL,
	"reviewed_by" text,
	"reviewed_at" timestamp,
	"justification" text,
	"is_resolved" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_alerts" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"report_id" integer,
	"alert_type" text NOT NULL,
	"severity" text NOT NULL,
	"message" text NOT NULL,
	"metric_value" numeric,
	"threshold_value" numeric,
	"acknowledged_at" timestamp,
	"acknowledged_by" text,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nauuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_bunker_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"voyage_no" text,
	"port" text NOT NULL,
	"bunkered_date" text NOT NULL,
	"fuel_type" text NOT NULL,
	"quantity_mt" numeric NOT NULL,
	"density" numeric,
	"sulphur_pct" numeric,
	"price_pmt" numeric,
	"total_cost" numeric,
	"supplier" text,
	"bdn_number" text,
	"sample_seal_number" text,
	"remarks" text,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nbruuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_cii_tracking" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"year" integer NOT NULL,
	"ytd_co2_mt" numeric,
	"ytd_distance_nm" numeric,
	"aer" numeric,
	"cii_rating" text,
	"previous_cii_rating" text,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nctuuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_fuel_rob" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"fuel_type" text NOT NULL,
	"current_rob" numeric DEFAULT '0' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_report_id" integer,
	"avg3_day" numeric,
	"avg7_day" numeric,
	"endurance_days" numeric,
	"endurance_nm" numeric,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nfruuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_noon_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"submitted_at" timestamp,
	"submitted_by" text,
	"draft_saved_at" timestamp,
	"report_date" text NOT NULL,
	"report_time" text,
	"voyage_no" text,
	"port_from" text,
	"port_to" text,
	"lat_degrees" numeric,
	"lat_minutes" numeric,
	"lat_direction" text,
	"lon_degrees" numeric,
	"lon_minutes" numeric,
	"lon_direction" text,
	"course" numeric,
	"speed" numeric,
	"distance_sailed" numeric,
	"next_port" text,
	"eta_next_port" timestamp,
	"distance_to_go" numeric,
	"wind_direction" text,
	"wind_force" integer,
	"sea_state" integer,
	"swell_height" numeric,
	"swell_direction" text,
	"visibility" text,
	"current_direction" text,
	"current_speed" numeric,
	"air_temperature" numeric,
	"sea_temperature" numeric,
	"me_load" numeric,
	"me_rpm" numeric,
	"me_hours" numeric,
	"ae_running_hours" numeric,
	"boiler_hours" numeric,
	"hfo_consumption" numeric,
	"lsmgo_consumption" numeric,
	"mgo_consumption" numeric,
	"vlsfo_consumption" numeric,
	"lpg_consumption" numeric,
	"hfo_rob" numeric,
	"lsmgo_rob" numeric,
	"mgo_rob" numeric,
	"vlsfo_rob" numeric,
	"lpg_rob" numeric,
	"lube_oil_consumption" numeric,
	"fresh_water_consumption" numeric,
	"fresh_water_produced" numeric,
	"co2_emissions" numeric,
	"sox_emissions" numeric,
	"nox_emissions" numeric,
	"eeoi" numeric,
	"cii_rating" text,
	"aer" numeric,
	"co2_hfo" numeric,
	"co2_lsmgo" numeric,
	"co2_mgo" numeric,
	"co2_vlsfo" numeric,
	"co2_lpg" numeric,
	"co2_total" numeric,
	"emission_override_notes" text,
	"draft_forward" numeric,
	"draft_aft" numeric,
	"trim" numeric,
	"condition" text,
	"cargo_quantity" numeric,
	"cargo_description" text,
	"remarks" text,
	"general_remarks" text,
	"machinery_remarks" text,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nruuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nr_voyage_legs" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" text NOT NULL,
	"voyage_no" text NOT NULL,
	"port_from" text,
	"port_to" text,
	"departure_date" text,
	"arrival_date" text,
	"status" text DEFAULT 'active' NOT NULL,
	"eeoi" numeric,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"nvluuid" text DEFAULT gen_random_uuid() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "fleet_job_vessel_mapping" DROP CONSTRAINT "unique_fleet_job_vessel_mapping";--> statement-breakpoint
ALTER TABLE "fleet_spare_vessel_mapping" DROP CONSTRAINT "unique_fleet_spare_vessel_mapping";--> statement-breakpoint
ALTER TABLE "spare_component_links" DROP CONSTRAINT "unique_spare_component_link";--> statement-breakpoint
ALTER TABLE "component_maintenance_history" ADD COLUMN "missed_cycles" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "component_maintenance_history" ADD COLUMN "original_due_date" text;--> statement-breakpoint
ALTER TABLE "component_maintenance_history" ADD COLUMN "is_skipped" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "component_maintenance_history" ADD COLUMN "skipped_cycle_date" text;--> statement-breakpoint
ALTER TABLE "component_maintenance_history" ADD COLUMN "source_work_order_id" text;--> statement-breakpoint
ALTER TABLE "fleets" ADD COLUMN "fuuid" text NOT NULL;--> statement-breakpoint
ALTER TABLE "running_hours_audit" ADD COLUMN "updated_by_uuid" text;--> statement-breakpoint
ALTER TABLE "vessels" ADD COLUMN "class_id" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "missed_cycles" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "original_due_date" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "skipped_cycles_justification" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "days_late" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "approval_tier" text DEFAULT 'standard';--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "superintendent_acknowledged" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "superintendent_acknowledged_at" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "superintendent_notified_at" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "ce_approval_remarks" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "approval_block_reason" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "completion_rh" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "completion_rh_validated" boolean;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "completion_rh_source" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "completion_rh_validation_details" jsonb;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "rh_justification" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "rh_justification_provided_by" text;--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "rh_justification_date" timestamp;--> statement-breakpoint
ALTER TABLE "adm_role_menu_access" ADD CONSTRAINT "adm_role_menu_access_role_ruid_admn_role_master_ruid_fk" FOREIGN KEY ("role_ruid") REFERENCES "public"."admn_role_master"("ruid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adm_role_menu_access" ADD CONSTRAINT "adm_role_menu_access_menu_muid_adm_menumaster_ac_muid_fk" FOREIGN KEY ("menu_muid") REFERENCES "public"."adm_menumaster_ac"("muid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_fleet_classes_fleet_id" ON "fleet_classes" USING btree ("fleet_id");--> statement-breakpoint
CREATE INDEX "idx_nr_alerts_vessel" ON "nr_alerts" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_nr_alerts_type_vessel" ON "nr_alerts" USING btree ("vessel_id","alert_type");--> statement-breakpoint
CREATE INDEX "idx_nr_bunker_vessel" ON "nr_bunker_records" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_nr_bunker_vessel_date" ON "nr_bunker_records" USING btree ("vessel_id","bunkered_date");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_nr_cii_vessel_year" ON "nr_cii_tracking" USING btree ("vessel_id","year");--> statement-breakpoint
CREATE INDEX "idx_nr_rob_vessel_fuel" ON "nr_fuel_rob" USING btree ("vessel_id","fuel_type");--> statement-breakpoint
CREATE INDEX "idx_nr_reports_vessel_date" ON "nr_noon_reports" USING btree ("vessel_id","report_date");--> statement-breakpoint
CREATE INDEX "idx_nr_reports_status" ON "nr_noon_reports" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_nr_voyage_vessel" ON "nr_voyage_legs" USING btree ("vessel_id");--> statement-breakpoint
ALTER TABLE "fleet_job_vessel_mapping" ADD CONSTRAINT "unique_fleet_job_vessel_mapping" UNIQUE("fleet_equipment_code","job_code","vessel_code","job_id");--> statement-breakpoint
ALTER TABLE "fleet_spare_vessel_mapping" ADD CONSTRAINT "unique_fleet_spare_vessel_mapping" UNIQUE("fleet_equipment_code","part_code","vessel_code","spare_id");--> statement-breakpoint
ALTER TABLE "fleets" ADD CONSTRAINT "fleets_fuuid_unique" UNIQUE("fuuid");--> statement-breakpoint
ALTER TABLE "spare_component_links" ADD CONSTRAINT "unique_spare_component_link" UNIQUE("spare_id","component_id","vessel_id");