ALTER TABLE "company_standard_grace_settings" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "company_standard_grace_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "company_standard_grace_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "company_standard_grace_settings" ALTER COLUMN "fallback_grace_days" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "company_standard_grace_settings" ALTER COLUMN "created_at" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "company_standard_grace_settings" ALTER COLUMN "updated_at" SET DATA TYPE timestamp;