CREATE TABLE "adm_available_ranks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "adm_available_ranks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ar_uuid" text DEFAULT gen_random_uuid()::text,
	"name" text NOT NULL,
	"category" text,
	"rank_id" text NOT NULL,
	"label" text,
	"applicable_to_company" boolean DEFAULT true,
	"is_system_rank" boolean DEFAULT true,
	"sort_order" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "adm_available_ranks_ar_uuid_unique" UNIQUE("ar_uuid"),
	CONSTRAINT "adm_available_ranks_rank_id_unique" UNIQUE("rank_id")
);
--> statement-breakpoint
CREATE TABLE "adm_vessel_org_chart" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "adm_vessel_org_chart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"oc_uuid" text DEFAULT gen_random_uuid()::text,
	"rank" text,
	"rank_id" text NOT NULL,
	"parent_rank_id" text,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "adm_vessel_org_chart_oc_uuid_unique" UNIQUE("oc_uuid")
);
--> statement-breakpoint
ALTER TABLE "adm_vessel_org_chart" ADD CONSTRAINT "adm_vessel_org_chart_rank_id_adm_available_ranks_rank_id_fk" FOREIGN KEY ("rank_id") REFERENCES "public"."adm_available_ranks"("rank_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "adm_vessel_org_chart" ADD CONSTRAINT "adm_vessel_org_chart_parent_rank_id_adm_available_ranks_rank_id_fk" FOREIGN KEY ("parent_rank_id") REFERENCES "public"."adm_available_ranks"("rank_id") ON DELETE no action ON UPDATE no action;