CREATE TABLE "alert_acknowledgements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_acknowledgements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"aauuid" text NOT NULL,
	"event_uuid" text NOT NULL,
	"user_id" text NOT NULL,
	"user_role" text NOT NULL,
	"comments" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "alert_acknowledgements_aauuid_unique" UNIQUE("aauuid")
);
--> statement-breakpoint
CREATE TABLE "monthly_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monthly_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"snapshot_month" text NOT NULL,
	"snapshot_type" text NOT NULL,
	"snapshot_timestamp" timestamp NOT NULL,
	"category" text NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	"work_order_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_monthly_snapshot" UNIQUE("vessel_id","snapshot_month","snapshot_type","category")
);
--> statement-breakpoint
ALTER TABLE "adm_available_ranks" ADD COLUMN "view_mode" text;--> statement-breakpoint
ALTER TABLE "adm_vessel_org_chart" ADD COLUMN "rank_view" text;--> statement-breakpoint
ALTER TABLE "spares" ADD COLUMN "is_rotation_item" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "alert_acknowledgements" ADD CONSTRAINT "alert_acknowledgements_event_uuid_alert_events_aeuuid_fk" FOREIGN KEY ("event_uuid") REFERENCES "public"."alert_events"("aeuuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ADD CONSTRAINT "monthly_snapshots_vessel_id_vessels_vuuid_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vuuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_monthly_snap_vessel_month" ON "monthly_snapshots" USING btree ("vessel_id","snapshot_month");--> statement-breakpoint
CREATE INDEX "idx_monthly_snap_type" ON "monthly_snapshots" USING btree ("snapshot_type");