CREATE TABLE IF NOT EXISTS "monthly_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monthly_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"snapshot_month" text NOT NULL,
	"snapshot_type" text NOT NULL,
	"snapshot_timestamp" timestamp NOT NULL,
	"category" text NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	"work_order_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_monthly_snapshot" UNIQUE("vessel_id","snapshot_month","snapshot_type","category")
);
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "monthly_snapshots" ADD CONSTRAINT "monthly_snapshots_vessel_id_vessels_vuuid_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vuuid") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_monthly_snap_vessel_month" ON "monthly_snapshots" USING btree ("vessel_id","snapshot_month");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_monthly_snap_type" ON "monthly_snapshots" USING btree ("snapshot_type");
