CREATE TABLE "master_list_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "master_list_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mltuuid" text NOT NULL,
	"list_type_key" text NOT NULL,
	"label" text NOT NULL,
	"section" text NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "master_list_types_mltuuid_unique" UNIQUE("mltuuid"),
	CONSTRAINT "master_list_types_list_type_key_unique" UNIQUE("list_type_key")
);
--> statement-breakpoint
CREATE INDEX "idx_mlt_section" ON "master_list_types" USING btree ("section");--> statement-breakpoint
CREATE INDEX "idx_mlt_active" ON "master_list_types" USING btree ("is_active");