CREATE TABLE "master_list_types" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "master_list_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "mltuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
        "list_type_key" text NOT NULL,
        "label" text NOT NULL,
        "section" text NOT NULL,
        "is_system" boolean DEFAULT false NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "display_order" integer DEFAULT 0 NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        "created_by_uuid" text,
        "updated_by_uuid" text,
        "is_deleted" boolean DEFAULT false NOT NULL,
        "is_sync" boolean DEFAULT false NOT NULL,
        CONSTRAINT "master_list_types_mltuuid_unique" UNIQUE("mltuuid"),
        CONSTRAINT "master_list_types_list_type_key_unique" UNIQUE("list_type_key")
);
--> statement-breakpoint
CREATE TABLE "vessel_department_config" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_department_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "vessel_id" text NOT NULL,
        "department" text NOT NULL,
        "is_enabled" boolean DEFAULT true NOT NULL,
        "sort_order" integer DEFAULT 0 NOT NULL,
        "created_at" timestamp with time zone DEFAULT now(),
        "updated_at" timestamp with time zone DEFAULT now(),
        CONSTRAINT "vessel_dept_config_unique" UNIQUE("vessel_id","department")
);
--> statement-breakpoint
CREATE TABLE "vessel_org_chart_nodes" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_org_chart_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "node_uuid" text DEFAULT gen_random_uuid()::text NOT NULL,
        "vessel_id" text NOT NULL,
        "rank_id" text NOT NULL,
        "node_label" text,
        "department" text,
        "parent_node_uuid" text,
        "is_hod" boolean DEFAULT false,
        "is_assigned" boolean DEFAULT false,
        "view_mode" text,
        "sort_order" integer DEFAULT 0,
        "node_layer" text DEFAULT 'department' NOT NULL,
        "created_at" timestamp with time zone DEFAULT now(),
        "updated_at" timestamp with time zone DEFAULT now(),
        "created_by_uuid" text,
        "updated_by_uuid" text,
        "is_deleted" boolean DEFAULT false,
        CONSTRAINT "vessel_org_chart_nodes_node_uuid_unique" UNIQUE("node_uuid")
);
--> statement-breakpoint
ALTER TABLE "jobs" ADD COLUMN "assigned_to_rank_id" text;--> statement-breakpoint
UPDATE "jobs" SET "assigned_to_rank_id" = r."rank_id"
FROM "adm_available_ranks" r
WHERE LOWER(TRIM("jobs"."assigned_to")) = LOWER(TRIM(r."name"))
AND "jobs"."assigned_to" IS NOT NULL
AND "jobs"."assigned_to_rank_id" IS NULL;--> statement-breakpoint
ALTER TABLE "vessel_department_config" ADD CONSTRAINT "vessel_department_config_vessel_id_vessels_vuuid_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vuuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vessel_org_chart_nodes" ADD CONSTRAINT "vessel_org_chart_nodes_vessel_id_vessels_vuuid_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vuuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vessel_org_chart_nodes" ADD CONSTRAINT "vessel_org_chart_nodes_rank_id_adm_available_ranks_rank_id_fk" FOREIGN KEY ("rank_id") REFERENCES "public"."adm_available_ranks"("rank_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_mlt_section" ON "master_list_types" USING btree ("section");--> statement-breakpoint
CREATE INDEX "idx_mlt_active" ON "master_list_types" USING btree ("is_active");