CREATE TABLE "sync_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ssuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"setting_key" text NOT NULL,
	"setting_value" text,
	"setting_type" text DEFAULT 'text',
	"description" text,
	"is_editable" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_settings_ssuuid_unique" UNIQUE("ssuuid"),
	CONSTRAINT "sync_settings_setting_key_unique" UNIQUE("setting_key")
);
