CREATE TABLE "approval_workflow_config" (
	"id" serial PRIMARY KEY NOT NULL,
	"awcuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"module_id" text NOT NULL,
	"sub_module_id" text NOT NULL,
	"function_id" text NOT NULL,
	"variable_name" text NOT NULL,
	"level1_enabled" boolean DEFAULT false NOT NULL,
	"level2_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "approval_workflow_config_awcuuid_unique" UNIQUE("awcuuid"),
	CONSTRAINT "approval_workflow_config_function_id_variable_name_unique" UNIQUE("function_id","variable_name")
);
--> statement-breakpoint
CREATE TABLE "moc_approvers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "moc_approvers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mauuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"name" text,
	"user_id" text,
	"approver_level" text,
	"email_id" text,
	"is_active" integer DEFAULT 1,
	"modulename" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "moc_approvers_mauuid_unique" UNIQUE("mauuid")
);
--> statement-breakpoint
ALTER TABLE "work_orders" ADD COLUMN "rh_synced_at" timestamp;