CREATE TABLE IF NOT EXISTS "view_modes_master" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "view_modes_master_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vmuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"code" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "view_modes_master_vmuuid_unique" UNIQUE("vmuuid"),
	CONSTRAINT "view_modes_master_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_view_mode_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_view_mode_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rvmuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"role_ruid" text NOT NULL,
	"view_mode_code" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0,
	CONSTRAINT "role_view_mode_mapping_rvmuuid_unique" UNIQUE("rvmuuid"),
	CONSTRAINT "role_view_mode_mapping_role_ruid_unique" UNIQUE("role_ruid")
);
