CREATE TABLE "defect_approval_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_approval_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dasuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"singleton_key" text DEFAULT 'default' NOT NULL,
	"long_extension_days" integer DEFAULT 90 NOT NULL,
	"show_rejected_closures_on_report" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "defect_approval_settings_dasuuid_unique" UNIQUE("dasuuid"),
	CONSTRAINT "defect_approval_settings_singleton_key_unique" UNIQUE("singleton_key")
);
--> statement-breakpoint
INSERT INTO "defect_approval_settings" (
	"singleton_key",
	"long_extension_days",
	"show_rejected_closures_on_report"
) VALUES ('default', 90, false)
ON CONFLICT ("singleton_key") DO NOTHING;