CREATE TABLE "defect_closure_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "defect_closure_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dchuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"defect_duuid" text NOT NULL,
	"vessel_id" text NOT NULL,
	"attempt_number" integer NOT NULL,
	"prior_status" text NOT NULL,
	"closed_out_by_name" text,
	"closed_out_by_rank" text,
	"confirm_completed" boolean DEFAULT false NOT NULL,
	"date_completed" text,
	"closed_by_name" text,
	"closed_by_rank" text,
	"closure_comment" text,
	"closed_by" text,
	"closed_on" text,
	"closure_files" text[],
	"rejected_by_user_uuid" text NOT NULL,
	"rejected_by_name" text NOT NULL,
	"rejected_by_position" text NOT NULL,
	"rejected_at" timestamp DEFAULT now() NOT NULL,
	"rejection_reason" text NOT NULL,
	"approval_request_uuid" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "defect_closure_history_dchuuid_unique" UNIQUE("dchuuid"),
	CONSTRAINT "defect_closure_history_attempt_positive" CHECK ("defect_closure_history"."attempt_number" > 0)
);
--> statement-breakpoint
ALTER TABLE "defect_closure_history" ADD CONSTRAINT "defect_closure_history_defect_duuid_defects_duuid_fk" FOREIGN KEY ("defect_duuid") REFERENCES "public"."defects"("duuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "defect_closure_history" ADD CONSTRAINT "defect_closure_history_vessel_id_vessels_vuuid_fk" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vuuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_defect_closure_history_defect" ON "defect_closure_history" USING btree ("defect_duuid");--> statement-breakpoint
CREATE INDEX "idx_defect_closure_history_vessel" ON "defect_closure_history" USING btree ("vessel_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_defect_closure_history_attempt" ON "defect_closure_history" USING btree ("defect_duuid","attempt_number");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_defect_closure_history_request" ON "defect_closure_history" USING btree ("approval_request_uuid");--> statement-breakpoint
CREATE OR REPLACE FUNCTION prevent_defect_closure_history_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'defect_closure_history is immutable — rows cannot be updated or deleted';
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER prevent_defect_closure_history_mutation
  BEFORE UPDATE OR DELETE ON "defect_closure_history"
  FOR EACH ROW EXECUTE FUNCTION prevent_defect_closure_history_mutation();