CREATE TABLE IF NOT EXISTS "report_snapshots" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "vessel_id" text NOT NULL,
  "report_type" text NOT NULL,
  "export_format" text NOT NULL,
  "generated_at" timestamp DEFAULT now() NOT NULL,
  "generated_by" text,
  "item_count" integer DEFAULT 0 NOT NULL,
  "filters_applied" jsonb,
  "summary_data" jsonb NOT NULL,
  "items_data" jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_report_snapshots_vessel" ON "report_snapshots" ("vessel_id");
CREATE INDEX IF NOT EXISTS "idx_report_snapshots_type" ON "report_snapshots" ("report_type");
CREATE INDEX IF NOT EXISTS "idx_report_snapshots_date" ON "report_snapshots" ("generated_at");
