CREATE TABLE IF NOT EXISTS vessel_org_chart_nodes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  node_uuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  vessel_id TEXT NOT NULL REFERENCES vessels(vuuid),
  rank_id TEXT NOT NULL,
  node_label TEXT,
  department TEXT,
  parent_node_uuid TEXT,
  is_hod BOOLEAN DEFAULT FALSE,
  is_assigned BOOLEAN DEFAULT FALSE,
  view_mode TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_vocn_vessel_id ON vessel_org_chart_nodes(vessel_id);
CREATE INDEX IF NOT EXISTS idx_vocn_rank_id ON vessel_org_chart_nodes(rank_id);
CREATE INDEX IF NOT EXISTS idx_vocn_parent ON vessel_org_chart_nodes(parent_node_uuid);
CREATE INDEX IF NOT EXISTS idx_vocn_department ON vessel_org_chart_nodes(vessel_id, department);
