-- Migration 123: Audit Phase 4 — Configurable retention + disposition lifecycle
-- Records-management model: the configured period is a MINIMUM keep-time, not an auto-delete
-- timer. Business/audit records are NEVER auto-deleted. Disposal is a human, logged, REVERSIBLE
-- soft-dispose (mark disposed_at, keep the row). Permanent physical deletion is manual-only and
-- OUT OF SCOPE here. Additive only: new table + nullable columns; existing rows untouched.

-- 1) Retention settings — one row per record category, UI-managed, seeded with the committed
--    Record Retention Procedure §6 defaults. is_protected categories enforce a hard floor (min_*).
CREATE TABLE IF NOT EXISTS retention_settings (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category        text NOT NULL UNIQUE,
  label           text NOT NULL,
  retention_value integer NOT NULL DEFAULT 0,
  retention_unit  text NOT NULL DEFAULT 'years',   -- 'days' | 'months' | 'years' | 'forever'
  enabled         boolean NOT NULL DEFAULT true,
  is_protected    boolean NOT NULL DEFAULT true,    -- true = business/audit (hard floor, no auto-delete)
  min_value       integer NOT NULL DEFAULT 0,       -- committed minimum (floor) in min_unit
  min_unit        text NOT NULL DEFAULT 'years',
  description     text,
  updated_at      timestamp NOT NULL DEFAULT now(),
  updated_by_uuid text
);

-- Seed committed defaults (idempotent — re-run inserts zero rows).
INSERT INTO retention_settings (category, label, retention_value, retention_unit, enabled, is_protected, min_value, min_unit, description)
SELECT v.category, v.label, v.retention_value, v.retention_unit, v.enabled, v.is_protected, v.min_value, v.min_unit, v.description
FROM (VALUES
  ('maintenance',           'Maintenance Records',   5, 'years',   true,  true,  5, 'years',   'Work-order maintenance audit + component maintenance history. Minimum keep-time; no auto-delete.'),
  ('approval',              'Approval Records',      5, 'years',   true,  true,  5, 'years',   'Work-order postponement approvals + approval actions. Minimum keep-time; no auto-delete.'),
  ('audit_general',         'Audit Logs',            2, 'years',   true,  true,  2, 'years',   'General audit logs incl. component-register audit. Minimum keep-time; no auto-delete.'),
  ('user_access',           'User Access Logs',     12, 'months',  true,  true, 12, 'months',  'Role-permission, rank and retention-setting changes. Minimum keep-time; no auto-delete.'),
  ('running_hours_history', 'Running Hours History', 0, 'forever', false, true,  0, 'forever', 'Life of equipment — never disposed.'),
  ('sync_logs',             'Sync Logs',            12, 'months',  true,  false, 0, 'days',    'Sync-scratch (field log, batches, file queue, conflicts). The ONLY category that auto-prunes, honoring synced/resolved/completed safety predicates.')
) AS v(category, label, retention_value, retention_unit, enabled, is_protected, min_value, min_unit, description)
WHERE NOT EXISTS (SELECT 1 FROM retention_settings r WHERE r.category = v.category);

-- 2) Disposition columns (soft-dispose) on the business/audit tables. Additive, nullable.
--    A NULL disposed_at = active; a set disposed_at = marked disposed (recoverable via Revert).
ALTER TABLE audit_log                     ADD COLUMN IF NOT EXISTS disposed_at timestamp;
ALTER TABLE audit_log                     ADD COLUMN IF NOT EXISTS disposed_by_uuid text;
ALTER TABLE component_maintenance_history ADD COLUMN IF NOT EXISTS disposed_at timestamp;
ALTER TABLE component_maintenance_history ADD COLUMN IF NOT EXISTS disposed_by_uuid text;
ALTER TABLE work_order_postponements      ADD COLUMN IF NOT EXISTS disposed_at timestamp;
ALTER TABLE work_order_postponements      ADD COLUMN IF NOT EXISTS disposed_by_uuid text;
