-- Migration 122: Change Request Approval Workflow Engine
-- Creates change_request_approval intermediary table (one row per required
-- approval level per change request) and adds approval_workflow_snapshot
-- column to change_request.
-- All statements are idempotent.

-- ── New table: change_request_approval ────────────────────────────────────
CREATE TABLE IF NOT EXISTS change_request_approval (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crauuid               TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  change_request_id     INTEGER NOT NULL REFERENCES change_request(id),
  change_request_uuid   TEXT NOT NULL,
  approval_level        TEXT NOT NULL,   -- 'Level 1' | 'Level 2'
  status                TEXT NOT NULL DEFAULT 'Pending',  -- 'Pending' | 'Approved' | 'Rejected'
  action_by_user_id     TEXT,            -- NULL until someone acts
  action_at             TIMESTAMPTZ,
  remarks               TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_uuid       TEXT,
  updated_by_uuid       TEXT,
  is_deleted            BOOLEAN NOT NULL DEFAULT false,
  is_sync               BOOLEAN NOT NULL DEFAULT false
);

-- ── New column on change_request: approval_workflow_snapshot ──────────────
-- Freezes the Level1/Level2 config at submission time so later admin changes
-- do not affect in-progress requests.
ALTER TABLE change_request
  ADD COLUMN IF NOT EXISTS approval_workflow_snapshot JSONB
  DEFAULT '{"level1Enabled": false, "level2Enabled": false, "equipmentClassification": "unknown"}'::jsonb;
