-- 124: WO Postponement multi-level approval workflow
-- Adds approval_workflow_snapshot column to work_order_postponements and
-- creates wo_postponement_approvals table for level-gated approval steps.

DO $$ BEGIN
  ALTER TABLE work_order_postponements ADD COLUMN approval_workflow_snapshot jsonb;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS wo_postponement_approvals (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  wpauuid text NOT NULL DEFAULT gen_random_uuid()::text,
  postponement_id text NOT NULL REFERENCES work_order_postponements(id),
  work_order_id text NOT NULL,
  approval_level text NOT NULL,
  status text NOT NULL DEFAULT 'Pending',
  action_by_user_id text,
  action_at timestamptz,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by_uuid text,
  updated_by_uuid text,
  is_deleted boolean NOT NULL DEFAULT false,
  is_sync boolean NOT NULL DEFAULT false
);
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS wo_postponement_approvals_wpauuid_key ON wo_postponement_approvals (wpauuid);
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_wpa_postponement_id ON wo_postponement_approvals (postponement_id);
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS idx_wpa_work_order_id ON wo_postponement_approvals (work_order_id);
