-- 137: Company approval-policy settings (singleton, shore-configured, synced shore→ship)
--
-- Holds the Superintendent-lock toggle for the Layer-5 approval-tier system.
-- superintendent_lock_enabled = TRUE (default, seeded) keeps today's behaviour
-- byte-identical: WOs with 3+ missed cycles / 21+ days late / 7+ days backdating
-- are LOCKED pending Superintendent acknowledgment. FALSE downgrades that tier to
-- notify-only: approval allowed, Superintendent notification still fires, HOD
-- remarks (min 20 chars) still mandatory. Enforcement reads this LIVE, so flipping
-- OFF unlocks already-locked WOs immediately — no data migration.
--
-- Mirrors company_standard_grace_settings: integer identity PK + singleton_key
-- UNIQUE 'ACTIVE' (the sync identity column), synced ONE_WAY_SHORE_TO_SHIP via
-- updated_at full-row snapshots. Idempotent: re-run inserts zero rows.

-- is_deleted is REQUIRED even for a singleton: the provisioning exporter and
-- one-way sync filter every synced table with COALESCE(is_deleted,false)=false —
-- without the column the bundle export throws 42703 and generation fails.
CREATE TABLE IF NOT EXISTS company_approval_settings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  singleton_key TEXT NOT NULL UNIQUE DEFAULT 'ACTIVE',
  superintendent_lock_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  is_deleted BOOLEAN DEFAULT FALSE
);

-- Drift guard (idempotent): covers any DB where the table pre-exists without the column.
ALTER TABLE company_approval_settings ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

INSERT INTO company_approval_settings (singleton_key, superintendent_lock_enabled)
SELECT 'ACTIVE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM company_approval_settings WHERE singleton_key = 'ACTIVE');
