-- Migration 142: durable record of LOST field logs (Phase-0 un-swallow, SYNC-HARDENING-PLAN §9.4).
--
-- ROOT CAUSE CLASS (4th, Frontier Venture "52"): every work_orders write site commits the row
-- FIRST and then calls logFieldChanges separately, wrapped in try/catch{console.error} (20 sites).
-- Any logger failure (notably the deliberate instance-id-resolution throw during MT
-- registration/restart churn) silently loses the sync log while the business row commits —
-- the change then NEVER syncs and nothing records that it was lost.
--
-- This table is that record: one row per lost log event, written best-effort by the field
-- logger itself. Recovery tooling reads unresolved rows and regenerates the missing field
-- logs via the full-row-diff script (plan §3.2), then marks them resolved.
--
-- LOCAL BOOKKEEPING ONLY: deliberately NOT in shared/syncConfig.ts (never synced) and never
-- exported by provisioning (exporter walks syncConfig tables only). No is_deleted/uuid needed.
-- Idempotent: IF NOT EXISTS throughout; second run is a clean no-op.
CREATE TABLE IF NOT EXISTS sync_field_log_failures (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  table_name text NOT NULL,
  row_uuid text NOT NULL,
  vessel_id text,
  failed_fields integer NOT NULL DEFAULT 0,
  error text,
  occurred_at timestamptz NOT NULL DEFAULT NOW(),
  resolved boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_sflf_unresolved ON sync_field_log_failures (resolved, occurred_at);
CREATE INDEX IF NOT EXISTS idx_sflf_row ON sync_field_log_failures (table_name, row_uuid);
