-- 152: Rotational Items Tracking — data foundation
--
-- Components that are physically swapped between equipment positions (e.g. fuel
-- injectors) keep their own Running Hour history under a unique Stamp number.
--
-- components.rotational_item — flag, office-managed, flows shore→ship via normal
--   one-way component sync.
-- components.current_stamp   — MUTABLE POINTER to the currently-installed item;
--   rewritten on every swap. Permanent stamp identity lives ONLY in
--   rotational_items.stamp. Ship-side swaps sync via the rotation event tables
--   (Task: replacement flow), NOT via the components row.
--
-- rotational_items — BOTH_EDITABLE master registry of physical items:
--   * riuuid: sync identity (uuid convention).
--   * component_id: stores components.cuuid (schema-wide convention); populated
--     ONLY while status='Installed'.
--   * component_code / component_name: denormalized HISTORICAL SNAPSHOTS written
--     during install/swap ("where was this item last fitted") — intentionally NOT
--     updated on component renames.
--   * status: Installed | Spare | In Store | Retired.
--   * vessel_id is TEXT referencing vessels(vuuid) — codebase convention.
--
-- DEPLOYMENT ORDER: shore FIRST, ships after. Old ships never send rotational
-- rows; the one-way applier's unknown-column guard (added alongside this
-- migration) keeps shore→ship component sync working during the upgrade window.
--
-- Idempotent: safe to re-run (IF NOT EXISTS everywhere).

ALTER TABLE components ADD COLUMN IF NOT EXISTS rotational_item BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE components ADD COLUMN IF NOT EXISTS current_stamp TEXT;

CREATE TABLE IF NOT EXISTS rotational_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  riuuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  vessel_id TEXT NOT NULL REFERENCES vessels(vuuid),
  stamp TEXT NOT NULL,
  component_id TEXT,
  component_code TEXT,
  component_name TEXT,
  current_rh NUMERIC(10,2) NOT NULL DEFAULT 0,
  rh_last_updated TEXT,
  status TEXT NOT NULL DEFAULT 'Spare',
  -- standard audit/sync columns (migration 052 convention)
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_sync BOOLEAN DEFAULT FALSE,
  sort_order INTEGER
);

-- Stamp unique per vessel among non-deleted items (retired/deleted stamps can be reissued)
CREATE UNIQUE INDEX IF NOT EXISTS uq_rotational_items_vessel_stamp
  ON rotational_items (vessel_id, stamp) WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_rotational_items_vessel ON rotational_items (vessel_id);
CREATE INDEX IF NOT EXISTS idx_rotational_items_status ON rotational_items (vessel_id, status);
CREATE INDEX IF NOT EXISTS idx_rotational_items_component ON rotational_items (component_id) WHERE is_deleted = FALSE;
