-- 152: shipskart_catalogue_links — push-state ledger for the Stage 3 catalogue push
-- (docs/SHIPSKART-CATALOGUE-STAGE3-PLAN.md §4). Same pattern as the mig-149 Shipskart
-- link tables: NO_SYNC by omission (not in shared/syncConfig.ts, not in shared/schema.ts),
-- shore-only bookkeeping, raw-SQL repository.
--
-- One row per pushed entity. entity_type:
--   'category'  — local_key = category code (SFI code / STORES-slug); vessel_id NULL
--                 (categories are tenant-level on their side)
--   'product'   — local_key = component cuuid; vessel_id set (product masters are
--                 vessel-prefixed per plan §2.3)
--   'sku'       — local_key = spare suuid / stores item stuuid; vessel_id set
--   'catalogue' — local_key = same as sku (the vessel-catalogue add step); vessel_id set
--
-- push_status: pending | pushed | failed. A duplicate answer from their side is mapped
-- to 'pushed' (their catalogue is ours alone). remote_id nullable — SKUs need no id
-- downstream; categories/products get theirs resolved via their get-all endpoints.
--
-- Idempotent: IF NOT EXISTS everywhere; second run is a clean no-op.

CREATE TABLE IF NOT EXISTS shipskart_catalogue_links (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type   text NOT NULL,
  local_key     text NOT NULL,
  vessel_id     text,
  remote_code   text,
  remote_id     text,
  push_status   text NOT NULL DEFAULT 'pending',
  last_error    text,
  pushed_at     timestamp,
  created_at    timestamp NOT NULL DEFAULT now(),
  updated_at    timestamp NOT NULL DEFAULT now()
);

-- UNIQUE over (entity_type, local_key, vessel_id) with NULL vessel_id normalised:
-- a partial pair of unique indexes, since NULLs never collide in a plain UNIQUE.
CREATE UNIQUE INDEX IF NOT EXISTS uq_skcl_entity_key_vessel
  ON shipskart_catalogue_links (entity_type, local_key, vessel_id)
  WHERE vessel_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_skcl_entity_key_novessel
  ON shipskart_catalogue_links (entity_type, local_key)
  WHERE vessel_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_skcl_status ON shipskart_catalogue_links (push_status);
CREATE INDEX IF NOT EXISTS idx_skcl_vessel ON shipskart_catalogue_links (vessel_id);
