-- 153: Rotational Items — rotation history (replacement flow)
--
-- Insert-only immutable event log of physical swaps AND the sync carrier of the
-- swap. components is ONE_WAY_SHORE_TO_SHIP, so a ship-side swap's direct write
-- to components.current_stamp/RH never syncs ship→shore by itself: the
-- BOTH_EDITABLE rotation_history row travels instead, and derived-update hooks
-- in the sync appliers re-apply the stamp + RH baseline onto the receiving
-- side's component row (idempotent by rhruuid; latest-rotation-wins by
-- rotation_date).
--
-- Exact pattern of component_maintenance_history: UPDATE-blocking trigger makes
-- the table immutable; the SYNC_CONFIG immutable flag makes the field-log
-- appliers ACK re-delivered rows instead of issuing the forbidden UPDATE.
--
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS rotation_history (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  rhruuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  vessel_id TEXT NOT NULL REFERENCES vessels(vuuid),
  component_id TEXT NOT NULL,          -- components.cuuid of the position swapped
  component_code TEXT,                 -- historical snapshot at swap time
  component_name TEXT,                 -- historical snapshot at swap time
  out_riuuid TEXT,                     -- outgoing rotational_items.riuuid (NULL: position was empty)
  out_stamp TEXT,
  out_rh NUMERIC(10,2),                -- RH stored against the outgoing stamp at removal
  in_riuuid TEXT NOT NULL,             -- incoming rotational_items.riuuid
  in_stamp TEXT NOT NULL,
  in_rh NUMERIC(10,2) NOT NULL,        -- incoming item's stored RH — the component's new baseline
  rotation_date TIMESTAMP NOT NULL DEFAULT NOW(),
  user_id TEXT,
  actor_label TEXT,
  notes TEXT,
  -- standard audit/sync columns (migration 052 convention)
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_sync BOOLEAN DEFAULT FALSE,
  sort_order INTEGER
);

CREATE INDEX IF NOT EXISTS idx_rotation_history_vessel ON rotation_history (vessel_id);
CREATE INDEX IF NOT EXISTS idx_rotation_history_component ON rotation_history (component_id, rotation_date);

-- Immutability: rotation_history is an insert-only event log. UPDATEs are
-- hard-blocked at the DB level (same pattern as prevent_maintenance_history_update).
CREATE OR REPLACE FUNCTION prevent_rotation_history_update() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'rotation_history is immutable — rows cannot be updated';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS prevent_rotation_history_update ON rotation_history;
CREATE TRIGGER prevent_rotation_history_update
  BEFORE UPDATE ON rotation_history
  FOR EACH ROW EXECUTE FUNCTION prevent_rotation_history_update();
