-- 168: Approval Engine tables (Phase 1, design v3). Engine-owned, NO_SYNC, per tenant DB.
-- Idempotent: second run is a clean no-op. No hardcoded ids, no FKs/CHECKs on text columns
-- (values validated in the engine service layer). Prefix apprv_.

CREATE TABLE IF NOT EXISTS apprv_workflows (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  wfuuid TEXT NOT NULL UNIQUE,
  module_id TEXT NOT NULL,
  screen_id TEXT NOT NULL,
  action_id TEXT NOT NULL DEFAULT '',
  classification TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'simple',
  version INTEGER NOT NULL,
  status TEXT NOT NULL,
  label TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
-- one ACTIVE workflow per scope + classification
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_workflows_active
  ON apprv_workflows (module_id, screen_id, action_id, classification)
  WHERE status = 'active' AND is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_apprv_workflows_scope
  ON apprv_workflows (module_id, screen_id, action_id, classification, version);

CREATE TABLE IF NOT EXISTS apprv_workflow_nodes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workflow_wfuuid TEXT NOT NULL,
  node_key TEXT NOT NULL,
  type TEXT NOT NULL,
  ordinal INTEGER NOT NULL DEFAULT 0,
  quorum_rule TEXT,
  quorum_n INTEGER,
  label TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_nodes ON apprv_workflow_nodes (workflow_wfuuid, node_key);

CREATE TABLE IF NOT EXISTS apprv_node_edges (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workflow_wfuuid TEXT NOT NULL,
  from_key TEXT NOT NULL,
  to_key TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_edges ON apprv_node_edges (workflow_wfuuid, from_key, to_key);

CREATE TABLE IF NOT EXISTS apprv_node_slots (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workflow_wfuuid TEXT NOT NULL,
  node_key TEXT NOT NULL,
  slot_ordinal INTEGER NOT NULL,
  role_id TEXT NOT NULL,
  role_label TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_node_slots ON apprv_node_slots (workflow_wfuuid, node_key, slot_ordinal);

CREATE TABLE IF NOT EXISTS apprv_requests (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  requuid TEXT NOT NULL UNIQUE,
  module_id TEXT NOT NULL,
  screen_id TEXT NOT NULL,
  action_id TEXT NOT NULL DEFAULT '',
  classification TEXT NOT NULL,
  subject_ref TEXT NOT NULL,
  vessel_id TEXT,
  snapshot_json JSON NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  current_node_key TEXT,
  submitted_by TEXT NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finalized_at TIMESTAMPTZ,
  workflow_wfuuid TEXT NOT NULL,
  workflow_version INTEGER NOT NULL
);
-- one PENDING request per scope + subject
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_requests_pending
  ON apprv_requests (module_id, screen_id, action_id, subject_ref)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_apprv_requests_subject
  ON apprv_requests (module_id, screen_id, action_id, subject_ref);

CREATE TABLE IF NOT EXISTS apprv_request_slots (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  requuid TEXT NOT NULL,
  node_key TEXT NOT NULL,
  slot_ordinal INTEGER NOT NULL,
  role_id TEXT NOT NULL,
  role_label TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  resolved_approver_ids_json JSON,
  decided_by TEXT,
  decided_at TIMESTAMPTZ,
  remarks TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_request_slots ON apprv_request_slots (requuid, node_key, slot_ordinal);
CREATE INDEX IF NOT EXISTS idx_apprv_request_slots_status ON apprv_request_slots (status);

CREATE TABLE IF NOT EXISTS apprv_scope_settings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  module_id TEXT NOT NULL,
  screen_id TEXT NOT NULL,
  action_id TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_apprv_scope_settings ON apprv_scope_settings (module_id, screen_id, action_id);
