-- 169: Approval notifications (Sahil, 21-Aug-2026: in-app + email, both). Per-user inbox rows
-- written by the approval-engine notifier on shore (engine is shore-only; ships see subject
-- status via existing synced tables — these rows are NO_SYNC). Idempotent; no FKs/CHECKs.

CREATE TABLE IF NOT EXISTS approval_notifications (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  anuuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  user_uuid TEXT NOT NULL,
  requuid TEXT NOT NULL,
  module_id TEXT NOT NULL,
  screen_id TEXT NOT NULL,
  action_id TEXT NOT NULL DEFAULT '',
  subject_ref TEXT NOT NULL,
  vessel_id TEXT,
  kind TEXT NOT NULL,                    -- 'pending-approval' | 'approved' | 'returned'
  title TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  read_at TIMESTAMPTZ,
  email_status TEXT,                     -- 'sent' | 'skipped' | 'error' | NULL (no email attempted)
  email_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_apprv_notif_user_unread ON approval_notifications (user_uuid, read_at, created_at);
CREATE INDEX IF NOT EXISTS idx_apprv_notif_requuid ON approval_notifications (requuid);
