-- 178: Approval withdrawals (28-Sep-2026, Sahil E6 / Q8: "only the sender may cancel a pending request").
-- One row per withdrawal asked by the SENDER of a change request, WO (re-)postponement request or
-- defect target-date extension. BOTH_EDITABLE (ship ↔ shore) with DISJOINT writers:
--   * the sender's side INSERTS the row (ship or shore);
--   * the shore fills the outcome (withdrawn / too-late / refused) after cancelling the engine request —
--     so ship and shore never edit the same field (no sync conflict with the subject records).
-- Idempotent; no FKs; no CHECK constraints on synced text columns.
CREATE TABLE IF NOT EXISTS approval_withdrawals (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  awuuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  vessel_id TEXT NOT NULL,
  subject_type TEXT NOT NULL,          -- 'change-request' | 'wo-postponement' | 'defect-extension'
  subject_ref TEXT NOT NULL,           -- cruuid | wouuid | duuid
  extension_id TEXT,                   -- defect-extension only: the entry id inside target_date_extensions
  reason TEXT,
  requested_by_uuid TEXT NOT NULL,
  requested_by_name TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  outcome TEXT,                        -- NULL = waiting for the office | 'withdrawn' | 'too-late' | 'refused'
  outcome_at TIMESTAMPTZ,
  outcome_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_sync BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_approval_withdrawals_subject ON approval_withdrawals (subject_ref);
CREATE INDEX IF NOT EXISTS idx_approval_withdrawals_open ON approval_withdrawals (vessel_id) WHERE outcome IS NULL;
