-- 179: Approval history for Technical approvals (29-Sep-2026, Jeevan's "Approval process" request).
-- One row per event — who did what and when — for:
--   'wo-completion'       Work Order submitted / approved / rejected / Tech. Sup. acknowledged / reopened
--   'wo-postponement'     postponement requested / approved / rejected / withdrawn
--   'wo-re-postponement'  re-postponement requested / approved / rejected / withdrawn
--   'change-request'      Modify PMS change request submitted / approved / rejected / withdrawn
-- The actor's name and rank/position are FROZEN at the time of the event (they survive crew changes
-- and need no user lookup on the vessel). Rows are only ever inserted, never edited: the side where
-- the event happens (vessel or office) inserts it, so both sides never write the same row.
-- BOTH_EDITABLE for sync (vessel ↔ office). Idempotent; no FKs; no CHECK constraints on synced text.
CREATE TABLE IF NOT EXISTS approval_history (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ahuuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  vessel_id TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_ref TEXT NOT NULL,          -- wouuid | cruuid
  event_type TEXT NOT NULL,           -- submitted | approved | rejected | forwarded | completed | ts-acknowledged | ts-rejected | reopened | withdrawal-requested | withdrawn | withdrawal-too-late
  step_label TEXT,                    -- approval step name (approval workflow) when known
  actor_uuid TEXT,
  actor_name TEXT,
  actor_position TEXT,
  remarks TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_sync BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_approval_history_subject ON approval_history (subject_ref, occurred_at);
CREATE INDEX IF NOT EXISTS idx_approval_history_vessel ON approval_history (vessel_id);
