CREATE TABLE IF NOT EXISTS "ship_surveys_labels_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ship_surveys_labels_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_type" text NOT NULL,
	"key" text NOT NULL,
	"label" text DEFAULT '' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ship_surveys_master" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ship_surveys_master_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sequence" integer NOT NULL,
	"master_id" text NOT NULL,
	"survey_name" text NOT NULL,
	"category" text NOT NULL,
	"group" text NOT NULL,
	"requirement_ref" text,
	"applicable_to_company" boolean DEFAULT false NOT NULL,
	"survey_label" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"company_id" text,
	"company_group" text,
	"company_sequence" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ship_surveys_master_master_id_unique" UNIQUE("master_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_certificate_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_certificate_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"vessel_name" text NOT NULL,
	"master_id" text NOT NULL,
	"issue_date" text,
	"expiry_date" text,
	"last_annual" text,
	"last_interm" text,
	"endorsement_date" text,
	"last_edit_upload" text,
	"attachments" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_survey_applicability" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_survey_applicability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"vessel_name" text NOT NULL,
	"master_id" text NOT NULL,
	"is_applicable" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_survey_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vessel_survey_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"vessel_name" text NOT NULL,
	"master_id" text NOT NULL,
	"survey_date" text,
	"due_date" text,
	"first_range_date" text,
	"second_range_date" text,
	"postponed" text,
	"last_edit_upload" text,
	"attachments" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ship_survey_master_sequence" ON "ship_surveys_master" USING btree ("sequence");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ship_survey_master_category" ON "ship_surveys_master" USING btree ("category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ship_survey_master_group" ON "ship_surveys_master" USING btree ("group");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_cert_data_vessel_master" ON "vessel_certificate_data" USING btree ("vessel_id","master_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_cert_data_vessel" ON "vessel_certificate_data" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_cert_data_master" ON "vessel_certificate_data" USING btree ("master_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_vessel_master" ON "vessel_survey_applicability" USING btree ("vessel_id","master_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_vessel" ON "vessel_survey_applicability" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_master" ON "vessel_survey_applicability" USING btree ("master_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_data_vessel_master" ON "vessel_survey_data" USING btree ("vessel_id","master_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_data_vessel" ON "vessel_survey_data" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessel_survey_data_master" ON "vessel_survey_data" USING btree ("master_id");