CREATE TABLE IF NOT EXISTS "fleet_spares" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_spares_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fleet_spares_uuid" text DEFAULT gen_random_uuid(),
	"fleet_components_uuid" text,
	"part_code" text NOT NULL,
	"fleet_equipment_code" text NOT NULL,
	"fleet_equipment_name" text NOT NULL,
	"part_name" text NOT NULL,
	"part_number" text,
	"unit_of_measurement" text NOT NULL,
	"drawing_number" text,
	"position_number" text,
	"note" text,
	"specification" text,
	"maker" text,
	"maker_code" text,
	"manual_name" text,
	"page_number" text,
	"criticality" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"ihm" text,
	"evidence_type" text,
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false,
	"is_sync" boolean DEFAULT false,
	CONSTRAINT "fleet_spares_part_code_unique" UNIQUE("part_code")
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_fleet_spares_part_code" ON "fleet_spares" USING btree ("part_code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_fleet_spares_equipment" ON "fleet_spares" USING btree ("fleet_equipment_code");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_fleet_spares_uuid" ON "fleet_spares" USING btree ("fleet_spares_uuid");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_fleet_spares_component_uuid" ON "fleet_spares" USING btree ("fleet_components_uuid");