CREATE TABLE IF NOT EXISTS "report_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vessel_id" text NOT NULL,
	"report_type" text NOT NULL,
	"export_format" text NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	"generated_by" text,
	"item_count" integer DEFAULT 0 NOT NULL,
	"filters_applied" jsonb,
	"summary_data" jsonb NOT NULL,
	"items_data" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "manufacture_date" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "expiry_date" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "batch_number" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "lot_number" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "shelf_life_months" integer;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "sds_reference" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "sds_document_url" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "sds_last_updated" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "hazard_classification" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "un_number" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "flash_point" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "storage_temp_min" numeric(5, 2);--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "storage_temp_max" numeric(5, 2);--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "disposal_instructions" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "ppe_requirements" text;--> statement-breakpoint
ALTER TABLE "stores_items" ADD COLUMN IF NOT EXISTS "emergency_contact" text;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_snapshots_vessel" ON "report_snapshots" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_snapshots_type" ON "report_snapshots" USING btree ("report_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_snapshots_date" ON "report_snapshots" USING btree ("generated_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stores_expiry_date" ON "stores_items" USING btree ("expiry_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stores_hazard_class" ON "stores_items" USING btree ("hazard_classification");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stores_batch_number" ON "stores_items" USING btree ("batch_number");