CREATE TABLE "sync_batches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"batch_uuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"initiated_by_instance" text NOT NULL,
	"vessel_id" text,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"status" text DEFAULT 'in_progress' NOT NULL,
	"records_sent" integer DEFAULT 0,
	"records_received" integer DEFAULT 0,
	"conflicts_found" integer DEFAULT 0,
	"conflicts_resolved" integer DEFAULT 0,
	"files_queued" integer DEFAULT 0,
	"files_completed" integer DEFAULT 0,
	"checkpoint_before" timestamp,
	"checkpoint_after" timestamp,
	"error_message" text,
	"duration_ms" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_batches_batch_uuid_unique" UNIQUE("batch_uuid")
);
--> statement-breakpoint
CREATE TABLE "sync_conflicts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_conflicts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conflict_uuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"table_name" text NOT NULL,
	"row_uuid" text NOT NULL,
	"field_name" text NOT NULL,
	"ship_value" text,
	"ship_changed_at" timestamp,
	"ship_changed_by" text,
	"shore_value" text,
	"shore_changed_at" timestamp,
	"shore_changed_by" text,
	"resolution" text,
	"resolved_value" text,
	"resolved_at" timestamp,
	"resolved_by" text,
	"vessel_id" text,
	"sync_batch_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_conflicts_conflict_uuid_unique" UNIQUE("conflict_uuid")
);
--> statement-breakpoint
CREATE TABLE "sync_field_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_field_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"log_uuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"table_name" text NOT NULL,
	"row_uuid" text NOT NULL,
	"field_name" text NOT NULL,
	"old_value" text,
	"new_value" text,
	"vessel_id" text,
	"changed_at" timestamp DEFAULT now() NOT NULL,
	"changed_by_user_id" text,
	"instance_id" text NOT NULL,
	"sync_batch_id" text,
	"is_synced" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_field_log_log_uuid_unique" UNIQUE("log_uuid")
);
--> statement-breakpoint
CREATE TABLE "sync_file_queue" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_file_queue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"queue_uuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"table_name" text NOT NULL,
	"row_uuid" text NOT NULL,
	"file_key" text NOT NULL,
	"file_name" text,
	"file_size_bytes" integer,
	"file_hash" text,
	"direction" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"chunk_offset" integer DEFAULT 0,
	"total_chunks" integer,
	"priority" integer DEFAULT 0,
	"retry_count" integer DEFAULT 0,
	"last_error" text,
	"vessel_id" text,
	"instance_id" text NOT NULL,
	"sync_batch_id" text,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_file_queue_queue_uuid_unique" UNIQUE("queue_uuid")
);
--> statement-breakpoint
CREATE TABLE "sync_metadata" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sync_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"smuuid" text DEFAULT gen_random_uuid()::text NOT NULL,
	"instance_id" text NOT NULL,
	"vessel_id" text,
	"last_sync_checkpoint" timestamp,
	"last_sync_status" text,
	"last_sync_at" timestamp,
	"sync_direction" text,
	"sync_api_key" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by_uuid" text,
	"updated_by_uuid" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"is_sync" boolean DEFAULT false NOT NULL,
	CONSTRAINT "sync_metadata_smuuid_unique" UNIQUE("smuuid"),
	CONSTRAINT "sync_metadata_instance_id_unique" UNIQUE("instance_id")
);
--> statement-breakpoint
CREATE INDEX "idx_sb_vessel_status" ON "sync_batches" USING btree ("vessel_id","status");--> statement-breakpoint
CREATE INDEX "idx_sb_started_at" ON "sync_batches" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "idx_sb_instance" ON "sync_batches" USING btree ("initiated_by_instance");--> statement-breakpoint
CREATE INDEX "idx_sc_unresolved" ON "sync_conflicts" USING btree ("resolution");--> statement-breakpoint
CREATE INDEX "idx_sc_table_row_field" ON "sync_conflicts" USING btree ("table_name","row_uuid","field_name");--> statement-breakpoint
CREATE INDEX "idx_sc_vessel" ON "sync_conflicts" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_sc_sync_batch" ON "sync_conflicts" USING btree ("sync_batch_id");--> statement-breakpoint
CREATE INDEX "idx_sfl_table_row_uuid" ON "sync_field_log" USING btree ("table_name","row_uuid");--> statement-breakpoint
CREATE INDEX "idx_sfl_vessel_synced" ON "sync_field_log" USING btree ("vessel_id","is_synced");--> statement-breakpoint
CREATE INDEX "idx_sfl_instance_synced" ON "sync_field_log" USING btree ("instance_id","is_synced");--> statement-breakpoint
CREATE INDEX "idx_sfl_changed_at" ON "sync_field_log" USING btree ("changed_at");--> statement-breakpoint
CREATE INDEX "idx_sfl_sync_batch_id" ON "sync_field_log" USING btree ("sync_batch_id");--> statement-breakpoint
CREATE INDEX "idx_sfq_pending" ON "sync_file_queue" USING btree ("status","priority");--> statement-breakpoint
CREATE INDEX "idx_sfq_vessel" ON "sync_file_queue" USING btree ("vessel_id");--> statement-breakpoint
CREATE INDEX "idx_sfq_instance_direction" ON "sync_file_queue" USING btree ("instance_id","direction");--> statement-breakpoint
CREATE INDEX "idx_sfq_sync_batch" ON "sync_file_queue" USING btree ("sync_batch_id");