CREATE TABLE IF NOT EXISTS vessel_department_config (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vessel_id TEXT NOT NULL REFERENCES vessels(vuuid),
  department TEXT NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT vessel_dept_config_unique UNIQUE(vessel_id, department)
);
