-- 156: Rotational Items Tracking — data foundation
--
-- Components that are physically swapped between equipment positions (e.g. fuel
-- injectors) keep their own Running Hour history under a unique Stamp number.
--
-- components.rotational_item — flag, office-managed, flows shore→ship via normal
--   one-way component sync.
-- components.current_stamp   — MUTABLE POINTER to the currently-installed item;
--   rewritten on every swap. Permanent stamp identity lives ONLY in
--   rotational_items.stamp. Ship-side swaps sync via the rotation event tables
--   (Task: replacement flow), NOT via the components row.
--
-- rotational_items — BOTH_EDITABLE master registry of physical items (PURE MASTER,
-- Task #366 — no component back-pointer):
--   * riuuid: sync identity (uuid convention).
--   * stamp_name: part description shown wherever the stamp is picked/displayed.
--   * installed-on link is DERIVED via join components.current_stamp =
--     rotational_items.stamp (per vessel); historical "where fitted" trace lives
--     in the immutable rotation_history table.
--   * status: Installed | Spare | In Store | Retired.
--   * vessel_id is TEXT referencing vessels(vuuid) — codebase convention.
--
-- DEPLOYMENT ORDER: shore FIRST, ships after. Old ships never send rotational
-- rows; the one-way applier's unknown-column guard (added alongside this
-- migration) keeps shore→ship component sync working during the upgrade window.
--
-- Idempotent: safe to re-run (IF NOT EXISTS everywhere).

ALTER TABLE components ADD COLUMN IF NOT EXISTS rotational_item BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE components ADD COLUMN IF NOT EXISTS current_stamp TEXT;

CREATE TABLE IF NOT EXISTS rotational_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  riuuid TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  vessel_id TEXT NOT NULL REFERENCES vessels(vuuid),
  stamp TEXT NOT NULL,
  stamp_name TEXT,
  current_rh NUMERIC(10,2) NOT NULL DEFAULT 0,
  rh_last_updated TEXT,
  status TEXT NOT NULL DEFAULT 'Spare',
  -- standard audit/sync columns (migration 052 convention)
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by_uuid TEXT,
  updated_by_uuid TEXT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_sync BOOLEAN DEFAULT FALSE,
  sort_order INTEGER
);

-- Stamp unique per vessel among non-deleted items (retired/deleted stamps can be reissued)
CREATE UNIQUE INDEX IF NOT EXISTS uq_rotational_items_vessel_stamp
  ON rotational_items (vessel_id, stamp) WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_rotational_items_vessel ON rotational_items (vessel_id);
CREATE INDEX IF NOT EXISTS idx_rotational_items_status ON rotational_items (vessel_id, status);

-- Fast derived-join lookups: which component holds this stamp?
CREATE INDEX IF NOT EXISTS idx_comp_vessel_current_stamp
  ON components (vessel_id, current_stamp) WHERE current_stamp IS NOT NULL AND is_deleted = FALSE;
