import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Calendar, CalendarDays, Upload, View, Plus, Trash2, Edit, FileText } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Form, FormControl, FormField, FormItem, FormLabel } from "@/components/ui/form";
import { insertDefectSchema, type InsertDefect, type DefectAction } from "@shared/schema";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

// Form validation schema
const defectFormSchema = insertDefectSchema.extend({
  critical: z.boolean().optional(),
});

type DefectFormData = z.infer<typeof defectFormSchema>;

interface DefectFormProps {
  defect?: InsertDefect;
  onSuccess?: () => void;
  onCancel?: () => void;
}

export function DefectForm({ defect, onSuccess, onCancel }: DefectFormProps) {
  const { toast } = useToast();
  const [actions, setActions] = useState<DefectAction[]>([]);
  const [showActionForm, setShowActionForm] = useState(false);
  
  // Generate reference number (format: DN/007/21/1243/V)
  const generateReference = () => {
    const now = new Date();
    const year = now.getFullYear().toString().slice(-2);
    const random = Math.floor(Math.random() * 9999).toString().padStart(4, '0');
    return `DN/007/${year}/${random}/V`;
  };

  const form = useForm<DefectFormData>({
    resolver: zodResolver(defectFormSchema),
    defaultValues: defect || {
      id: generateReference(),
      vesselId: "V001",
      vesselName: "MV SEAFARER",
      issueDate: new Date().toISOString().split('T')[0],
      category: "",
      status: "Open",
      priority: "Medium",
      critical: false,
      severity: 1,
      reportedBy: "MASTER",
      ...(defect || {}),
    },
  });

  const onSubmit = async (data: DefectFormData) => {
    try {
      if (defect?.id) {
        await apiRequest(`/api/defects/${defect.id}`, "PATCH", data);
        toast({ title: "Defect updated successfully" });
      } else {
        await apiRequest("/api/defects", "POST", data);
        toast({ title: "Defect created successfully" });
      }
      onSuccess?.();
    } catch (error) {
      toast({ 
        title: "Error", 
        description: "Failed to save defect",
        variant: "destructive" 
      });
    }
  };

  const addAction = () => {
    const newAction: DefectAction = {
      id: 0, // Will be generated by backend
      defectId: form.getValues("id") || "",
      actionType: "Corrective Action Planned",
      actionDescription: "All crew members have been briefed on the correct procedure to carry out in accordance with the Quality Management Manual section 3.2 Personal protective Equipment. All crew members have been briefed on the correct procedure to carry out in accordance with the Quality Management Manual section 3.2 Personal protective Equipment.",
      proposedBy: "MASTER",
      responsibility: "Vessel Manager",
      dueDate: "29 May 2021",
      dateCompleted: "29 May 2021", 
      status: "Close",
      justification: null,
      attachmentUrls: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    setActions([...actions, newAction]);
  };

  return (
    <div className="max-w-7xl mx-auto p-6 space-y-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex items-center justify-between bg-white p-4 rounded-lg shadow-sm">
        <div className="flex items-center gap-4">
          <div className="w-8 h-8 bg-blue-600 rounded flex items-center justify-center">
            <FileText className="h-4 w-4 text-white" />
          </div>
          <h1 className="text-xl font-semibold">Defect Report</h1>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={onCancel} data-testid="button-back">
            ← Back
          </Button>
          <Button variant="outline" data-testid="button-view">
            View
          </Button>
          <Button onClick={form.handleSubmit(onSubmit)} data-testid="button-save">
            SAVE
          </Button>
        </div>
      </div>

      <Form {...form}>
        <form className="space-y-6">
          {/* Details Section */}
          <Card>
            <CardHeader className="pb-4">
              <div className="flex items-center justify-between">
                <CardTitle className="text-lg">Details</CardTitle>
                <Badge variant="secondary" className="text-blue-600 bg-blue-50">
                  {form.watch("id") || "DN/007/21/1243/V"}
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-6">
                {/* Basic Column */}
                <div className="space-y-4">
                  <h3 className="font-medium text-sm text-gray-700">Basic</h3>
                  
                  <FormField
                    control={form.control}
                    name="vesselId"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">VESSEL</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-vessel">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="V001">MV SEAFARER</SelectItem>
                            <SelectItem value="V002">MV VOYAGER</SelectItem>
                            <SelectItem value="V003">MV EXPLORER</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="source"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">SOURCE</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-source">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Internal">Internal</SelectItem>
                            <SelectItem value="External">External</SelectItem>
                            <SelectItem value="SIRE">SIRE</SelectItem>
                            <SelectItem value="PSC">PSC</SelectItem>
                            <SelectItem value="Class">Class</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="defectCategory"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">DEFECT CATEGORY</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-defect-category">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Minor">Minor</SelectItem>
                            <SelectItem value="Major">Major</SelectItem>
                            <SelectItem value="Catastrophic">Catastrophic</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="defectType"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">DEFECT TYPE</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-defect-type">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Routine">Routine</SelectItem>
                            <SelectItem value="Corrective">Corrective</SelectItem>
                            <SelectItem value="Emergency">Emergency</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />
                </div>

                {/* Equipment/Hardware Column */}
                <div className="space-y-4">
                  <h3 className="font-medium text-sm text-gray-700">Equipment / Hardware</h3>

                  <FormField
                    control={form.control}
                    name="equipmentCategory"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">CATEGORY</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-equipment-category">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Deck">Deck</SelectItem>
                            <SelectItem value="Navigation">Navigation</SelectItem>
                            <SelectItem value="Machinery">Machinery</SelectItem>
                            <SelectItem value="Safety">Safety</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="equipmentType"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">TYPE</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-equipment-type">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Pump">Pump</SelectItem>
                            <SelectItem value="Engine">Engine</SelectItem>
                            <SelectItem value="Valve">Valve</SelectItem>
                            <SelectItem value="Sensor">Sensor</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="equipmentMake"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">MAKE</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-make">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="Caterpillar">Caterpillar</SelectItem>
                            <SelectItem value="MAN">MAN</SelectItem>
                            <SelectItem value="Wartsila">Wartsila</SelectItem>
                            <SelectItem value="Kongsberg">Kongsberg</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="equipmentModel"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">MODEL</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-model">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="3516">3516</SelectItem>
                            <SelectItem value="6L32">6L32</SelectItem>
                            <SelectItem value="W32">W32</SelectItem>
                            <SelectItem value="K-Chief">K-Chief</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  {/* Purchase Order Section */}
                  <div className="pt-4 border-t">
                    <h4 className="font-medium text-sm text-blue-600 mb-2">Purchase Order</h4>
                    <FormField
                      control={form.control}
                      name="purchaseOrderRef"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs uppercase tracking-wide text-gray-500">P.O REF</FormLabel>
                          <FormControl>
                            <Input {...field} data-testid="input-po-ref" />
                          </FormControl>
                        </FormItem>
                      )}
                    />
                  </div>

                  {/* Critical Checkbox */}
                  <FormField
                    control={form.control}
                    name="critical"
                    render={({ field }) => (
                      <FormItem className="flex items-center space-x-2 pt-2">
                        <FormControl>
                          <Checkbox
                            checked={field.value}
                            onCheckedChange={field.onChange}
                            data-testid="checkbox-critical"
                          />
                        </FormControl>
                        <FormLabel className="text-sm">Critical</FormLabel>
                      </FormItem>
                    )}
                  />
                </div>

                {/* Date Column */}
                <div className="space-y-4">
                  <h3 className="font-medium text-sm text-gray-700">Date</h3>

                  <FormField
                    control={form.control}
                    name="issueDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">DATE ISSUED</FormLabel>
                        <FormControl>
                          <Input 
                            {...field} 
                            type="date"
                            data-testid="input-date-issued"
                            className="w-full" 
                          />
                        </FormControl>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="targetDate"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">TARGET DATE</FormLabel>
                        <FormControl>
                          <Input 
                            {...field} 
                            type="date"
                            data-testid="input-target-date"
                            className="w-full" 
                          />
                        </FormControl>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="dateCompleted"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">DATE COMPLETED</FormLabel>
                        <FormControl>
                          <Input 
                            {...field} 
                            type="date"
                            data-testid="input-date-completed"
                            className="w-full" 
                          />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              {/* Description Section */}
              <div className="mt-8 pt-6 border-t">
                <h3 className="font-medium text-sm text-gray-700 mb-4">Description</h3>
                
                <FormField
                  control={form.control}
                  name="description"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-xs uppercase tracking-wide text-gray-500">DESCRIPTION</FormLabel>
                      <FormControl>
                        <Textarea 
                          {...field}
                          rows={4}
                          data-testid="textarea-description"
                          className="w-full resize-none"
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />

                <div className="grid grid-cols-4 gap-4 mt-4">
                  <div className="bg-green-600 text-white px-4 py-2 rounded text-center">
                    <span className="text-sm font-medium">2 - Minor</span>
                  </div>
                  
                  <FormField
                    control={form.control}
                    name="viqVersion"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">VIQ VER</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-viq-ver">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="7.0">7.0</SelectItem>
                            <SelectItem value="6.0">6.0</SelectItem>
                            <SelectItem value="5.0">5.0</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="viqRef"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">VIQ REF</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-viq-ref">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="1.1">1.1</SelectItem>
                            <SelectItem value="1.2">1.2</SelectItem>
                            <SelectItem value="2.1">2.1</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="sfiCodeRef"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">SFI CODE REF</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl>
                            <SelectTrigger data-testid="select-sfi-code">
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="05">05</SelectItem>
                            <SelectItem value="06">06</SelectItem>
                            <SelectItem value="07">07</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />
                </div>

                <Button className="mt-4 bg-blue-600 hover:bg-blue-700" data-testid="button-save-form">
                  SAVE
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Cause Analysis Section */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Cause Analysis</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Immediate Cause */}
              <div>
                <h3 className="font-medium text-sm text-gray-700 mb-4">Immediate Cause</h3>
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="immediateCause"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">IMMEDIATE CAUSE</FormLabel>
                        <FormControl>
                          <Button variant="outline" className="w-full justify-start h-10" data-testid="button-select-immediate-cause">
                            {field.value || "Select"}
                          </Button>
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  
                  <FormField
                    control={form.control}
                    name="immediateCauseExplanation"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">FURTHER EXPLANATION</FormLabel>
                        <FormControl>
                          <Textarea 
                            {...field}
                            rows={3}
                            data-testid="textarea-immediate-cause"
                            className="resize-none"
                          />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
              </div>

              {/* Root Cause */}
              <div>
                <h3 className="font-medium text-sm text-gray-700 mb-4">Root Cause</h3>
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="rootCause"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">ROOT CAUSE</FormLabel>
                        <FormControl>
                          <Button variant="outline" className="w-full justify-start h-10" data-testid="button-select-root-cause">
                            {field.value || "Select"}
                          </Button>
                        </FormControl>
                      </FormItem>
                    )}
                  />
                  
                  <FormField
                    control={form.control}
                    name="rootCauseExplanation"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="text-xs uppercase tracking-wide text-gray-500">FURTHER EXPLANATION</FormLabel>
                        <FormControl>
                          <Textarea 
                            {...field}
                            rows={3}
                            data-testid="textarea-root-cause"
                            className="resize-none"
                          />
                        </FormControl>
                      </FormItem>
                    )}
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Actions Section */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-lg">ACTIONS</CardTitle>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={addAction}
                  className="text-green-600 hover:text-green-700"
                  data-testid="button-add-action"
                >
                  <Plus className="h-4 w-4 mr-1" />
                  ADD ACTION
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-gray-50">
                      <TableHead className="text-xs">Action Type</TableHead>
                      <TableHead className="text-xs">Proposed By</TableHead>
                      <TableHead className="text-xs">Responsibility</TableHead>
                      <TableHead className="text-xs">Due Date</TableHead>
                      <TableHead className="text-xs">Date Completed</TableHead>
                      <TableHead className="text-xs">Status</TableHead>
                      <TableHead className="text-xs w-16"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {actions.map((action, index) => (
                      <TableRow key={index}>
                        <TableCell className="text-sm">{action.actionType}</TableCell>
                        <TableCell className="text-sm">{action.proposedBy}</TableCell>
                        <TableCell className="text-sm">{action.responsibility}</TableCell>
                        <TableCell className="text-sm">{action.dueDate}</TableCell>
                        <TableCell className="text-sm">{action.dateCompleted}</TableCell>
                        <TableCell className="text-sm">{action.status}</TableCell>
                        <TableCell>
                          <div className="flex gap-1">
                            <Button size="sm" variant="ghost" className="h-8 w-8 p-0" data-testid={`button-edit-action-${index}`}>
                              <Edit className="h-3 w-3" />
                            </Button>
                            <Button size="sm" variant="ghost" className="h-8 w-8 p-0" data-testid={`button-delete-action-${index}`}>
                              <Trash2 className="h-3 w-3 text-red-500" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                    
                    {/* Default Action */}
                    <TableRow>
                      <TableCell className="text-sm">Corrective Action Planned</TableCell>
                      <TableCell className="text-sm">MASTER</TableCell>
                      <TableCell className="text-sm">Vessel Manager</TableCell>
                      <TableCell className="text-sm">29 May 2021</TableCell>
                      <TableCell className="text-sm">29 May 2021</TableCell>
                      <TableCell className="text-sm">Close</TableCell>
                      <TableCell>
                        <div className="flex gap-1">
                          <Button size="sm" variant="ghost" className="h-8 w-8 p-0" data-testid="button-edit-default-action">
                            <Edit className="h-3 w-3" />
                          </Button>
                          <Button size="sm" variant="ghost" className="h-8 w-8 p-0" data-testid="button-delete-default-action">
                            <Trash2 className="h-3 w-3 text-red-500" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>

              {/* Action Description */}
              <div className="mt-4 p-4 bg-gray-50 rounded">
                <h4 className="font-medium text-sm mb-2">Nature Of Action</h4>
                <p className="text-sm text-gray-700">
                  All crew members have been briefed on the correct procedure to carry out in accordance 
                  with the Quality Management Manual section 3.2 Personal protective Equipment. All crew 
                  members have been briefed on the correct procedure to carry out in accordance with the 
                  Quality Management Manual section 3.2 Personal protective Equipment.
                </p>
              </div>
            </CardContent>
          </Card>

          {/* File Upload Section */}
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-4">
                <Button type="button" variant="outline" className="gap-2" data-testid="button-upload">
                  <Upload className="h-4 w-4" />
                  UPLOAD
                </Button>
                <Button type="button" variant="outline" className="gap-2" data-testid="button-view-files">
                  <View className="h-4 w-4" />
                  VIEW
                </Button>
                <Button type="submit" className="ml-auto bg-blue-600 hover:bg-blue-700" data-testid="button-submit">
                  SUBMIT
                </Button>
              </div>
            </CardContent>
          </Card>
        </form>
      </Form>
    </div>
  );
}