import { pgTable, text, integer, boolean, timestamp, decimal, index, json } from "drizzle-orm/pg-core";

export const bulkComponents = pgTable("components", {
  id: text("id").primaryKey(),
  fleetEquipmentCode: text("fleet_equipment_code"),
  fleetEquipmentName: text("fleet_equipment_name"),
  parentId: text("parent_id"),
  componentCode: text("component_code"),
  name: text("name"),
  componentCategory: text("component_category"),
  maker: text("maker"),
  makerCode: text("maker_code"),
  model: text("model"),
  modelCode: text("model_code"),
  serialNo: text("serial_no"),
  drawingNo: text("drawing_no"),
  location: text("location"),
  critical: boolean("critical").default(false),
  conditionBased: boolean("condition_based").default(false),
  installationDate: text("installation_date"),
  commissionedDate: text("commissioned_date"),
  rating: text("rating"),
  eqptSystemDept: text("eqpt_system_dept"),
  isActive: boolean("is_active").default(true),
  vesselCode: text("vessel_code"),
  isParent: boolean("is_parent").default(false),
  notes: text("notes"),
  vesselId: text("vessel_id"),
  dataScope: text("data_scope").notNull().default("vessel"),
  parentFleetEquipmentCode: text("parent_fleet_equipment_code"),
  modelNumber: text("model_number"),
  department: text("department"),
  deptCategory: text("dept_category"),
  category: text("category"),
  classItem: boolean("class_item").default(false),
  noOfUnits: text("no_of_units"),
  parentComponent: text("parent_component"),
  dimensionsSize: text("dimensions_size"),
  runningHours: decimal("running_hours", { precision: 10, scale: 2 }),
  currentCumulativeRH: decimal("current_cumulative_rh", { precision: 10, scale: 2 }).notNull().default("0"),
  lastUpdated: text("last_updated"),
  applicableVesselIds: text("applicable_vessel_ids").array(),
  scopeNotes: text("scope_notes"),
  rhCounterType: text("rh_counter_type").notNull().default("NOT_RH_DRIVEN"),
  rhCounterSource: text("rh_counter_source"),
  rhMasterComponentId: text("rh_master_component_id"),
  rhCurrentMaster: decimal("rh_current_master", { precision: 10, scale: 2 }),
  rhMasterUpdatedAt: timestamp("rh_master_updated_at"),
  rhMasterUpdatedBy: text("rh_master_updated_by"),
  rhMasterUpdateSource: text("rh_master_update_source"),
  rhCurrentInheritedCached: decimal("rh_current_inherited_cached", { precision: 10, scale: 2 }),
  rhInheritedUpdatedAt: timestamp("rh_inherited_updated_at"),
  meterReplacedDate: timestamp("meter_replaced_date"),
  meterReplacedLastRh: decimal("meter_replaced_last_rh", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const bulkMakerList = pgTable("maker_list", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  makerCode: text("maker_code").notNull().unique(),
  makerName: text("maker_name").notNull(),
  address: text("address"),
  addressId: text("address_id"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const bulkImportHistory = pgTable("import_history", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  mode: text("mode").notNull(),
  archiveMissing: boolean("archive_missing").default(false),
  userId: text("user_id"),
  vesselId: text("vessel_id"),
  created: integer("created").default(0),
  updated: integer("updated").default(0),
  skipped: integer("skipped").default(0),
  archived: integer("archived").default(0),
  startedAt: timestamp("started_at").defaultNow(),
  finishedAt: timestamp("finished_at"),
  status: text("status").notNull().default("in_progress"),
  originalName: text("original_name"),
  fileSize: integer("file_size"),
  storedFilePath: text("stored_file_path"),
  undoneAt: timestamp("undone_at"),
  errorMessage: text("error_message"),
});

export const bulkImportChangeLog = pgTable("import_change_log", {
  id: text("id").primaryKey(),
  importHistoryId: text("import_history_id").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  operation: text("operation").notNull(),
  previousData: json("previous_data"),
  newData: json("new_data"),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const bulkSfiDetails = pgTable("sfi_details", {
  id: integer("id").primaryKey().generatedByDefaultAsIdentity(),
  componentCode: text("component_code").notNull().unique(),
  componentName: text("component_name").notNull(),
  description: text("description"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
