/**
 * One-Way Sync Applier — Upserts rows by UUID for one-way sync tables.
 *
 * Used for:
 * - SHIP_ONLY tables: ship pushes -> shore overwrites
 * - ONE_WAY_SHORE_TO_SHIP tables: shore pushes -> ship overwrites
 *
 * Uses raw SQL for dynamic table names since Drizzle ORM requires static table refs.
 */

import { getPool } from '../../db';
import { getTableSyncConfig, getIdentityColumn } from '../../../shared/syncConfig';
import { syncDiag } from './syncDiagLogger';
import { safeParseDate } from '../running-hours/utils/rhValidation';

interface ApplyResult {
  inserted: number;
  updated: number;
  softDeleted: number;
  errors: Array<{ rowIndex: number; error: string }>;
}

// ── Column metadata cache (schema-aware id/JSON handling) ──

export interface ColumnMeta {
  identityAlwaysCols: Set<string>;
  jsonCols: Set<string>;
  allCols: Set<string>;
  arrayCols: Set<string>;
}

const columnMetaCache = new Map<string, ColumnMeta>();

/**
 * Get column metadata for a table — caches auto-generated identity and JSON/JSONB info.
 * identityAlwaysCols includes BOTH 'GENERATED ALWAYS' AND 'GENERATED BY DEFAULT' columns
 * to prevent auto-increment PK conflicts during ship-shore sync.
 * Exported for reuse in syncEngine.ts (applyFieldLog JSON coercion).
 */
export async function getColumnMeta(pool: any, tableName: string): Promise<ColumnMeta> {
  if (columnMetaCache.has(tableName)) return columnMetaCache.get(tableName)!;

  let identityAlwaysCols = new Set<string>();
  let jsonCols = new Set<string>();
  let allCols = new Set<string>();
  let arrayCols = new Set<string>();

  try {
    // Find GENERATED ALWAYS or GENERATED BY DEFAULT AS IDENTITY columns
    // 'a' = ALWAYS, 'd' = BY DEFAULT — both must be excluded from INSERT/UPDATE
    // to avoid PK conflicts when ship sends its auto-increment id to shore (or vice versa)
    const identityResult = await pool.query(
      `SELECT a.attname FROM pg_attribute a
       JOIN pg_class c ON a.attrelid = c.oid
       JOIN pg_namespace n ON c.relnamespace = n.oid
       WHERE n.nspname = 'public' AND c.relname = $1 AND a.attidentity IN ('a', 'd')`,
      [tableName]
    );
    identityAlwaysCols = new Set((identityResult.rows || []).map((r: any) => r.attname));

    // Also detect serial/bigserial columns — these use nextval() DEFAULT but do NOT set
    // attidentity. Without this, ship's auto-increment id (e.g., id=5) is included in
    // INSERT, hitting PK conflict when shore already has its own id=5.
    const serialResult = await pool.query(
      `SELECT a.attname FROM pg_attribute a
       JOIN pg_class c ON a.attrelid = c.oid
       JOIN pg_namespace n ON c.relnamespace = n.oid
       JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
       WHERE n.nspname = 'public' AND c.relname = $1
       AND pg_get_expr(d.adbin, d.adrelid) LIKE 'nextval(%'`,
      [tableName]
    );
    for (const r of (serialResult.rows || [])) {
      identityAlwaysCols.add(r.attname);
    }
  } catch { /* ignore — table may not exist yet */ }

  try {
    // Find json/jsonb columns (for value coercion)
    const jsonResult = await pool.query(
      `SELECT column_name FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1
       AND data_type IN ('json', 'jsonb')`,
      [tableName]
    );
    jsonCols = new Set((jsonResult.rows || []).map((r: any) => r.column_name));
  } catch { /* ignore */ }

  try {
    // All column names — used by the field-log appliers to skip unmapped/absent columns
    // (defense-in-depth) rather than letting an unknown column abort the pull transaction.
    const colResult = await pool.query(
      `SELECT column_name FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1`,
      [tableName]
    );
    allCols = new Set((colResult.rows || []).map((r: any) => r.column_name));
  } catch { /* ignore — table may not exist yet; guard is fail-open when allCols is empty */ }

  try {
    // Postgres array columns (text[] etc.) — values must reach pg as a JS array, not a JSON
    // string, or the insert/update fails with "malformed array literal".
    const arrResult = await pool.query(
      `SELECT column_name FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1 AND data_type = 'ARRAY'`,
      [tableName]
    );
    arrayCols = new Set((arrResult.rows || []).map((r: any) => r.column_name));
  } catch { /* ignore */ }

  const meta = { identityAlwaysCols, jsonCols, allCols, arrayCols };
  columnMetaCache.set(tableName, meta);
  return meta;
}

/**
 * Apply one-way rows — upsert by identity column (UUID).
 *
 * @param tableName - Target table name
 * @param rows - Array of row objects to upsert
 * @returns Counts of inserts, updates, soft-deletes, and any per-row errors
 */
export async function applyOneWayRows(
  tableName: string,
  rows: any[]
): Promise<ApplyResult> {
  if (rows.length === 0) return { inserted: 0, updated: 0, softDeleted: 0, errors: [] };

  syncDiag(`ONE-WAY-APPLY START: ${tableName} — ${rows.length} rows`);

  const config = getTableSyncConfig(tableName);
  if (!config) {
    return {
      inserted: 0, updated: 0, softDeleted: 0,
      errors: [{ rowIndex: -1, error: `Unknown table: ${tableName}` }],
    };
  }

  const identityCol = config.identityColumn;
  // Tables without a UUID identity column use the text PK 'id'
  const lookupColumn = identityCol || 'id';

  const pool = await getPool();

  // Schema-aware column metadata (GENERATED ALWAYS + JSON detection)
  const meta = await getColumnMeta(pool, tableName);

  // Detect composite-key tables: no UUID identity + integer GENERATED PKs that differ
  // between shore and ship. We match by their natural unique key instead of mismatched id.
  const COMPOSITE_KEY_TABLES: Record<string, string[]> = {
    vessel_certificate_applicability: ['vessel_id', 'master_id'],
    vessel_survey_applicability: ['vessel_id', 'master_id'],
    // RBAC permissions — UNIQUE on (role_ruid, menu_muid)
    adm_role_menu_access: ['role_ruid', 'menu_muid'],
    // Vessel department config — UNIQUE on (vessel_id, department)
    vessel_department_config: ['vessel_id', 'department'],
    // Master lists — UNIQUE on (list_type, list_key)
    master_lists: ['list_type', 'list_key'],
    // Job-component links — UNIQUE on (job_id, component_id)
    job_component_links: ['job_id', 'component_id'],
    // Labels config — logical key (config_type, key), no formal UNIQUE constraint
    ship_certificates_labels_config: ['config_type', 'key'],
    ship_surveys_labels_config: ['config_type', 'key'],
    // Alert config — one per vessel
    alert_config: ['vessel_id'],
    // Component class regulatory — match by (component_id, survey_type, classification_society)
    component_class_regulatory: ['component_id', 'survey_type', 'classification_society'],
  };
  const compositeKeys = COMPOSITE_KEY_TABLES[tableName] || null;
  const useCompositeKey = compositeKeys !== null && !identityCol;

  const result: ApplyResult = { inserted: 0, updated: 0, softDeleted: 0, errors: [] };

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    try {
      // Check if this is a soft-delete marker
      const isDeleted = row.is_deleted === true || row.isDeleted === true;

      let existCheck: any;
      let whereClause: string;
      let whereValues: any[];

      if (useCompositeKey) {
        // Composite-key lookup: match by (vessel_id, master_id) etc.
        const conditions: string[] = [];
        whereValues = [];
        let pIdx = 1;
        for (const keyCol of compositeKeys!) {
          const val = row[keyCol] || row[toCamelCase(keyCol)];
          if (!val) {
            break;
          }
          conditions.push(`"${keyCol}" = $${pIdx}`);
          whereValues.push(val);
          pIdx++;
        }
        if (conditions.length !== compositeKeys!.length) {
          // Missing composite key columns — fall back to id lookup
          const lookupValue = row[lookupColumn] || row[toCamelCase(lookupColumn)];
          if (!lookupValue) {
            result.errors.push({ rowIndex: i, error: `Missing composite key columns for "${tableName}"` });
            continue;
          }
          whereClause = `"${lookupColumn}" = $1`;
          whereValues = [lookupValue];
        } else {
          whereClause = conditions.join(' AND ');
        }
        existCheck = await pool.query(
          `SELECT "id" FROM "${tableName}" WHERE ${whereClause} LIMIT 1`,
          whereValues
        );
      } else {
        // Standard single-column lookup
        const lookupValue = row[lookupColumn] || row[toCamelCase(lookupColumn)];
        if (!lookupValue) {
          result.errors.push({ rowIndex: i, error: `Missing identity column "${lookupColumn}"` });
          continue;
        }
        whereClause = `"${lookupColumn}" = $1`;
        whereValues = [lookupValue];
        existCheck = await pool.query(
          `SELECT 1 FROM "${tableName}" WHERE ${whereClause} LIMIT 1`,
          whereValues
        );
      }

      if (existCheck.rows.length > 0) {
        if (isDeleted) {
          // Soft-delete: set is_deleted = true
          await pool.query(
            `UPDATE "${tableName}" SET is_deleted = true, updated_at = NOW() WHERE ${whereClause}`,
            whereValues
          );
          result.softDeleted++;
        } else {
          // Update all columns (excluding PK and generated columns)
          const updatePairs = buildUpdatePairs(row, lookupColumn, meta);
          if (updatePairs.setClauses.length > 0) {
            // Re-parameterize WHERE clause to follow UPDATE SET params
            const offset = updatePairs.values.length;
            const reindexedWhere = whereClause.replace(/\$(\d+)/g, (_, n) => `$${Number(n) + offset}`);
            const updateSQL = `UPDATE "${tableName}" SET ${updatePairs.setClauses.join(', ')}, updated_at = NOW() WHERE ${reindexedWhere}`;
            await pool.query(updateSQL, [...updatePairs.values, ...whereValues]);
          }
          result.updated++;
        }
      } else {
        if (isDeleted) {
          // Row doesn't exist and is deleted — skip
          result.softDeleted++;
          continue;
        }
        // Insert new row — skip the integer PK for composite-key tables so the
        // ship DB generates its own sequence value (avoids PK collisions)
        const insertParts = buildInsertParts(row, meta, useCompositeKey);
        if (insertParts.columns.length > 0) {
          const insertSQL = `INSERT INTO "${tableName}" (${insertParts.columns.join(', ')}) VALUES (${insertParts.placeholders.join(', ')}) ON CONFLICT DO NOTHING`;
          await pool.query(insertSQL, insertParts.values);
          result.inserted++;
        }
      }
    } catch (err: any) {
      syncDiag(`ONE-WAY-APPLY ROW ERROR: ${tableName} row[${i}]: ${err.message.substring(0, 150)}`);
      result.errors.push({ rowIndex: i, error: err.message });
    }
  }

  syncDiag(`ONE-WAY-APPLY DONE: ${tableName} — inserted=${result.inserted}, updated=${result.updated}, deleted=${result.softDeleted}, errors=${result.errors.length}`);

  // Advance sequences for GENERATED ALWAYS identity columns so future
  // INSERTs (via UI or next sync) don't collide with imported integer PKs.
  if (meta.identityAlwaysCols.size > 0) {
    for (const col of Array.from(meta.identityAlwaysCols)) {
      try {
        await pool.query(
          `SELECT setval(pg_get_serial_sequence('"${tableName}"', '${col}'), GREATEST(COALESCE((SELECT MAX("${col}") FROM "${tableName}"), 0), 1))`
        );
      } catch (e: any) {
        console.warn(`[OneWayApplier] Could not advance sequence for ${tableName}.${col}: ${e.message}`);
      }
    }
  }

  // Log detailed error messages so operators can diagnose failures
  if (result.errors.length > 0) {
    console.error(`[OneWayApplier] ${result.errors.length} errors applying ${tableName}:`);
    result.errors.slice(0, 5).forEach((e) =>
      console.error(`  - row ${e.rowIndex}: ${e.error}`)
    );
    if (result.errors.length > 5) {
      console.error(`  ... and ${result.errors.length - 5} more`);
    }
  }

  return result;
}

// ── Helpers ──

/** Convert snake_case to camelCase */
function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Convert camelCase to snake_case */
function toSnakeCase(str: string): string {
  // Handle consecutive uppercase (acronyms) correctly:
  // timestampUTC → timestamp_utc, previousRH → previous_rh, completionRHValidated → completion_rh_validated
  return str
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')   // split acronym from next word: "RHV" → "RH_V"
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')       // split camelCase: "timestamp" + "U" → "timestamp_U"
    .toLowerCase();
}

// Column-name aliases for field_name → DB column where the camel→snake round-trip fails.
// location2 (JS prop) ↔ location_2 (DB col): toSnakeCase only inserts '_' before an uppercase
// letter, never before a digit, so "location2" wrongly stays "location2". A global digit-split
// rule is unsafe — it would break level1/2/3, *_hardware_level*, level2_reviewer_rank_id, etc.
// which round-trip correctly today. So alias the single offender explicitly. Exact-match only.
export const SYNC_COLUMN_ALIASES: Record<string, string> = { location2: 'location_2' };

/** Resolve a field_name to its DB column, honoring SYNC_COLUMN_ALIASES then toSnakeCase. */
export function fieldNameToColumn(fieldName: string): string {
  return SYNC_COLUMN_ALIASES[fieldName] ?? toSnakeCase(fieldName);
}

/** Normalize an array-column value to a JS array so node-postgres serializes a real Postgres
 *  array literal ({...}). Field logs store arrays as JSON strings ('["a","b"]'); provisioning
 *  passes JS arrays. A JSON string inserted into text[] → "malformed array literal". Already-
 *  formatted pg literals ('{...}') and plain scalars pass through unchanged. Handles: JS array,
 *  JSON-string array, pg literal, empty array (→ '{}' via pg), and null. */
export function coerceArrayValue(value: any): any {
  if (value === null || value === undefined) return null;
  if (Array.isArray(value)) return value;
  if (typeof value === 'string') {
    const s = value.trim();
    if (s.startsWith('[')) {
      try { const parsed = JSON.parse(s); if (Array.isArray(parsed)) return parsed; } catch { /* fall through */ }
    }
    return value; // pg array literal '{...}' or unparseable scalar — leave as-is
  }
  return value;
}

// Columns that should not be included in UPDATE (PK + auto-generated timestamps)
const SKIP_UPDATE_COLUMNS = new Set(['id', 'created_at', 'createdAt']);

/** Coerce a value for the correct PostgreSQL column type */
function coerceValue(value: any, snakeKey: string, meta: ColumnMeta): any {
  if (value === null || value === undefined) return null;
  if (meta.jsonCols.has(snakeKey)) {
    // JSON/JSONB column: ensure value is a valid JSON string for PostgreSQL
    if (typeof value === 'string') {
      try { JSON.parse(value); return value; } catch { return JSON.stringify(value); }
    }
    if (typeof value === 'object' && !(value instanceof Date)) {
      return JSON.stringify(value);
    }
    return JSON.stringify(value);
  }
  if (meta.arrayCols.has(snakeKey)) {
    // Postgres array column — return a JS array so pg serializes {...}, not JSON [...]
    return coerceArrayValue(value);
  }
  // Non-JSON: stringify plain objects for TEXT/VARCHAR columns
  if (typeof value === 'object' && !(value instanceof Date)) {
    return JSON.stringify(value);
  }
  return value;
}

/** Build SET clauses for UPDATE */
function buildUpdatePairs(
  row: any,
  identityCol: string,
  meta: ColumnMeta
): { setClauses: string[]; values: any[] } {
  const setClauses: string[] = [];
  const values: any[] = [];
  let paramIndex = 1;

  for (const [key, value] of Object.entries(row)) {
    const snakeKey = toSnakeCase(key);
    // Skip PK, identity, generated-always, and auto-generated columns
    if (SKIP_UPDATE_COLUMNS.has(key) || SKIP_UPDATE_COLUMNS.has(snakeKey)) continue;
    if (meta.identityAlwaysCols.has(key) || meta.identityAlwaysCols.has(snakeKey)) continue;
    if (key === identityCol || snakeKey === identityCol) continue;
    if (key === 'updated_at' || key === 'updatedAt') continue; // We set this ourselves

    setClauses.push(`"${snakeKey}" = $${paramIndex}`);
    values.push(coerceValue(value, snakeKey, meta));
    paramIndex++;
  }

  return { setClauses, values };
}

/** Build columns/placeholders/values for INSERT */
function buildInsertParts(
  row: any,
  meta: ColumnMeta,
  skipIntegerPK: boolean = false
): { columns: string[]; placeholders: string[]; values: any[] } {
  const columns: string[] = [];
  const placeholders: string[] = [];
  const values: any[] = [];
  let paramIndex = 1;

  for (const [key, value] of Object.entries(row)) {
    const snakeKey = toSnakeCase(key);
    // Skip only GENERATED ALWAYS columns (e.g. adm_role_menu_access.id)
    // — do NOT skip regular integer PKs (admn_role_master.id, adm_menumaster_ac.id)
    if (meta.identityAlwaysCols.has(key) || meta.identityAlwaysCols.has(snakeKey)) continue;

    // For composite-key tables, skip the integer PK so the receiving side
    // generates its own sequence value (avoids PK collisions between shore/ship)
    if (skipIntegerPK && (snakeKey === 'id') && typeof value === 'number') continue;

    columns.push(`"${snakeKey}"`);
    placeholders.push(`$${paramIndex}`);
    values.push(coerceValue(value, snakeKey, meta));
    paramIndex++;
  }

  return { columns, placeholders, values };
}

// ════════════════════════════════════════════════════════════════════════════════
// FIELD LOG INSERT APPLIER — Handles INSERT for new BOTH_EDITABLE rows via field logs
// ════════════════════════════════════════════════════════════════════════════════

/**
 * Field log entry structure (as received from push/pull).
 */
export interface FieldLogEntry {
  tableName: string;
  rowUuid: string;
  fieldName: string;
  oldValue: string | null;
  newValue: string | null;
  vesselId?: string | null;
  changedAt?: string | Date;
  changedByUserId?: string | null;
  instanceId?: string;
}

/**
 * Apply a batch of field logs, handling both INSERT (new rows) and UPDATE (existing fields).
 *
 * Logic:
 * - Group field logs by (tableName, rowUuid)
 * - If ALL logs in a group have oldValue === null → it's an INSERT
 *   - Check if row already exists (idempotency)
 *   - If not: build INSERT INTO ... ON CONFLICT DO NOTHING
 * - Otherwise → individual UPDATE per field (existing behavior, delegated to caller)
 *
 * Returns:
 * - insertedRows: count of new rows inserted
 * - updateLogs: field logs that need UPDATE (not part of an INSERT group)
 * - errors: any errors during INSERT
 */
export async function applyFieldLogInserts(
  fieldLogs: FieldLogEntry[],
  /** Optional pg client to reuse (for transactional SET LOCAL sync.bypass_trigger) */
  externalClient?: { query: (text: string, values?: any[]) => Promise<any> }
): Promise<{
  insertedRows: number;
  updateLogs: FieldLogEntry[];
  errors: string[];
  failedRowUuids: string[];
}> {
  if (fieldLogs.length === 0) {
    return { insertedRows: 0, updateLogs: [], errors: [], failedRowUuids: [] };
  }

  syncDiag(`FIELD-LOG-INSERT START: ${fieldLogs.length} logs`);

  const pool = externalClient || await getPool();
  let insertedRows = 0;
  const updateLogs: FieldLogEntry[] = [];
  const errors: string[] = [];
  // Fix 2/3: row_uuids whose INSERT was DROPPED (not applied, not deferred-to-update).
  // Returned so the push-ack can tell the ship to keep them is_synced=false and retry,
  // instead of silently losing them. Populated ONLY at true drop sites (below), never at
  // the defer-to-update sites (unknown table / row-exists / exist-check) which are not lost.
  const failedRowUuids: string[] = [];

  // 1. Group by (tableName, rowUuid)
  const groups = new Map<string, FieldLogEntry[]>();
  for (const log of fieldLogs) {
    const key = `${log.tableName}::${log.rowUuid}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(log);
  }

  // 2. Classify each group as INSERT or UPDATE
  //
  // BUG FIX (2026-05-14): Previously only groups where ALL logs had oldValue===null
  // were treated as INSERT candidates. But when a user creates a cert and immediately
  // edits dates/attachments, the group has MIXED logs (INSERT + UPDATE). The old check
  // `logs.every(l => l.oldValue === null)` returned false, routing everything to UPDATE.
  // The UPDATE path does `UPDATE ... WHERE identity = $1` — but the row doesn't exist
  // on the receiving side, so 0 rows are updated and data is silently lost.
  //
  // Fix: Check if ANY log has oldValue===null (indicating at least part of the group
  // originated from an INSERT). If yes AND the row doesn't exist → INSERT using the
  // latest newValue for each field. After INSERT, only route non-INSERT logs that
  // have newer values (they'll be UPDATE'd by the caller if needed).
  syncDiag(`FIELD-LOG-INSERT: ${groups.size} groups from ${fieldLogs.length} logs`);
  const groupKeys = Array.from(groups.keys());
  for (const groupKey of groupKeys) {
    const logs = groups.get(groupKey)!;
    // Loose == null (null OR undefined): the wire is JSON so null should survive,
    // but be defensive against any mapping/storage variant that turns a null
    // oldValue into undefined — strict ===null silently reclassified INSERT
    // groups as UPDATE-shaped, and UPDATEs against a missing row vanish.
    const isInsertGroup = logs.every((l: FieldLogEntry) => l.oldValue == null);
    const hasAnyInsertLogs = logs.some((l: FieldLogEntry) => l.oldValue == null);

    const tableName = logs[0].tableName;
    const rowUuid = logs[0].rowUuid;

    const config = getTableSyncConfig(tableName);
    if (!config) {
      errors.push(`${tableName}: unknown table`);
      updateLogs.push(...logs); // fallback to UPDATE attempt
      continue;
    }

    const identityCol = config.identityColumn || 'id';

    if (!isInsertGroup && !hasAnyInsertLogs) {
      // UPDATE-shaped group (no INSERT-origin logs). Previously passed straight
      // to the per-field UPDATE path — which did NOTHING when the row didn't
      // exist on the receiver (UPDATE matched 0 rows, errors=0). That silent
      // drop is how generated WOs vanished (Issue 01). Now: if the receiver row
      // EXISTS → per-field UPDATE as before; if it's MISSING → loud warning and
      // a recovery INSERT built from the logs' newValues (savepoint-guarded
      // below; on failure it falls back to passthrough, which the UPDATE-MISS
      // counter in receivePushData now also surfaces).
      try {
        const exist = await pool.query(`SELECT 1 FROM "${tableName}" WHERE "${identityCol}" = $1 LIMIT 1`, [rowUuid]);
        if (exist.rows.length > 0) {
          updateLogs.push(...logs);
          continue;
        }
        const msg = `${tableName}.${rowUuid}: UPDATE-shaped group (${logs.length} logs) for a row that does NOT exist on receiver — attempting recovery INSERT from newValues`;
        console.warn(`[FieldLogInsert] ${msg}`);
        syncDiag(`FIELD-LOG-INSERT RECOVERY: ${msg}`);
        // fall through to the INSERT build below
      } catch (existErr: any) {
        errors.push(`${tableName}.${rowUuid}: exist-check failed (${existErr.message})`);
        updateLogs.push(...logs);
        continue;
      }
    }

    // Hoist meta + rowData so they're accessible in the catch block for conflict resolution
    let meta: Awaited<ReturnType<typeof getColumnMeta>> | null = null;
    let rowData: Record<string, any> = {};

    // SAVEPOINT isolation: if this INSERT fails (e.g., PK conflict from serial id),
    // we ROLLBACK TO SAVEPOINT so the PostgreSQL transaction stays valid for
    // subsequent groups. Without this, one failed INSERT aborts the entire transaction
    // and all later UPDATEs silently fail ("current transaction is aborted").
    const savepointName = `ins_${tableName.replace(/[^a-z0-9_]/gi, '')}_${rowUuid.replace(/[^a-z0-9]/gi, '').substring(0, 8)}`;
    if (externalClient) {
      try { await pool.query(`SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
    }

    try {
      // Idempotency check — does row already exist?
      const existCheck = await pool.query(
        `SELECT 1 FROM "${tableName}" WHERE "${identityCol}" = $1 LIMIT 1`,
        [rowUuid]
      );

      if (existCheck.rows.length > 0) {
        // Row exists — treat as UPDATE (maybe a re-sync or partial previous apply)
        updateLogs.push(...logs);
        continue;
      }

      // Build the row object from field logs.
      // For mixed groups (INSERT + UPDATE logs), sort by changedAt so we take the
      // LATEST value for each field — a subsequent UPDATE log may have a newer value
      // than the initial INSERT log for the same field.
      meta = await getColumnMeta(pool, tableName);
      rowData = {};

      // Set identity column
      rowData[identityCol] = rowUuid;

      // Set vessel_id if available from logs and config requires it
      if (config.vesselScopeColumn && logs[0].vesselId) {
        rowData[config.vesselScopeColumn] = logs[0].vesselId;
      }

      // Sort logs by changedAt ascending so later values overwrite earlier ones
      const sortedLogs = [...logs].sort((a, b) => {
        const aTime = a.changedAt instanceof Date ? a.changedAt.getTime() : new Date(String(a.changedAt)).getTime();
        const bTime = b.changedAt instanceof Date ? b.changedAt.getTime() : new Date(String(b.changedAt)).getTime();
        return aTime - bTime;
      });

      // Set all logged fields (latest value wins per field)
      for (const log of sortedLogs) {
        const snakeField = fieldNameToColumn(log.fieldName);

        // Skip GENERATED ALWAYS columns
        if (meta.identityAlwaysCols.has(snakeField)) continue;

        // Defense-in-depth: skip columns that don't exist on this table so an unmapped/absent
        // field can never abort the pull transaction. Fail-open when allCols is unknown (empty).
        if (meta.allCols.size > 0 && !meta.allCols.has(snakeField)) {
          syncDiag(`FIELD-LOG-INSERT SKIP unknown column ${tableName}.${snakeField} (row ${rowUuid})`);
          continue;
        }

        // JSON coercion
        let value: any = log.newValue;
        if (value !== null && meta.jsonCols.has(snakeField)) {
          try {
            JSON.parse(value);
            // Valid JSON string — use as-is
          } catch {
            value = '[]'; // Corrupted → reset
          }
        } else if (value !== null && meta.arrayCols.has(snakeField)) {
          // Field logs store arrays as JSON strings ('["a"]') — parse back to a JS array so pg
          // serializes a real array literal ({...}) instead of failing on the JSON string.
          value = coerceArrayValue(value);
        }

        rowData[snakeField] = value;
      }

      // Add timestamps
      if (!rowData['created_at']) rowData['created_at'] = new Date();
      if (!rowData['updated_at']) rowData['updated_at'] = new Date();

      // Defense-in-depth (pairs with full-row-creation logging): work_orders.id is a LOCAL text PK
      // with no DB default, and it is intentionally NOT carried across instances (every child table
      // FKs to wouuid, never to id). If an incoming INSERT lacks `id`, assign a fresh local id keyed
      // on wouuid so the row is NEVER dropped for a missing local id ("null value in column id").
      // Idempotent: same wouuid -> same synthesized id, and ON CONFLICT (wouuid) dedups re-applies.
      if (tableName === 'work_orders' && (rowData['id'] === undefined || rowData['id'] === null)) {
        rowData['id'] = `WO-SYNC-${rowUuid}`;
      }

      // Build INSERT statement
      const columns: string[] = [];
      const placeholders: string[] = [];
      const values: any[] = [];
      let paramIdx = 1;

      for (const [col, val] of Object.entries(rowData)) {
        // Skip GENERATED ALWAYS columns
        if (meta.identityAlwaysCols.has(col)) continue;

        columns.push(`"${col}"`);
        placeholders.push(`$${paramIdx}`);
        // Coerce value for correct pg type
        if (val !== null && meta.jsonCols.has(col)) {
          // Already handled above, pass as-is
          values.push(val);
        } else if (val instanceof Date) {
          values.push(val);
        } else {
          values.push(val);
        }
        paramIdx++;
      }

      if (columns.length === 0) {
        errors.push(`${tableName}.${rowUuid}: no columns to insert`);
        failedRowUuids.push(rowUuid);
        continue;
      }

      const insertSQL = `INSERT INTO "${tableName}" (${columns.join(', ')}) VALUES (${placeholders.join(', ')}) ON CONFLICT ("${identityCol}") DO NOTHING`;

      await pool.query(insertSQL, values);
      insertedRows++;
      syncDiag(`FIELD-LOG-INSERT OK: ${tableName} row=${rowUuid} (${columns.length} columns)`);
      console.log(`[FieldLogInsert] Inserted new row ${tableName}.${rowUuid} (${columns.length} columns)`);

      // ── Post-INSERT: Derived RH update — propagate running_hours_audit to components current state ──
      // When a running_hours_audit row arrives via sync, the audit row is BOTH_EDITABLE but
      // components is ONE_WAY_SHORE_TO_SHIP. The current-state fields (current_cumulative_rh,
      // rh_current_master) on the receiving side stay stale. Fix: read new_rh + cumulative_rh
      // from the inserted audit row and UPDATE the corresponding component.
      if (tableName === 'running_hours_audit' && rowData['component_id']) {
        try {
          const compId = rowData['component_id'];
          const newRH = rowData['cumulative_rh'] || rowData['new_rh'];
          if (newRH !== undefined && newRH !== null) {
            // Read old value for diag
            const oldRow = await pool.query(
              `SELECT current_cumulative_rh, rh_current_master FROM components WHERE cuuid = $1 LIMIT 1`,
              [compId]
            );
            const oldVal = oldRow.rows[0]?.current_cumulative_rh || oldRow.rows[0]?.rh_current_master || '(not found)';
            // Also propagate rh_master_updated_at + last_updated so "Last Updated Date" reflects on shore.
            // The API reads: component.lastUpdated || component.rhMasterUpdatedAt || component.updatedAt
            // last_updated (TEXT) has highest priority, so it MUST be set here.
            // Components is ONE_WAY_SHORE_TO_SHIP — vessel's last_updated change never syncs back.
            // IMPORTANT: Vessel sets last_updated = date_updated_local (user-selected date, e.g. "13-May-2026 10:30").
            // We must use the same field here — NOT entered_at_utc which is a system timestamp.
            const rhUpdatedAt = rowData['entered_at_utc'] || new Date();
            const lastUpdatedText = rowData['date_updated_local'] || (rhUpdatedAt instanceof Date ? rhUpdatedAt : new Date(String(rhUpdatedAt))).toISOString();
            // rh_master_updated_at must be the USER's reading date (date_updated_local),
            // NOT entered_at_utc (system write time) — feeds "Last Updated" MAX() and the
            // WO-approval back-dated check (Issues 1 & 2).
            const rhMasterUpdatedAtVal = safeParseDate(rowData['date_updated_local']) || rhUpdatedAt;
            await pool.query(
              `UPDATE components SET current_cumulative_rh = $1, rh_current_master = $1, rh_master_updated_at = $3, last_updated = $4, updated_at = NOW() WHERE cuuid = $2`,
              [String(newRH), compId, rhMasterUpdatedAtVal, lastUpdatedText]
            );
            syncDiag(`RH-APPLY INSERT: component=${compId} current_cumulative_rh updated from ${oldVal} to ${newRH}, last_updated=${lastUpdatedText} from audit row ${rowUuid}`);
          }
        } catch (rhErr: any) {
          syncDiag(`RH-APPLY INSERT ERROR: component=${rowData['component_id']} audit=${rowUuid}: ${rhErr.message}`);
        }
      }

      // ── Post-INSERT: Cross-instance integer FK resolution for location_uuid → location_id ──
      // When a new spare_location_stock or inventory_transactions row is inserted from a remote
      // instance, the sender's integer location_id may not match the receiver's auto-increment.
      // If location_uuid is present, resolve to the local locations.id.
      if ((tableName === 'spare_location_stock' || tableName === 'inventory_transactions') && rowData['location_uuid']) {
        try {
          const locLookup = await pool.query(
            `SELECT id FROM locations WHERE luuid = $1 LIMIT 1`,
            [rowData['location_uuid']]
          );
          if (locLookup.rows.length > 0) {
            await pool.query(
              `UPDATE "${tableName}" SET "location_id" = $1 WHERE "${identityCol}" = $2`,
              [locLookup.rows[0].id, rowUuid]
            );
            syncDiag(`FK-REMAP INSERT: ${tableName} row=${rowUuid} location_uuid=${rowData['location_uuid']} → local location_id=${locLookup.rows[0].id}`);
          } else {
            syncDiag(`FK-REMAP INSERT DEFERRED: ${tableName} row=${rowUuid} location_uuid=${rowData['location_uuid']} — location not yet synced`);
          }
        } catch (fkErr: any) {
          syncDiag(`FK-REMAP INSERT ERROR: ${tableName} row=${rowUuid}: ${fkErr.message}`);
        }
      }

      // Release savepoint on success — keeps transaction clean
      if (externalClient) {
        try { await pool.query(`RELEASE SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
      }
    } catch (err: any) {
      // Rollback to savepoint so the transaction stays valid for subsequent groups
      if (externalClient) {
        try { await pool.query(`ROLLBACK TO SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
      }
      // 23505 = unique_violation — another unique constraint (not the identity column)
      // was violated. This happens when both ship and shore independently created rows
      // for the same logical entity (e.g., same vessel_id + master_id in vessel_certificate_data).
      // Fallback: find the conflicting row and apply updates to it.
      if (err.code === '23505') {
        syncDiag(`FIELD-LOG-INSERT CONFLICT (23505): ${tableName} row=${rowUuid} constraint=${err.constraint || 'unknown'} detail=${err.detail || 'none'} — attempting fallback UPDATE`);
        console.warn(
          `[FieldLogInsert] Unique constraint hit for ${tableName}.${rowUuid} — ` +
          `falling back to field-level UPDATE (constraint: ${err.constraint || 'unknown'})`
        );
        try {
          // Ensure meta is available for the fallback path
          if (!meta) meta = await getColumnMeta(pool, tableName);

          // Apply each field log as an UPDATE against the existing row.
          // Strategy: Parse PostgreSQL's error detail to extract the exact conflicting
          // column names and values, then use ONLY those for the lookup.
          // This avoids the old bug where using all non-null rowData fields failed because
          // the conflicting row had different values for non-constraint columns.
          const vesselScopeCol = config.vesselScopeColumn;
          const vesselIdVal = logs[0].vesselId;

          let existingIdentity: string | null = null;

          // Strategy 1: Parse PostgreSQL error detail to get exact conflict key
          // Format: "Key (col1, col2)=(val1, val2) already exists."
          const detailMatch = err.detail?.match(/Key \(([^)]+)\)=\(([^)]+)\)/);
          if (detailMatch) {
            const constraintCols = detailMatch[1].split(',').map((c: string) => c.trim());
            const constraintVals = detailMatch[2].split(',').map((v: string) => v.trim());
            syncDiag(`FIELD-LOG-INSERT CONFLICT LOOKUP: using constraint cols=[${constraintCols.join(',')}] vals=[${constraintVals.join(',')}]`);

            if (constraintCols.length > 0 && constraintCols.length === constraintVals.length) {
              const whereParts = constraintCols.map((col: string, i: number) => `"${col}" = $${i + 1}`);
              const lookupSQL = `SELECT "${identityCol}" FROM "${tableName}" WHERE ${whereParts.join(' AND ')} LIMIT 1`;
              const constraintResult = await pool.query(lookupSQL, constraintVals);
              if (constraintResult.rows.length > 0) {
                existingIdentity = constraintResult.rows[0][identityCol];
                syncDiag(`FIELD-LOG-INSERT CONFLICT FOUND: ${tableName} existing identity=${existingIdentity} via constraint columns`);
              }
            }
          }

          // Strategy 2 (fallback): vessel scope → single row or multi-field lookup
          if (!existingIdentity && vesselScopeCol && vesselIdVal) {
            const lookupResult = await pool.query(
              `SELECT "${identityCol}" FROM "${tableName}" WHERE "${vesselScopeCol}" = $1 LIMIT 2`,
              [vesselIdVal]
            );
            if (lookupResult.rows.length === 1) {
              existingIdentity = lookupResult.rows[0][identityCol];
              syncDiag(`FIELD-LOG-INSERT CONFLICT FOUND: ${tableName} existing identity=${existingIdentity} via single vessel-scope row`);
            } else {
              // Use only a few key columns from rowData — prefer columns likely in unique constraints
              const lookupCols: string[] = [];
              const lookupVals: any[] = [];
              let pIdx = 1;
              for (const [col, val] of Object.entries(rowData)) {
                if (col === identityCol || val === null || val === undefined) continue;
                if (['created_at', 'updated_at'].includes(col)) continue;
                lookupCols.push(`"${col}" = $${pIdx}`);
                lookupVals.push(val);
                pIdx++;
                if (pIdx > 5) break;
              }
              if (lookupCols.length > 0) {
                const lookupSQL = `SELECT "${identityCol}" FROM "${tableName}" WHERE ${lookupCols.join(' AND ')} LIMIT 1`;
                const specificResult = await pool.query(lookupSQL, lookupVals);
                if (specificResult.rows.length > 0) {
                  existingIdentity = specificResult.rows[0][identityCol];
                }
              }
            }
          }

          if (existingIdentity) {
            // Apply field-level updates to the existing row
            let fieldsApplied = 0;
            for (const log of logs) {
              const fieldSnake = fieldNameToColumn(log.fieldName);
              if (fieldSnake === identityCol || fieldSnake === 'created_at' || fieldSnake === 'updated_at') continue;
              if (meta.identityAlwaysCols.has(fieldSnake)) continue;
              if (meta.allCols.size > 0 && !meta.allCols.has(fieldSnake)) continue;
              if (log.newValue === null) continue;

              let valueToApply: any = log.newValue;
              if (meta.jsonCols.has(fieldSnake)) {
                try { JSON.parse(valueToApply); } catch { valueToApply = '[]'; }
              }

              try {
                const logTs = log.changedAt instanceof Date ? log.changedAt : (log.changedAt ? new Date(String(log.changedAt)) : new Date());
                await pool.query(
                  `UPDATE "${tableName}" SET "${fieldSnake}" = $1, "updated_at" = $3 WHERE "${identityCol}" = $2`,
                  [valueToApply, existingIdentity, logTs]
                );
                fieldsApplied++;
              } catch (updateErr: any) {
                // Best-effort per-field update
                console.warn(`[FieldLogInsert] Conflict fallback UPDATE failed for ${tableName}.${fieldSnake}: ${updateErr.message}`);
              }
            }

            // Converge identity: adopt the incoming rowUuid so future UPDATE logs
            // from the remote instance will match this row by its identity column.
            if (existingIdentity !== rowUuid) {
              try {
                await pool.query(
                  `UPDATE "${tableName}" SET "${identityCol}" = $1 WHERE "${identityCol}" = $2`,
                  [rowUuid, existingIdentity]
                );
                console.log(`[FieldLogInsert] Identity converged: ${tableName} "${identityCol}" ${existingIdentity} → ${rowUuid}`);
              } catch (convergeErr: any) {
                // Non-fatal — may fail if incoming rowUuid already exists (shouldn't happen)
                console.warn(`[FieldLogInsert] Identity convergence failed for ${tableName}: ${convergeErr.message}`);
              }
            }

            if (fieldsApplied > 0) {
              insertedRows++; // Count as successfully synced
              syncDiag(`FIELD-LOG-INSERT CONFLICT RESOLVED: ${tableName} row=${rowUuid} → updated ${fieldsApplied} fields on existing row (identity: ${existingIdentity}→${rowUuid})`);
              console.log(`[FieldLogInsert] Conflict resolved: updated ${fieldsApplied} fields on existing ${tableName} row (identity: ${existingIdentity})`);
            }
          } else {
            // Could not find conflicting row — log as error
            syncDiag(`FIELD-LOG-INSERT CONFLICT FAILED: ${tableName} row=${rowUuid} — could not locate existing row despite 23505 conflict`);
            errors.push(`${tableName}.${rowUuid}: unique constraint conflict but could not find existing row`);
            failedRowUuids.push(rowUuid);
          }
        } catch (fallbackErr: any) {
          errors.push(`${tableName}.${rowUuid}: conflict fallback failed: ${fallbackErr.message}`);
          failedRowUuids.push(rowUuid);
          console.error(`[FieldLogInsert] Conflict fallback error for ${tableName}.${rowUuid}:`, fallbackErr.message);
        }
      } else if (err.code === '23503') {
        // 23503 = foreign_key_violation — the row references a FK target that doesn't
        // exist on this instance. Common case: defect created on ship references a
        // component_id that was soft-deleted or not yet synced to shore.
        //
        // Strategy: Extract the offending column from the constraint name (convention:
        // tableName_columnName_targetTable_targetCol_fk), NULL it out, and retry INSERT.
        // The FK column is typically nullable. Future sync UPDATE logs will fill it in
        // once the referenced row arrives.
        const constraintName = err.constraint || '';
        syncDiag(`FIELD-LOG-INSERT FK-VIOLATION (23503): ${tableName} row=${rowUuid} constraint=${constraintName} — attempting NULL-FK retry`);

        // Parse column from constraint name: e.g. "defects_component_id_components_cuuid_fk"
        // Convention: <table>_<column>_<ref_table>_<ref_col>_fk
        let fkColumn: string | null = null;
        if (constraintName.startsWith(`${tableName}_`) && constraintName.endsWith('_fk')) {
          // Remove table prefix and _fk suffix, then take the first segment(s) before the ref table
          const inner = constraintName.slice(tableName.length + 1, -3); // e.g. "component_id_components_cuuid"
          // The FK column is everything before the last two segments (ref_table + ref_col)
          const parts = inner.split('_');
          // Try progressively: the FK column name could be 1 or 2 segments
          // e.g. "component_id" (2 segments) + "components" (1) + "cuuid" (1)
          for (let i = 1; i <= Math.min(3, parts.length - 2); i++) {
            const candidate = parts.slice(0, i).join('_');
            if (rowData[candidate] !== undefined) {
              fkColumn = candidate;
              break;
            }
          }
        }

        // Fallback: extract from error detail if constraint parsing fails
        if (!fkColumn && err.detail) {
          // Detail format: 'Key (component_id)=(some-uuid) is not present in table "components".'
          const detailMatch = err.detail.match(/Key \((\w+)\)=/);
          if (detailMatch) fkColumn = detailMatch[1];
        }

        if (fkColumn && rowData[fkColumn] !== undefined) {
          syncDiag(`FK-NULL RETRY: ${tableName} row=${rowUuid} — setting ${fkColumn}=NULL and retrying INSERT`);
          try {
            // Rollback to savepoint, null out the FK column, and retry
            if (externalClient) {
              try { await pool.query(`ROLLBACK TO SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
              try { await pool.query(`SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
            }

            rowData[fkColumn] = null;

            // Rebuild INSERT with nulled FK
            if (!meta) meta = await getColumnMeta(pool, tableName);
            const cols2: string[] = [];
            const phs2: string[] = [];
            const vals2: any[] = [];
            let pi2 = 1;
            for (const [col, val] of Object.entries(rowData)) {
              if (meta.identityAlwaysCols.has(col)) continue;
              cols2.push(`"${col}"`);
              phs2.push(`$${pi2}`);
              vals2.push(val instanceof Date ? val : val);
              pi2++;
            }

            const retrySQL = `INSERT INTO "${tableName}" (${cols2.join(', ')}) VALUES (${phs2.join(', ')}) ON CONFLICT ("${identityCol}") DO NOTHING`;
            await pool.query(retrySQL, vals2);
            insertedRows++;
            syncDiag(`FK-NULL RETRY OK: ${tableName} row=${rowUuid} — inserted with ${fkColumn}=NULL (will be filled by future sync)`);

            if (externalClient) {
              try { await pool.query(`RELEASE SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
            }
          } catch (retryErr: any) {
            if (externalClient) {
              try { await pool.query(`ROLLBACK TO SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
            }
            syncDiag(`FK-NULL RETRY FAIL: ${tableName} row=${rowUuid} — ${retryErr.message.substring(0, 150)}`);
            errors.push(`${tableName}.${rowUuid}: FK retry failed: ${retryErr.message}`);
            failedRowUuids.push(rowUuid);
          }
        } else {
          syncDiag(`FIELD-LOG-INSERT FK-VIOLATION: ${tableName} row=${rowUuid} — could not identify FK column from constraint=${constraintName}`);
          errors.push(`${tableName}.${rowUuid}: FK violation: ${err.message}`);
          failedRowUuids.push(rowUuid);
        }
      } else {
        // Recover the transaction so ONE bad row can't poison the whole pull batch (mirrors the
        // 23503 FK branch above). Without this, a 42703/any error leaves the tx aborted → every
        // later statement fails with 25P02 and COMMIT rolls back the entire pull.
        if (externalClient) {
          try { await pool.query(`ROLLBACK TO SAVEPOINT ${savepointName}`); } catch { /* non-fatal */ }
        }
        syncDiag(`FIELD-LOG-INSERT FAIL: ${tableName} row=${rowUuid} — ${err.message.substring(0, 150)}`);
        errors.push(`${tableName}.${rowUuid}: ${err.message}`);
        failedRowUuids.push(rowUuid);
        console.error(`[FieldLogInsert] Failed to insert ${tableName}.${rowUuid}:`, err.message);
      }
    }
  }

  syncDiag(`FIELD-LOG-INSERT DONE: inserted=${insertedRows}, updatePassthrough=${updateLogs.length}, errors=${errors.length}`);
  return { insertedRows, updateLogs, errors, failedRowUuids };
}
