/**
 * Single Source of Truth: Bulk Import Template Fields
 *
 * This file defines the canonical field specifications for each Bulk Data Import template.
 * The Field Mapping Guide in the admin UI reads directly from these definitions, so any
 * change here is automatically reflected in the guide without touching component files.
 *
 * Pattern mirrors shared/sparesTemplateFields.ts (Spares already uses that file).
 * Add new templates here as they are introduced.
 *
 * IMPORTANT: Field headers and order must exactly match the backend template generator.
 * Backend source: server/modules/bulk-upload/controllers/bulkController.ts (case 'components')
 *                 server/modules/bulk-upload/services/templateService.ts (Vessel_Component sheet)
 */

export interface BulkImportTemplateField {
  header: string;
  key: string;
  required: boolean;
  description: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// MACHINERY COMPONENTS
// 28 columns — exact order and headers as generated by the backend template
// Required: Component Code, Component Name, Component Category, Vessel Code
// ─────────────────────────────────────────────────────────────────────────────

export const MACHINERY_COMPONENT_TEMPLATE_FIELDS: BulkImportTemplateField[] = [
  { header: 'Fleet Equipment Code',           key: 'fleetEquipmentCode',      required: false, description: 'Reference to fleet master equipment (XXX.XXX.XX format)' },
  { header: 'Fleet Equipment Name',           key: 'fleetEquipmentName',      required: false, description: 'Fleet equipment description' },
  { header: 'Parent Component Code',          key: 'parentComponentCode',     required: false, description: 'Parent SFI code — leave blank for top-level components' },
  { header: 'Component Code',                 key: 'componentCode',           required: true,  description: 'Unique SFI format identifier (e.g., XXX.XXX)' },
  { header: 'Component Name',                 key: 'componentName',           required: true,  description: 'Equipment name' },
  { header: 'Component Category',             key: 'componentCategory',       required: true,  description: 'SFI category name' },
  { header: 'Maker',                          key: 'maker',                   required: false, description: 'Manufacturer name' },
  { header: 'Maker Code',                     key: 'makerCode',               required: false, description: 'Maker ID from the Maker List' },
  { header: 'Model',                          key: 'model',                   required: false, description: 'Model name' },
  { header: 'Model Code',                     key: 'modelCode',               required: false, description: 'Model code' },
  { header: 'Serial No',                      key: 'serialNo',                required: false, description: 'Serial number' },
  { header: 'Drawing No',                     key: 'drawingNo',               required: false, description: 'Drawing reference' },
  { header: 'Location',                       key: 'location',                required: false, description: 'Physical location on the vessel' },
  { header: 'Criticality',                    key: 'criticality',             required: false, description: 'Yes or No' },
  { header: 'Condition Based',                key: 'conditionBased',          required: false, description: 'Yes or No' },
  { header: 'Installation Date',              key: 'installationDate',        required: false, description: 'Date format: DD-MMM-YYYY' },
  { header: 'Commissioned Date',              key: 'commissionedDate',        required: false, description: 'Date format: DD-MMM-YYYY' },
  { header: 'Rating',                         key: 'rating',                  required: false, description: 'Capacity or specification' },
  { header: 'Equipment / System Department',  key: 'equipmentDepartment',     required: false, description: 'Engine / Deck / Electrical' },
  { header: 'Class item',                     key: 'classItem',               required: false, description: 'Yes or No' },
  { header: 'IS Active',                      key: 'isActive',                required: false, description: 'Yes or No' },
  { header: 'Vessel Code',                    key: 'vesselCode',              required: true,  description: 'Vessel identification code (e.g., V001)' },
  { header: 'IS Parent',                      key: 'isParent',                required: false, description: 'Yes or No — marks top-level components' },
  { header: 'Notes',                          key: 'notes',                   required: false, description: 'Additional notes' },
  { header: 'RH Counter Type',               key: 'rhCounterType',           required: false, description: 'MASTER / INHERITED / NOT_RH_DRIVEN' },
  { header: 'RH Counter Source',             key: 'rhCounterSource',         required: false, description: 'Component code that is the running hours source' },
  { header: 'Running Hours',                  key: 'runningHours',            required: false, description: 'Numeric value, must be ≥ 0' },
  { header: 'Last Updated',                   key: 'lastUpdated',             required: false, description: 'Timestamp text' },
];

/**
 * Returns the field mappings array expected by the UniformBulkUpload fieldMappings prop.
 */
export function getMachineryComponentFieldMappings() {
  return MACHINERY_COMPONENT_TEMPLATE_FIELDS.map(f => ({
    field: f.header,
    required: f.required,
    description: f.description,
  }));
}
