export const POSTPONEMENT_REASONS = [
  "Awaiting spare parts onboard.",
  "Required consumables unavailable.",
  "Vessel in port operations.",
  "Vessel in transit.",
  "Vessel under pilotage / manoeuvring.",
  "Rough weather / adverse sea conditions.",
  "Operationally critical equipment in continuous use.",
  "Job postponed due to operational priority.",
  "Dry dock / repair window awaited.",
  "Riding squad / technician required.",
  "Maker's service engineer required.",
  "Shore assistance required.",
  "Class / flag / owner attendance awaited.",
  "Permit to work not available.",
  "Machinery shutdown opportunity not available.",
  "Main engine stoppage not available.",
  "Equipment isolation not possible.",
  "Cargo operations in progress.",
  "Bunkering operations in progress.",
  "Tank cleaning / gas-freeing in progress.",
  "Inspection / audit preparations in progress.",
  "Vessel staff workload / manpower limitation.",
  "Work in progress, not yet completed.",
  "Shore management instruction awaited.",
  "Dry dock / next port planning.",
  "To be carried out at next suitable opportunity.",
  "To be carried out during voyage leg.",
  "To be carried out during harbour stay.",
] as const;

export type PostponementReason = typeof POSTPONEMENT_REASONS[number];
