/**
 * Sync Configuration — Central source of truth for ship-shore synchronization
 *
 * Every table in the database is classified into one of 4 sync categories:
 * - ONE_WAY_SHORE_TO_SHIP: Shore is master. Ship receives overwrites. No conflict possible.
 * - BOTH_EDITABLE: Both sides can edit. Field-level merge with conflict detection via sync_field_log.
 * - SHIP_ONLY: Ship is master. Shore receives overwrites.
 * - NO_SYNC: Never synced. Instance-local only.
 *
 * Domain expert sign-off: Jeevan Naik, Rahul Singh Sisodiya, Sahil Puri (24-Apr-2026)
 *
 * This file provides CODE-LEVEL defaults. A future admin UI will allow database-level
 * overrides via sync_table_config table. Tables marked isConfigurable: true can be
 * reclassified via the admin UI without code changes.
 */

export type SyncDirection = 'shore_to_ship' | 'ship_to_shore' | 'bidirectional' | 'none';

export type SyncCategory = 'ONE_WAY_SHORE_TO_SHIP' | 'BOTH_EDITABLE' | 'SHIP_ONLY' | 'NO_SYNC';

export interface TableSyncConfig {
  /** Database table name (snake_case as in PostgreSQL) */
  tableName: string;
  /** Sync category */
  category: SyncCategory;
  /** Sync direction */
  direction: SyncDirection;
  /** UUID identity column name for cross-instance row identity (e.g., 'wouuid', 'duuid') */
  identityColumn: string | null;
  /** Column used to scope data to a specific vessel (e.g., 'vessel_id', 'vessel_code') */
  vesselScopeColumn: string | null;
  /** If vesselScopeColumn is null, how to resolve vessel scope via FK join */
  vesselScopeJoinPath: string | null;
  /** Whether this table is global (not vessel-specific, e.g., ranks, master data) */
  isGlobal: boolean;
  /** Whether this classification can be overridden via the future admin UI */
  isConfigurable: boolean;
  /** Business rules for sync (e.g., field-level restrictions) */
  businessRules: string | null;
  /** Brief description of why this classification was chosen */
  notes: string;
  /**
   * True ONLY for tables that carry a DB immutability trigger (INSERT-only; a BEFORE UPDATE
   * trigger hard-rejects modifications, e.g. component_maintenance_history). The field-log
   * appliers use this to ACK a re-delivered INSERT-origin log whose row already exists on the
   * receiver instead of issuing the forbidden UPDATE (which would raise and poison the batch).
   * Do NOT set this on ordinary tables — it must mirror an actual trigger.
   */
  immutable?: boolean;
}

// ════════════════════════════════════════════════════════════════════════════════
// SYNC_CONFIG — keyed by table name
// ════════════════════════════════════════════════════════════════════════════════

export const SYNC_CONFIG: Record<string, TableSyncConfig> = {

  // ══════════════════════════════════════════════════════════════════════════════
  // ONE_WAY_SHORE_TO_SHIP — Office is master, ship receives read-only copies
  // ══════════════════════════════════════════════════════════════════════════════

  // ── PMS Core: Components & Jobs ──

  components: {
    tableName: 'components',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'cuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Component tree structure managed by office. Ship reads only.',
  },
  jobs: {
    tableName: 'jobs',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'juuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: 'Ship can request changes via Modify PMS (change_request) but cannot edit jobs directly',
    notes: 'Job definitions managed by office. Ship uses change_request for modifications.',
  },
  job_component_links: {
    tableName: 'job_component_links',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Job-component associations managed by office. Integer PK, no UUID identity.',
  },

  // ── Fleet Management ──

  fleet_components: {
    tableName: 'fleet_components',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fleet_components_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-level component templates. Global, office-managed.',
  },
  fleet_jobs: {
    tableName: 'fleet_jobs',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fleet_jobs_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-level job templates. Global, office-managed.',
  },
  fleet_spares: {
    tableName: 'fleet_spares',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fleet_spares_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-level spare templates. Global, office-managed.',
  },
  fleet_vessel_mapping: {
    tableName: 'fleet_vessel_mapping',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Vessel-to-fleet assignment. Integer PK, no UUID.',
  },
  fleet_component_mapping: {
    tableName: 'fleet_component_mapping',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-to-vessel component mapping. Integer PK, no UUID.',
  },
  fleet_job_vessel_mapping: {
    tableName: 'fleet_job_vessel_mapping',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-to-vessel job mapping. Integer PK, no UUID.',
  },
  fleet_spare_vessel_mapping: {
    tableName: 'fleet_spare_vessel_mapping',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet-to-vessel spare mapping. Integer PK, no UUID.',
  },
  fleet_groups: {
    tableName: 'fleet_groups',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet group definitions. Text PK (id), no UUID identity.',
  },
  fleet_classes: {
    tableName: 'fleet_classes',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fcuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fleet class definitions. Global, office-managed.',
  },

  // ── Admin & Org Chart ──

  adm_available_ranks: {
    tableName: 'adm_available_ranks',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'ar_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Rank definitions. Global reference data.',
  },
  vessel_org_chart_nodes: {
    tableName: 'vessel_org_chart_nodes',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'node_uuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Vessel-specific org chart nodes, provisioned from office.',
  },
  adm_vessel_org_chart: {
    tableName: 'adm_vessel_org_chart',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'oc_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Global org chart template. No vessel scope — applied per-vessel via vessel_org_chart_nodes.',
  },
  vessel_department_config: {
    tableName: 'vessel_department_config',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Vessel department configuration. Integer PK, no UUID.',
  },
  admn_role_master: {
    tableName: 'admn_role_master',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'ruid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Role definitions. ruid is the text identity column.',
  },
  adm_menumaster_ac: {
    tableName: 'adm_menumaster_ac',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'muid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Menu definitions. muid is the text identity column.',
  },
  adm_role_menu_access: {
    tableName: 'adm_role_menu_access',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Role-menu access mapping. Integer PK (generatedAlways), no UUID.',
  },

  // ── Reference / Master Data ──

  equipment_categories: {
    tableName: 'equipment_categories',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'name',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Equipment category definitions. Integer PK, no UUID.',
  },
  sfi_details: {
    tableName: 'sfi_details',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'component_code',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'SFI group/code reference data. Integer PK, no UUID.',
  },
  master_data: {
    tableName: 'master_data',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fleet_equipment_code',
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Vessel master data (DWT, type, etc.). Uses vessel_code, not vessel_id.',
  },
  defect_categories: {
    tableName: 'defect_categories',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'name',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Defect category definitions. Integer PK, no UUID.',
  },
  defect_types: {
    tableName: 'defect_types',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'name',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Defect type definitions. Integer PK, no UUID.',
  },
  makers: {
    tableName: 'makers',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'maker_code',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Maker/manufacturer directory. Integer PK, no UUID. Uses maker_code as natural key.',
  },
  maker_list: {
    tableName: 'maker_list',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'maker_list_uuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Maker list (component-maker associations). Global reference data.',
  },
  master_list_types: {
    tableName: 'master_list_types',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'mltuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Master list type registry (dropdown categories). Global.',
  },
  master_lists: {
    tableName: 'master_lists',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Master list values (dropdown options). Integer PK, no UUID.',
  },

  // ── Forms ──

  form_definitions: {
    tableName: 'form_definitions',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fduuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Form builder definitions. Global, office-managed.',
  },
  form_versions: {
    tableName: 'form_versions',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'fvuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Form version snapshots. Global, office-managed.',
  },

  // ── Alerts & Settings ──

  alert_policies: {
    tableName: 'alert_policies',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'apuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Alert policy definitions. Global configuration.',
  },
  alert_config: {
    tableName: 'alert_config',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Per-vessel alert configuration (quiet hours, escalation). Integer PK, no UUID.',
  },
  company_standard_grace_settings: {
    tableName: 'company_standard_grace_settings',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'singleton_key',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Company-wide grace period settings. Single-row global config. Integer PK, no UUID.',
  },
  company_approval_settings: {
    tableName: 'company_approval_settings',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'singleton_key',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Company approval policy (superintendent lock toggle, migration 137). Single-row global config, shore-configured. Integer PK, no UUID.',
  },
  pms_vessel_settings: {
    tableName: 'pms_vessel_settings',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'vessel_id',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Per-vessel PMS settings (lead times, grace periods). Integer PK, no UUID.',
  },

  // ── Certificates & Surveys (Master / Config) ──

  ship_certificates_master: {
    tableName: 'ship_certificates_master',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'master_id',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Master list of certificate types. Integer PK, no UUID.',
  },
  ship_certificates_labels_config: {
    tableName: 'ship_certificates_labels_config',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Certificate label configuration. Integer PK, no UUID.',
  },
  ship_surveys_master: {
    tableName: 'ship_surveys_master',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'master_id',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Master list of survey types. Integer PK, no UUID.',
  },
  ship_surveys_labels_config: {
    tableName: 'ship_surveys_labels_config',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Survey label configuration. Integer PK, no UUID.',
  },
  vessel_certificate_applicability: {
    tableName: 'vessel_certificate_applicability',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Which certificates apply to which vessels. Integer PK, no UUID.',
  },
  vessel_survey_applicability: {
    tableName: 'vessel_survey_applicability',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Which surveys apply to which vessels. Integer PK, no UUID.',
  },

  // ── Class / Regulatory ──

  component_class_regulatory: {
    tableName: 'component_class_regulatory',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Class/regulatory data for components. Uses vessel_code. Integer PK, no UUID.',
  },

  // ── Approval workflow: office-managed config + approver registry (global) ──

  approval_workflow_config: {
    tableName: 'approval_workflow_config',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'awcuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: true,
    businessRules: 'Approval level config is office-managed; ships read-only.',
    notes: 'Per-function Level1/Level2 enable flags. Global, shore-mastered. SEEDED ON BOTH SIDES by migration 126 with per-instance awcuuid — applyOneWayRows matches it by natural key (function_id, variable_name) via FORCE_COMPOSITE (permanently: the seeded row keeps its local awcuuid; identity matching would 23505 on the natural unique every cycle). Provisioning import pre-clears local rows when the bundle carries this table, so fresh ships DO take shore awcuuids.',
  },
  moc_approvers: {
    tableName: 'moc_approvers',
    category: 'ONE_WAY_SHORE_TO_SHIP',
    direction: 'shore_to_ship',
    identityColumn: 'mauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: true,
    businessRules: 'Approver master is office-managed; ships read-only.',
    notes: 'Approvers (Level1/Level2 per module), refreshed shore-side by Sync-All (soft-delete-all + re-insert, both stamped). Global, shore-mastered.',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // BOTH_EDITABLE — Both ship & office can edit, requires field-level change logging
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Work Orders ──

  work_orders: {
    tableName: 'work_orders',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'wouuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Core work order records. Both ship and office create/update.',
  },
  work_order_executions: {
    tableName: 'work_order_executions',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'WO execution records. Text PK (id), no UUID identity column.',
  },
  work_order_execution_details: {
    tableName: 'work_order_execution_details',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'woeduuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'WO execution detail records.',
  },
  work_order_postponements: {
    tableName: 'work_order_postponements',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'id',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'WO postponement records. Text PK (id) IS the sync identity — app-generated unique (pp-<wo>-<ts>/randomUUID) + gen_random_uuid default (migration 133). Explicit identityColumn (engine previously fell back to id).',
  },
  wo_postponement_approvals: {
    tableName: 'wo_postponement_approvals',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'wpauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'wo_postponement_approvals.postponement_id -> work_order_postponements.id -> work_order_postponements.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: 'Ship creates approval steps on submit; office updates status on approve/reject.',
    notes: 'WO postponement approval steps. Vessel scope resolved via parent work_order_postponements FK (write paths stamp parent vessel_id into field logs). postponement_id is TEXT and carries verbatim cross-instance (no remap needed). Phase 4 AFTER work_order_postponements (real FK).',
  },
  work_order_documents: {
    tableName: 'work_order_documents',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'WO attached documents. Text PK (id), no UUID identity column.',
  },

  // ── Defects ──

  defects: {
    tableName: 'defects',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'duuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: 'Ship can Close (C1 Closeout). Only Office can Verify (C2 Verification). Sync engine must enforce: status=verified only accepted from shore instance.',
    notes: 'Defect records with C1/C2 closeout workflow.',
  },
  defect_actions: {
    tableName: 'defect_actions',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'dauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'defect_actions.defect_id -> defects.duuid -> defects.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Defect corrective actions. Vessel scope resolved via parent defect FK.',
  },
  defect_attachments: {
    tableName: 'defect_attachments',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'datuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'defect_attachments.defect_id -> defects.duuid -> defects.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Defect file attachments. Vessel scope resolved via parent defect FK.',
  },
  defect_sequences: {
    tableName: 'defect_sequences',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: 'Both sides generate sequences. Use instance_id prefix to avoid collision (ship: V-prefix, shore: O-prefix)',
    notes: 'DOMAIN EXPERT CORRECTION: Changed from SHIP_ONLY to BOTH_EDITABLE. Office can also generate defect reports. Integer PK, no UUID.',
  },

  // ── Spares & Inventory ──

  spares: {
    tableName: 'spares',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'suuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Spare parts inventory. Both sides can update ROB, receive, consume.',
  },
  spares_history: {
    tableName: 'spares_history',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'shuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Spare parts transaction history.',
  },
  spare_location_stock: {
    tableName: 'spare_location_stock',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'slsuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Per-location spare stock levels.',
  },
  spare_component_links: {
    tableName: 'spare_component_links',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'scluuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Spare-to-component associations.',
  },
  stores_items: {
    tableName: 'stores_items',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'stuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Stores/consumables inventory.',
  },
  stores_ledger: {
    tableName: 'stores_ledger',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'sluuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Stores transaction ledger.',
  },
  inventory_transactions: {
    tableName: 'inventory_transactions',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'ituuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Inventory transaction records (consume, receive, adjust, transfer).',
  },

  // ── Change Requests (Modify PMS) ──

  change_request: {
    tableName: 'change_request',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'cruuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Modify PMS change requests. Ship submits, office reviews.',
  },
  change_request_attachment: {
    tableName: 'change_request_attachment',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'crauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'change_request_attachment.change_request_id -> change_request.id -> change_request.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'CR attachments. Vessel scope resolved via parent change_request FK.',
  },
  change_request_approval: {
    tableName: 'change_request_approval',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'crauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'change_request_approval.change_request_id -> change_request.id -> change_request.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: 'Ship creates approval steps on submit; office updates status on approve/reject.',
    notes: 'CR approval steps. Vessel scope resolved via parent change_request FK (write paths stamp parent vessel_id into field logs). crauuid identity is table-scoped (shared name with change_request_attachment is safe — engine keys by table_name+value). change_request_id is a per-instance INTEGER: the applier remaps it from change_request_uuid post-INSERT (wrong-parent guard).',
  },
  change_request_comment: {
    tableName: 'change_request_comment',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'crcuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: 'change_request_comment.change_request_id -> change_request.id -> change_request.vessel_id',
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'CR comments. Vessel scope resolved via parent change_request FK.',
  },

  // ── Certificates & Surveys (Data) ──

  certificates: {
    tableName: 'certificates',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Certificate records. Text PK (id), no UUID identity column.',
  },
  surveys: {
    tableName: 'surveys',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Survey records. Text PK (id), no UUID identity column.',
  },
  vessel_certificate_data: {
    tableName: 'vessel_certificate_data',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'vcduuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Vessel-specific certificate data and dates.',
  },
  vessel_survey_data: {
    tableName: 'vessel_survey_data',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'vsduuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Vessel-specific survey data and dates.',
  },

  // ── Running Hours & Maintenance History ──

  running_hours_audit: {
    tableName: 'running_hours_audit',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'rhauuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Running hours audit trail entries.',
  },
  component_running_hours_log: {
    tableName: 'component_running_hours_log',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'crhluuid',
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Component RH log entries. Uses vessel_code not vessel_id — sync engine must map via vessel lookup.',
  },
  component_maintenance_history: {
    tableName: 'component_maintenance_history',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'cmhuuid',
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    immutable: true,
    notes: 'Component maintenance history. Uses vessel_code. Insert-only immutable table — UPDATE trigger (prevent_maintenance_history_update) hard-blocks modifications; immutable:true makes the field-log appliers ACK a re-delivered existing row instead of issuing the forbidden UPDATE.',
  },

  // ── Component Documents & Requisitions ──

  component_documents: {
    tableName: 'component_documents',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Component-attached documents. Uses vessel_code. Integer PK, no UUID.',
  },
  component_requisitions: {
    tableName: 'component_requisitions',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Component spare requisitions. Uses vessel_code. Integer PK, no UUID.',
  },

  // ── IHM (Inventory of Hazardous Materials) ──

  ihm_items: {
    tableName: 'ihm_items',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'IHM items. Integer PK, no UUID.',
  },
  ihm_maintenance_log: {
    tableName: 'ihm_maintenance_log',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'IHM maintenance log. Integer PK, no UUID.',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // SHIP_ONLY — Ship is master, shore receives overwrites
  // ══════════════════════════════════════════════════════════════════════════════

  nr_noon_reports: {
    tableName: 'nr_noon_reports',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nruuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Noon reports. Ship-generated operational data.',
  },
  nr_bunker_records: {
    tableName: 'nr_bunker_records',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nbruuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Bunkering delivery records. Ship-generated.',
  },
  nr_alerts: {
    tableName: 'nr_alerts',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nauuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Noon report threshold alerts. Ship-generated.',
  },
  nr_cii_tracking: {
    tableName: 'nr_cii_tracking',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nctuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Year-to-date CII tracking per vessel. Ship-generated.',
  },
  nr_fuel_rob: {
    tableName: 'nr_fuel_rob',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nfruuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Fuel ROB per vessel per fuel type. Ship-generated.',
  },
  nr_voyage_legs: {
    tableName: 'nr_voyage_legs',
    category: 'SHIP_ONLY',
    direction: 'ship_to_shore',
    identityColumn: 'nvluuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Voyage leg tracking. Ship-generated.',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // NO_SYNC — Never synced, instance-local only
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Platform-provisioned (managed by SAILERP, not PMS sync engine) ──

  users: {
    tableName: 'users',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Managed by SAILERP platform, provisioned separately.',
  },
  master_users: {
    tableName: 'master_users',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Managed by SAILERP platform. Text PK.',
  },
  vessels: {
    tableName: 'vessels',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'vuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Provisioned from SAILERP, not synced by PMS.',
  },
  fleets: {
    tableName: 'fleets',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'fuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Provisioned from SAILERP. Text PK.',
  },
  vessel_types: {
    tableName: 'vessel_types',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Provisioned from SAILERP. Text PK.',
  },
  additional_groups: {
    tableName: 'additional_groups',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Provisioned from SAILERP. Text PK.',
  },
  ports: {
    tableName: 'ports',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Provisioned from SAILERP. Text PK.',
  },
  locations: {
    tableName: 'locations',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'luuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'Location registry. Integer PK + UUID sync key (luuid). FK target for spare_location_stock.location_id and inventory_transactions.location_id — both have companion location_uuid column for cross-instance FK resolution.',
  },

  // ── Sync engine internal tables (future — will be created in next task) ──

  sync_metadata: {
    tableName: 'sync_metadata',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'FUTURE TABLE. Sync engine internal tracking — sync cursors and state.',
  },
  sync_field_log: {
    tableName: 'sync_field_log',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'FUTURE TABLE. Field-level change log for BOTH_EDITABLE tables.',
  },
  sync_conflicts: {
    tableName: 'sync_conflicts',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'FUTURE TABLE. Conflict records for manual resolution.',
  },
  sync_file_queue: {
    tableName: 'sync_file_queue',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'FUTURE TABLE. File attachment sync queue.',
  },
  sync_batches: {
    tableName: 'sync_batches',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'FUTURE TABLE. Sync batch tracking.',
  },

  // ── Local audit / import / reporting ──

  audit_log: {
    tableName: 'audit_log',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local audit trail per instance.',
  },
  import_history: {
    tableName: 'import_history',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local import tracking.',
  },
  import_change_log: {
    tableName: 'import_change_log',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local import change tracking.',
  },
  bulk_import_history: {
    tableName: 'bulk_import_history',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'biuuid',
    vesselScopeColumn: 'vessel_code',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local bulk import tracking.',
  },
  bulk_import_errors: {
    tableName: 'bulk_import_errors',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local bulk import errors.',
  },
  report_snapshots: {
    tableName: 'report_snapshots',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Locally generated report data.',
  },
  report_favorites: {
    tableName: 'report_favorites',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'rfuuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local user report preferences.',
  },
  monthly_snapshots: {
    tableName: 'monthly_snapshots',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Locally generated monthly reports.',
  },
  superintendent_notifications: {
    tableName: 'superintendent_notifications',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'snuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: true,
    businessRules: null,
    notes: 'WO approval-tier notifications. Ship creates, shore acknowledges.',
  },

  // ── Local alert state ──

  alert_events: {
    tableName: 'alert_events',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'aeuuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local alert state. Alerts are computed per-instance from synced data.',
  },
  alert_deliveries: {
    tableName: 'alert_deliveries',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local alert delivery tracking. Integer PK, no UUID.',
  },
  alert_acknowledgements: {
    tableName: 'alert_acknowledgements',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: 'aauuid',
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local alert acknowledgements.',
  },

  // ── Local computation / planning ──

  work_order_anomalies: {
    tableName: 'work_order_anomalies',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: null,
    notes: 'Locally computed anomaly detection. Serial PK, no UUID.',
  },
  planner_dates: {
    tableName: 'planner_dates',
    category: 'BOTH_EDITABLE',
    direction: 'bidirectional',
    identityColumn: 'pduuid',
    vesselScopeColumn: 'vessel_id',
    vesselScopeJoinPath: null,
    isGlobal: false,
    isConfigurable: false,
    businessRules: 'Shore sets planned maintenance dates, ship can adjust. Field-level merge.',
    notes: 'Maintenance planner dates synced bidirectionally between shore and ship.',
  },
  schema_migrations: {
    tableName: 'schema_migrations',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Migration tracking — local to each DB instance.',
  },
  form_version_usage: {
    tableName: 'form_version_usage',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Local form analytics.',
  },
  recurring_defects: {
    tableName: 'recurring_defects',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Auto-computed aggregation from defect data.',
  },
  recurring_defect_links: {
    tableName: 'recurring_defect_links',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Auto-computed linking from defect data.',
  },
  shipskart_role_mappings: {
    tableName: 'shipskart_role_mappings',
    category: 'NO_SYNC',
    direction: 'none',
    identityColumn: null,
    vesselScopeColumn: null,
    vesselScopeJoinPath: null,
    isGlobal: true,
    isConfigurable: false,
    businessRules: null,
    notes: 'Shipskart SSO role mapping (SAIL role → Shipskart role). Shore-only office feature — ships have no Shipskart config; per-tenant by db-per-tenant construction. Register ONE_WAY_SHORE_TO_SHIP later only if ships ever need Purchasing.',
  },
};

// ════════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ════════════════════════════════════════════════════════════════════════════════

/** Get all tables in a specific sync category */
export function getTablesByCategory(category: SyncCategory): TableSyncConfig[] {
  return Object.values(SYNC_CONFIG).filter(t => t.category === category);
}

/** Get sync config for a specific table */
export function getTableSyncConfig(tableName: string): TableSyncConfig | undefined {
  return SYNC_CONFIG[tableName];
}

/** Check if a table requires field-level change logging */
export function requiresFieldLogging(tableName: string): boolean {
  const config = SYNC_CONFIG[tableName];
  return config?.category === 'BOTH_EDITABLE';
}

/** Get the identity column for a table (used for sync_field_log.row_uuid) */
export function getIdentityColumn(tableName: string): string | null {
  return SYNC_CONFIG[tableName]?.identityColumn ?? null;
}

/** Get all configurable tables (for future admin UI) */
export function getConfigurableTables(): TableSyncConfig[] {
  return Object.values(SYNC_CONFIG).filter(t => t.isConfigurable);
}

/** Get all table names that need to be included in vessel provisioning */
export function getProvisioningTables(): TableSyncConfig[] {
  return Object.values(SYNC_CONFIG).filter(t => t.category !== 'NO_SYNC');
}

/** Get tables with business rules that sync engine must enforce */
export function getTablesWithBusinessRules(): TableSyncConfig[] {
  return Object.values(SYNC_CONFIG).filter(t => t.businessRules !== null);
}

/** Get the 6-phase sync order (parent tables before children, respecting FK dependencies) */
export function getSyncPhaseOrder(): string[][] {
  return [
    // Phase 1: Global reference data (no vessel FK, no parent FK)
    getTablesByCategory('ONE_WAY_SHORE_TO_SHIP')
      .filter(t => t.isGlobal)
      .map(t => t.tableName),
    // Phase 2: Vessel-scoped reference data (has vessel FK but is office-managed)
    getTablesByCategory('ONE_WAY_SHORE_TO_SHIP')
      .filter(t => !t.isGlobal)
      .map(t => t.tableName),
    // Phase 3: Primary BOTH_EDITABLE entities (parent rows)
    ['work_orders', 'defects', 'spares', 'stores_items', 'change_request',
     'certificates', 'surveys', 'vessel_certificate_data', 'vessel_survey_data',
     'running_hours_audit', 'component_running_hours_log',
     'component_maintenance_history', 'ihm_items', 'defect_sequences',
     'planner_dates', 'locations'],
    // Phase 4: Child entities (FK to parent rows in Phase 3)
    ['work_order_executions', 'work_order_execution_details', 'work_order_postponements',
     // wo_postponement_approvals has a REAL FK to work_order_postponements(id) —
     // it must import strictly AFTER its parent (migration 129).
     'wo_postponement_approvals',
     'work_order_documents', 'defect_actions', 'defect_attachments',
     'spares_history', 'spare_location_stock', 'spare_component_links',
     'stores_ledger', 'inventory_transactions',
     'change_request_attachment', 'change_request_comment', 'change_request_approval',
     'ihm_maintenance_log', 'component_documents', 'component_requisitions',
     'superintendent_notifications'],
    // Phase 5: SHIP_ONLY tables
    getTablesByCategory('SHIP_ONLY').map(t => t.tableName),
    // Phase 6: Files (processed after all field data synced)
    [], // File sync handled separately via sync_file_queue
  ];
}
