import { storage } from "../storage";
import type { WorkOrder, InsertWorkOrder, WorkOrderExecution, InsertWorkOrderExecution, Job, PmsVesselSettings } from "@shared/schema";
import { computeWorkOrderStatus } from "@shared/workOrders/status";
import { shouldGenerateWorkOrder } from "@shared/dateUtils";
import { generatePlannedWorkOrderNumber, generateUnplannedWorkOrderNumber } from "../utils/workOrderNumbering";
import { jobService } from "./jobService";

/**
 * Determine if a job is "critical" based on its jobPriority
 * Critical and High priority jobs are considered critical for lead time purposes
 */
function isJobCritical(job: Job): boolean {
  const priority = job.jobPriority?.toLowerCase() || '';
  return priority === 'critical' || priority === 'high';
}

/**
 * Get the appropriate calendar lead time in days for a job based on its priority
 */
function getCalendarLeadDays(job: Job, settings: PmsVesselSettings | null | undefined): number {
  if (!settings) return 0; // No settings configured, use 0 lead time
  return isJobCritical(job) 
    ? settings.calendarLeadDaysCritical 
    : settings.calendarLeadDaysNonCritical;
}

/**
 * Get the appropriate RH lead time in hours for a job based on its priority
 */
function getRhLeadHours(job: Job, settings: PmsVesselSettings | null | undefined): number {
  if (!settings) return 0; // No settings configured, use 0 lead time
  return isJobCritical(job)
    ? settings.rhLeadHoursCritical
    : settings.rhLeadHoursNonCritical;
}

/**
 * Work Order Service
 * Handles all business logic related to work order execution records
 * Separated from routes for better maintainability
 */

export class WorkOrderService {
  /**
   * Get all work orders with optional vessel filter and computed status
   */
  async getWorkOrders(vesselId?: string): Promise<WorkOrder[]> {
    const workOrders = await storage.getWorkOrders(vesselId);
    
    // Augment each work order with computed status
    return workOrders.map(wo => ({
      ...wo,
      computedStatus: computeWorkOrderStatus({
        dueDate: wo.dueDate,
        dueRH: (wo as any).dueRH || null,
        currentRH: null, // Will need component data for RH status - enhance in future
        isExecution: wo.isExecution,
        status: wo.status,
        completionDateTime: wo.dateCompleted,
        maintenanceBasis: wo.maintenanceBasis || undefined
      })
    }));
  }

  /**
   * Get a single work order by ID
   */
  async getWorkOrder(id: string): Promise<WorkOrder | undefined> {
    return storage.getWorkOrder(id);
  }

  /**
   * Create a new work order
   */
  async createWorkOrder(workOrderData: InsertWorkOrder): Promise<WorkOrder> {
    // Validate required fields
    if (!workOrderData.vesselId) {
      throw new Error('Vessel ID is required');
    }
    
    if (!workOrderData.jobTitle) {
      throw new Error('Job title is required');
    }

    // Work order number should already be generated by the caller using the appropriate utility
    // If not provided for some reason (unplanned WO), generate unplanned format
    if (!workOrderData.workOrderNo) {
      workOrderData.workOrderNo = await generateUnplannedWorkOrderNumber(storage, workOrderData.vesselId);
      workOrderData.templateCode = workOrderData.workOrderNo;
    }

    return storage.createWorkOrder(workOrderData);
  }

  /**
   * Update an existing work order
   */
  async updateWorkOrder(id: string, updates: Partial<InsertWorkOrder>): Promise<WorkOrder> {
    return storage.updateWorkOrder(id, updates);
  }

  /**
   * Delete a work order
   */
  async deleteWorkOrder(id: string): Promise<void> {
    return storage.deleteWorkOrder(id);
  }

  /**
   * Get work order execution data
   */
  async getWorkOrderExecution(workOrderId: string): Promise<WorkOrderExecution | undefined> {
    const executions = await storage.getWorkOrderExecutions();
    return executions.find(exec => exec.workOrderId === workOrderId);
  }

  /**
   * Create work order execution record
   */
  async createWorkOrderExecution(executionData: InsertWorkOrderExecution): Promise<WorkOrderExecution> {
    return storage.createWorkOrderExecution(executionData);
  }

  /**
   * Update work order execution record
   */
  async updateWorkOrderExecution(id: string, updates: Partial<InsertWorkOrderExecution>): Promise<WorkOrderExecution> {
    return storage.updateWorkOrderExecution(id, updates);
  }

  /**
   * Auto-generate work orders from due jobs (Calendar-based)
   * Now properly applies configured vessel lead times for proactive WO generation
   * Returns statistics about how many work orders were generated
   */
  async autoGenerateWorkOrdersFromJobs(vesselId?: string): Promise<{
    checked: number;
    generated: number;
    workOrders: WorkOrder[];
  }> {
    // Get ALL Calendar-based jobs (not just due ones - we apply lead time in the loop)
    const allJobs = await jobService.getJobs(vesselId);
    const calendarJobs = allJobs.filter(job => 
      job.maintenanceBasis === 'Calendar' && 
      job.nextDueDate
    );
    
    // Fetch vessel PMS settings for lead time configuration
    // Cache settings by vesselId to avoid repeated fetches
    const settingsCache = new Map<string, PmsVesselSettings | null>();
    const getSettingsForVessel = async (vId: string | null): Promise<PmsVesselSettings | null> => {
      if (!vId) return null;
      if (settingsCache.has(vId)) return settingsCache.get(vId) || null;
      const settings = await storage.getPmsVesselSettings(vId);
      settingsCache.set(vId, settings || null);
      return settings || null;
    };
    
    // Get all active work orders to prevent duplicates
    // Key includes vesselId to prevent cross-vessel collision
    const allWorkOrders = await this.getWorkOrders(vesselId);
    const activeWorkOrderKeys = new Set(
      allWorkOrders
        .filter(wo => ['Active', 'Due', 'Due (Grace P)', 'Overdue', 'Pending Approval'].includes(wo.status))
        .map(wo => `${wo.vesselId}|${wo.componentCode}|${wo.jobTitle}`)
    );
    
    const results = {
      checked: calendarJobs.length,
      generated: 0,
      workOrders: [] as WorkOrder[]
    };
    
    // Check each job to see if it should generate a work order based on lead time
    for (const job of calendarJobs) {
      // Get vessel settings for this job's vessel
      const settings = await getSettingsForVessel(job.vesselId);
      
      // Get appropriate lead time based on job priority
      const leadTimeDays = getCalendarLeadDays(job, settings);
      
      // Apply lead time when checking if work order should be generated
      const shouldGenerate = shouldGenerateWorkOrder(job.nextDueDate, new Date(), leadTimeDays);
      
      if (shouldGenerate) {
        // O(1) duplicate check using Set (key includes vesselId)
        const workOrderKey = `${job.vesselId}|${job.componentCode}|${job.jobTitle}`;
        
        if (!activeWorkOrderKeys.has(workOrderKey)) {
          // Generate spec-compliant work order number: <JOB CODE>.WO-<YEAR>-<RUNNING NUMBER>
          const workOrderNo = await generatePlannedWorkOrderNumber(storage, job.jobNo, job.vesselId || undefined);
          
          const workOrderData: InsertWorkOrder = {
            vesselId: job.vesselId,
            component: job.componentName, // Use component name, not ID
            componentCode: job.componentCode,
            workOrderNo: workOrderNo,
            templateCode: workOrderNo,
            jobTitle: job.jobTitle,
            assignedTo: job.assignedTo || 'Unassigned',
            dueDate: job.nextDueDate,
            status: 'Active',
            taskType: job.maintenanceType,
            maintenanceBasis: job.maintenanceBasis,
            frequencyValue: job.frequencyValue?.toString(),
            frequencyUnit: job.frequencyUnit,
            jobPriority: job.jobPriority,
            classRelated: job.classRelated,
            briefWorkDescription: job.briefWorkDescription,
            department: job.department,
            requiredSpareParts: job.requiredSpareParts || [],
            requiredTools: job.requiredTools || [],
            safetyRequirements: job.safetyRequirements || {
              ppeRequirements: [],
              permitRequirements: [],
              otherRequirements: []
            }
          };
          
          const createdWO = await this.createWorkOrder(workOrderData);
          results.generated++;
          results.workOrders.push(createdWO);
          
          // Add to Set to prevent duplicate generation in same run (key includes vesselId)
          activeWorkOrderKeys.add(workOrderKey);
          
          const priorityLabel = isJobCritical(job) ? 'Critical' : 'Non-Critical';
          console.log(`✅ Auto-generated work order ${workOrderNo} for ${priorityLabel} job ${job.jobNo} (lead time: ${leadTimeDays} days)`);
        }
      }
    }
    
    // Log settings used for transparency
    if (settingsCache.size > 0) {
      Array.from(settingsCache.entries()).forEach(([vId, settings]) => {
        if (settings) {
          console.log(`📋 [Calendar WO Gen] Vessel ${vId} lead times: Critical=${settings.calendarLeadDaysCritical}d, Non-Critical=${settings.calendarLeadDaysNonCritical}d`);
        } else {
          console.log(`⚠️ [Calendar WO Gen] Vessel ${vId} has no PMS settings configured, using 0 day lead time`);
        }
      });
    }
    
    return results;
  }

  /**
   * Bulk create work orders
   */
  async bulkCreateWorkOrders(workOrders: InsertWorkOrder[]): Promise<WorkOrder[]> {
    return storage.bulkCreateWorkOrders(workOrders);
  }

  /**
   * Bulk update work orders
   */
  async bulkUpdateWorkOrders(workOrders: Array<{ templateCode: string; data: Partial<WorkOrder> }>): Promise<WorkOrder[]> {
    return storage.bulkUpdateWorkOrders(workOrders);
  }

  /**
   * Bulk upsert work orders
   */
  async bulkUpsertWorkOrders(workOrders: InsertWorkOrder[]): Promise<{ created: number; updated: number }> {
    return storage.bulkUpsertWorkOrders(workOrders);
  }
}

// Export singleton instance
export const workOrderService = new WorkOrderService();
