export {
  workOrders,
  insertWorkOrderSchema,
  workOrderExecutions,
  insertWorkOrderExecutionSchema,
  workOrderExecutionDetails,
  insertWorkOrderExecutionDetailsSchema,
  components,
  jobs,
  insertJobSchema as sharedInsertJobSchema,
  spares,
  pmsVesselSettings,
  componentMaintenanceHistory,
  insertComponentMaintenanceHistorySchema,
  inventoryTransactions,
  insertInventoryTransactionSchema,
  spareLocationStock,
  insertSpareLocationStockSchema,
  spareComponentLinks,
  locations,
  insertLocationSchema,
  jobComponentLinks,
} from "@shared/schema";

export type {
  WorkOrder,
  InsertWorkOrder,
  WorkOrderExecution,
  InsertWorkOrderExecution,
  WorkOrderExecutionDetails,
  InsertWorkOrderExecutionDetails,
  Component,
  Job,
  Spare,
  PmsVesselSettings,
  ComponentMaintenanceHistory,
  InsertComponentMaintenanceHistory,
  InventoryTransaction,
  InsertInventoryTransaction,
  SpareLocationStock,
  InsertSpareLocationStock,
  SpareComponentLink,
  Location,
  InsertLocation,
} from "@shared/schema";
