import ExcelJS from 'exceljs';

// ═══════════════════════════════════════════════════════════════
// PROFESSIONAL MARITIME THEME - STANDARD COLOR PALETTE
// Matches the PMS application UI theme
// ═══════════════════════════════════════════════════════════════

export const COLORS = {
  // Primary colors (match app sidebar/headers)
  primary: 'FF1E5A8E',      // Deep blue - sidebar color
  secondary: 'FF5DADE2',    // Light blue - table headers
  
  // Status colors
  success: 'FF52C41A',      // Green
  warning: 'FFFAAD14',      // Amber
  danger: 'FFF5222D',       // Red - USE SPARINGLY
  
  // Text colors
  textDark: 'FF2C3E50',     // Dark blue-gray
  textLight: 'FF5A6C7D',    // Medium gray
  textWhite: 'FFFFFFFF',    // White
  
  // Background colors (subtle)
  bgLight: 'FFF7F9FC',      // Very light blue-gray (alternating rows)
  bgWhite: 'FFFFFFFF',      // White
  bgSuccess: 'FFF6FFED',    // Very light green (completed items)
  bgWarning: 'FFFFFBE6',    // Very light amber (warnings)
  bgDanger: 'FFFFF1F0',     // Very light red (critical items ONLY)
  
  // Border colors
  border: 'FFE1E8ED',       // Light gray
  borderMedium: 'FF1E5A8E', // Deep blue for emphasis
};

// Report-specific accent colors (only used for summary section emphasis)
export const REPORT_ACCENTS = {
  dueJobs: COLORS.secondary,     // Blue accent
  overdueJobs: COLORS.warning,   // Amber accent (NOT red!)
  completedJobs: COLORS.success, // Green accent
  default: COLORS.secondary,     // Blue accent
};

export interface ReportConfig {
  sheetName: string;
  reportTitle: string;
  reportSubtitle: string;
  vesselName: string;
  totalColumns: number;
  columns: ColumnDef[];
  data: any[];
  summary: SummaryItem[];
  reportType?: 'dueJobs' | 'overdueJobs' | 'completedJobs' | 'default';
}

export interface ColumnDef {
  key: string;
  header: string;
  width: number;
  align?: 'left' | 'center' | 'right';
  type?: 'text' | 'number' | 'date';
}

export interface SummaryItem {
  label: string;
  value: string | number;
  highlight?: boolean; // If true, use red color for value
}

// ═══════════════════════════════════════════════════════════════
// SECTION 1: REPORT HEADER (Rows 1-6)
// ═══════════════════════════════════════════════════════════════

export function applyStandardHeader(
  worksheet: ExcelJS.Worksheet,
  reportTitle: string,
  reportSubtitle: string,
  vesselName: string,
  totalRecords: number,
  lastColumn: string
): void {
  const reportDate = new Date();
  const formatDate = (d: Date) => {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${d.getDate().toString().padStart(2, '0')}-${months[d.getMonth()]}-${d.getFullYear()} ${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`;
  };

  // Row 1: Company/System Title - Deep Blue background
  worksheet.mergeCells(`A1:${lastColumn}1`);
  const titleCell = worksheet.getCell('A1');
  titleCell.value = 'SEAFARER TECHNICAL MANAGEMENT SYSTEM';
  titleCell.font = { size: 14, bold: true, color: { argb: COLORS.textWhite }, name: 'Arial' };
  titleCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: COLORS.primary }
  };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  worksheet.getRow(1).height = 30;

  // Row 2: Report Title - Light gray background with deep blue text
  worksheet.mergeCells(`A2:${lastColumn}2`);
  const subtitleCell = worksheet.getCell('A2');
  subtitleCell.value = reportTitle;
  subtitleCell.font = { size: 12, bold: true, color: { argb: COLORS.textDark }, name: 'Arial' };
  subtitleCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: COLORS.bgLight }
  };
  subtitleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  subtitleCell.border = {
    bottom: { style: 'medium', color: { argb: COLORS.primary } }
  };
  worksheet.getRow(2).height = 25;

  // Row 3: Empty separator
  worksheet.getRow(3).height = 10;

  // Row 4: Vessel & Date Info
  worksheet.getCell('A4').value = `Vessel: ${vesselName}`;
  worksheet.getCell('A4').font = { bold: true, size: 10, color: { argb: COLORS.textDark }, name: 'Arial' };
  
  // Right side - Report Date (merge last 3 columns)
  const dateColStart = String.fromCharCode(lastColumn.charCodeAt(0) - 2);
  worksheet.mergeCells(`${dateColStart}4:${lastColumn}4`);
  worksheet.getCell(`${dateColStart}4`).value = `Report Date: ${formatDate(reportDate)}`;
  worksheet.getCell(`${dateColStart}4`).font = { size: 10, color: { argb: COLORS.textLight }, name: 'Arial' };
  worksheet.getCell(`${dateColStart}4`).alignment = { horizontal: 'right' };
  worksheet.getRow(4).height = 18;

  // Row 5: Generated By & Total Records
  worksheet.getCell('A5').value = 'Generated By: PMS System';
  worksheet.getCell('A5').font = { size: 9, color: { argb: COLORS.textLight }, name: 'Arial' };
  
  worksheet.mergeCells(`${dateColStart}5:${lastColumn}5`);
  worksheet.getCell(`${dateColStart}5`).value = `Total Records: ${totalRecords}`;
  worksheet.getCell(`${dateColStart}5`).font = { bold: true, size: 9, color: { argb: COLORS.primary }, name: 'Arial' };
  worksheet.getCell(`${dateColStart}5`).alignment = { horizontal: 'right' };
  worksheet.getRow(5).height = 18;

  // Row 6: Empty separator
  worksheet.getRow(6).height = 5;
}

// ═══════════════════════════════════════════════════════════════
// SECTION 2: TABLE HEADER (Row 7) - Light Blue
// ═══════════════════════════════════════════════════════════════

export function applyStandardTableHeader(
  worksheet: ExcelJS.Worksheet,
  columns: ColumnDef[],
  headerRowNum: number = 7
): void {
  // Set column widths
  columns.forEach((col, idx) => {
    worksheet.getColumn(idx + 1).width = col.width;
  });

  // Add header values
  const headerRow = worksheet.getRow(headerRowNum);
  columns.forEach((col, idx) => {
    headerRow.getCell(idx + 1).value = col.header;
  });

  // Style header row - Light Blue (#5DADE2)
  headerRow.eachCell((cell, colNumber) => {
    if (colNumber <= columns.length) {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: COLORS.secondary }
      };
      cell.font = { bold: true, color: { argb: COLORS.textWhite }, size: 10, name: 'Arial' };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin', color: { argb: COLORS.textWhite } },
        left: { style: 'thin', color: { argb: COLORS.textWhite } },
        bottom: { style: 'thin', color: { argb: COLORS.textWhite } },
        right: { style: 'thin', color: { argb: COLORS.textWhite } }
      };
    }
  });
  headerRow.height = 25;
}

// ═══════════════════════════════════════════════════════════════
// SECTION 3: DATA ROWS - Subtle alternating with conditional styling
// ═══════════════════════════════════════════════════════════════

export interface ConditionalStyle {
  condition: (row: any) => boolean;
  style: 'success' | 'warning' | 'danger';
  textOnly?: boolean; // If true, only style text, not background
}

export function applyStandardDataRows(
  worksheet: ExcelJS.Worksheet,
  data: any[],
  columns: ColumnDef[],
  dataStartRow: number = 8,
  conditionalStyles?: ConditionalStyle[]
): void {
  if (data.length === 0) {
    const emptyRow = worksheet.getRow(dataStartRow);
    emptyRow.getCell(1).value = 'No records found';
    worksheet.mergeCells(dataStartRow, 1, dataStartRow, columns.length);
    emptyRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    emptyRow.getCell(1).font = { italic: true, color: { argb: COLORS.textLight }, size: 11, name: 'Arial' };
    emptyRow.height = 30;
    return;
  }

  data.forEach((record, index) => {
    const rowNum = dataStartRow + index;
    const row = worksheet.getRow(rowNum);
    
    // Set cell values
    columns.forEach((col, colIdx) => {
      const cellValue = record[col.key];
      row.getCell(colIdx + 1).value = cellValue !== undefined && cellValue !== null ? cellValue : '-';
    });

    row.height = 20;

    // Determine base background color (alternating)
    const isEvenRow = index % 2 === 1;
    const baseColor = isEvenRow ? COLORS.bgLight : COLORS.bgWhite;

    // Check for conditional styles
    let appliedStyle: 'success' | 'warning' | 'danger' | null = null;
    let textOnly = false;
    
    if (conditionalStyles) {
      for (const cs of conditionalStyles) {
        if (cs.condition(record)) {
          appliedStyle = cs.style;
          textOnly = cs.textOnly || false;
          break; // Apply first matching condition only
        }
      }
    }

    // Apply styling to each cell
    row.eachCell((cell, colNum) => {
      if (colNum > columns.length) return;

      const colDef = columns[colNum - 1];
      
      // Background color
      let bgColor = baseColor;
      let fontColor = COLORS.textDark;
      let isBold = false;

      if (appliedStyle && !textOnly) {
        switch (appliedStyle) {
          case 'success':
            bgColor = COLORS.bgSuccess;
            fontColor = COLORS.success;
            break;
          case 'warning':
            bgColor = COLORS.bgWarning;
            fontColor = 'FF9C6500'; // Dark orange
            isBold = true;
            break;
          case 'danger':
            bgColor = COLORS.bgDanger;
            fontColor = 'FF9C0006'; // Dark red
            isBold = true;
            break;
        }
      }

      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: bgColor }
      };

      cell.font = { 
        color: { argb: fontColor }, 
        size: 9, 
        name: 'Arial',
        bold: isBold
      };

      cell.border = {
        top: { style: 'thin', color: { argb: COLORS.border } },
        left: { style: 'thin', color: { argb: COLORS.border } },
        bottom: { style: 'thin', color: { argb: COLORS.border } },
        right: { style: 'thin', color: { argb: COLORS.border } }
      };

      // Alignment based on column type
      if (colDef.type === 'number' || colDef.align === 'right') {
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
      } else if (colDef.type === 'date' || colDef.align === 'center') {
        cell.alignment = { horizontal: 'center', vertical: 'middle' };
      } else {
        cell.alignment = { horizontal: 'left', vertical: 'middle' };
      }
    });
  });
}

// ═══════════════════════════════════════════════════════════════
// SECTION 4: SUMMARY SECTION
// ═══════════════════════════════════════════════════════════════

export function applyStandardSummary(
  worksheet: ExcelJS.Worksheet,
  summary: SummaryItem[],
  startRow: number,
  totalColumns: number,
  actionNote?: string
): number {
  // Add thick border line above summary
  for (let col = 1; col <= totalColumns; col++) {
    const borderCell = worksheet.getRow(startRow - 1).getCell(col);
    borderCell.border = {
      bottom: { style: 'medium', color: { argb: COLORS.primary } }
    };
  }

  // Summary Header
  worksheet.getCell(`A${startRow}`).value = 'SUMMARY:';
  worksheet.getCell(`A${startRow}`).font = { bold: true, size: 11, color: { argb: COLORS.primary }, name: 'Arial' };
  worksheet.getCell(`A${startRow}`).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: COLORS.bgLight }
  };

  // Summary items
  summary.forEach((item, idx) => {
    const rowNum = startRow + 1 + idx;
    worksheet.getCell(`A${rowNum}`).value = item.label;
    worksheet.getCell(`A${rowNum}`).font = { size: 9, color: { argb: COLORS.textDark }, name: 'Arial' };
    
    worksheet.getCell(`B${rowNum}`).value = item.value;
    worksheet.getCell(`B${rowNum}`).font = { 
      bold: true, 
      size: 9, 
      name: 'Arial',
      color: item.highlight && Number(item.value) > 0 
        ? { argb: COLORS.danger } 
        : { argb: COLORS.primary }
    };
  });

  let lastRow = startRow + summary.length;

  // Action note (optional)
  if (actionNote) {
    lastRow += 2;
    const lastColLetter = String.fromCharCode('A'.charCodeAt(0) + totalColumns - 1);
    worksheet.mergeCells(`A${lastRow}:${lastColLetter}${lastRow}`);
    
    const noteCell = worksheet.getCell(`A${lastRow}`);
    noteCell.value = actionNote;
    noteCell.font = { size: 9, italic: true, color: { argb: COLORS.textLight }, name: 'Arial' };
    noteCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: COLORS.bgWarning }
    };
    noteCell.alignment = { horizontal: 'left', vertical: 'middle' };
    noteCell.border = {
      top: { style: 'medium', color: { argb: COLORS.warning } },
      bottom: { style: 'medium', color: { argb: COLORS.warning } },
      left: { style: 'medium', color: { argb: COLORS.warning } },
      right: { style: 'medium', color: { argb: COLORS.warning } }
    };
    worksheet.getRow(lastRow).height = 25;
  }

  return lastRow;
}

// ═══════════════════════════════════════════════════════════════
// SECTION 5: PAGE SETUP
// ═══════════════════════════════════════════════════════════════

export function applyStandardPageSetup(
  worksheet: ExcelJS.Worksheet,
  headerRowNum: number,
  totalColumns: number,
  lastRow: number,
  vesselName: string
): void {
  const lastColLetter = String.fromCharCode('A'.charCodeAt(0) + totalColumns - 1);

  worksheet.pageSetup = {
    orientation: 'landscape',
    paperSize: 9, // A4
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    printArea: `A1:${lastColLetter}${lastRow}`,
    margins: {
      left: 0.5,
      right: 0.5,
      top: 0.5,
      bottom: 0.5,
      header: 0.3,
      footer: 0.3
    }
  };

  // Print title rows
  worksheet.pageSetup.printTitlesRow = `${headerRowNum}:${headerRowNum}`;

  // Footer
  worksheet.headerFooter = {
    oddFooter: `&L&8&"Arial"Confidential - ${vesselName}&C&8&"Arial"Page &P of &N&R&8&"Arial"Generated: &D &T`
  };
}

// ═══════════════════════════════════════════════════════════════
// UTILITY: Generate professional filename
// ═══════════════════════════════════════════════════════════════

export function generateFilename(reportName: string, vesselName: string): string {
  const now = new Date();
  const dateStr = `${now.getFullYear()}${(now.getMonth()+1).toString().padStart(2,'0')}${now.getDate().toString().padStart(2,'0')}`;
  const timeStr = `${now.getHours().toString().padStart(2,'0')}${now.getMinutes().toString().padStart(2,'0')}`;
  const safeVesselName = vesselName.replace(/[^a-zA-Z0-9]/g, '_');
  const safeReportName = reportName.replace(/[^a-zA-Z0-9]/g, '');
  return `PMS_${safeReportName}_${safeVesselName}_${dateStr}_${timeStr}.xlsx`;
}

// ═══════════════════════════════════════════════════════════════
// UTILITY: Get last column letter from column count
// ═══════════════════════════════════════════════════════════════

export function getLastColumnLetter(columnCount: number): string {
  if (columnCount <= 26) {
    return String.fromCharCode('A'.charCodeAt(0) + columnCount - 1);
  }
  // Handle columns beyond Z (AA, AB, etc.)
  const first = Math.floor((columnCount - 1) / 26);
  const second = (columnCount - 1) % 26;
  return String.fromCharCode('A'.charCodeAt(0) + first - 1) + String.fromCharCode('A'.charCodeAt(0) + second);
}
